### ISSUE TITLE
Single test suite with multiple conversation test cases

### ISSUE THREAD

**Issue by tenhsor1** [promptfoo/promptfoo#1020]
I want to have multiple different conversations to be part of a single test suite, there's a way to do this?

ie:
```
description: 'Global Test Suite'

prompts: [prompt.json]

providers:
 - openai:gpt-4o

tests:
  - description: "Test Conversation 1"
    - vars:
        question: Who founded Facebook?
    - vars:
        question: Where does he live?
    - vars:
        question: Which state is that in?
  # This test is independent from previous one, with a different prompt/conversation variable altogether
  - description: "Test Conversation 2"
    - vars:
      question: Who founded Twitter?
    - vars:
      question: "Is he into Bitcoin?"
 ```
` prompt.json`:
 ```
 [
  {% for completion in _conversation %}
    {
      "role": "user",
      "content": "{{ completion.input }}"
    },
    {
      "role": "assistant",
      "content": "{{ completion.output }}"
    },
  {% endfor %}
  {
    "role": "user",
    "content": "{{ question }}"
  }
]
 ```
 
Where ideally, each vars could have its own assertion as well.
The idea is that each test would restart/reset the `conversation` array, so no context gets carried over

**Comment by mldangelo** [comment]
Thanks for the detailed feature request! This is actually already supported using the `conversationId` metadata field.

Here's your exact use case with the current syntax:

```yaml
# promptfooconfig.yaml
description: 'Global Test Suite'

prompts:
  - file://prompt.json

providers:
  - openai:gpt-4o

tests:
  # Test Conversation 1
  - vars:
      question: Who founded Facebook?
    metadata:
      conversationId: conversation_1
  - vars:
      question: Where does he live?
    metadata:
      conversationId: conversation_1
  - vars:
      question: Which state is that in?
    metadata:
      conversationId: conversation_1
    assert:
      - type: contains
        value: California

  # Test Conversation 2 (independent, no context from conversation 1)
  - vars:
      question: Who founded Twitter?
    metadata:
      conversationId: conversation_2
  - vars:
      question: Is he into Bitcoin?
    metadata:
      conversationId: conversation_2
    assert:
      - type: icontains
        value: yes
```

Each turn can have its own assertions. Tests with the same `conversationId` share conversation history via the `_conversation` variable, while different conversation IDs are completely isolated.

Your prompt template would look like:

```json
[
  {% for completion in _conversation %}
    {
      "role": "user",
      "content": "{{ completion.input }}"
    },
    {
      "role": "assistant",
      "content": "{{ completion.output }}"
    },
  {% endfor %}
  {
    "role": "user",
    "content": "{{ question }}"
  }
]
```

**Resources:**
- [Multi-turn conversation docs](https://www.promptfoo.dev/docs/configuration/chat/#separating-chat-conversations)
- [Full working example](https://github.com/promptfoo/promptfoo/tree/main/examples/multiple-turn-conversation)

Closing as this is already supported. Let us know if you have any questions!
