### ISSUE TITLE
Can't specify OpenAI organisation configuration

### ISSUE THREAD

**Issue by jimioh** [promptfoo/promptfoo#105]
Currently the OpenAI organisation key is not supported. It would be great if I could configure it, thanks.

**Comment by typpo** [comment]
Support for `OPENAI_ORGANIZATION` environment variable will be released in 0.19.1.

You will also be able to specify with:
```yaml
providers:
  - openai:chat:gpt-3.5-turbo-0613:
      config:
        organization: org-xyz
```
