### ISSUE TITLE
Allow filtering test cases (inside scenarios)

### ISSUE THREAD

**Issue by aantn** [promptfoo/promptfoo#1061]
Given the following scenario, I want to only run test on the Spanish language:

```
scenarios:
  - config:
      - vars:
          language: Spanish
          expectedHelloWorld: 'Hola mundo'
      - vars:
          language: French
          expectedHelloWorld: 'Bonjour le monde'

    tests:
      # this isn't templated
      - description: Translated Hello World from {{ language }}
        vars:
          input: 'Hello world'
      - description: Translated Good Morning {{ language }}
        vars:
          input: 'Good morning'
```

I'm unable to filter with `--filter-pattern=Spanish` because the scenarios.tests.description field is not templated. Templating that field would fix this.

Alternatives:
* Add a new --filter-test-case flag which filters scenarios.configs instead

**Comment by maeltha** [comment]
Hi, 
I also would be interested in this feature. From https://github.com/promptfoo/promptfoo/issues/987
I read that however the "normal" filtering without variables  in the description field should work already? Or is there something missing? I tried with this code:  
 
```
scenarios:
  - config:
    - vars:
        prompt: file://./prompt.txt
        format_instructions: file://./format_instructions.txt
    tests:
      - description: 'test'
        vars:
```

but when I execute `promptfoo eval --filter-pattern 'something'` the test is executed nonetheless..
using promtfoo 0.100.5

Thanks for some advice and if the feature including templating is planned to be implemented
