### ISSUE TITLE
Error running example classifier assertion

### ISSUE THREAD

**Issue by lacom** [promptfoo/promptfoo#1082]
Version 0.68.2

Take the example config generated by `init` and add a classifier type assertion to the test that uses a HuggingFace model. This classifier example is taken straight from the docs:

```
# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide
description: "My eval"

prompts:
  - "Write a tweet about {{topic}}"
  - "Write a concise, funny tweet about {{topic}}"
  

providers:
  - "openai:gpt-3.5-turbo"
  - "openai:gpt-4o"
  

tests:
  - vars:
      topic: new york city
    assert:
      # For more information on model-graded evals, see https://promptfoo.dev/docs/configuration/expected-outputs/model-graded
      - type: llm-rubric
        value: ensure that the output is funny

      - type: classifier
        provider: huggingface:text-classification:facebook/roberta-hate-speech-dynabench-r4-target
        value: nothate
        threshold: 0.5
```

Running `eval` fails with error:
`TypeError: Cannot assign to read only property 'options' of object '#<Object>' at runAssertion...`
