### ISSUE TITLE
allowedColumns does not work

### ISSUE THREAD

**Issue by SysOverdrive** [promptfoo/promptfoo#1128]
Hi guys,

I think I uncovered a new bug in promtfoo, namely in regards to the allowed columns functionality.

### Configuration
Given the following assertion:
```
- description: "Specific SQL Assertion"
  vars:
    question: |
      Give me deliveries with delivery date as 01/01/2021
    database: file://sql/delivery_ddl.sql
  assert:
    # Ensure output is a valid SQL query
    - type: is-sql
      value:
        allowedTables:
          - select::null::delivery_table # select::::delivery_table
        allowedColumns:
          - select::null::deliverydate 
```
### Actual Behaviour
I recieve the following error :

SQL validation failed: authority = 'select::null::(.*)' is required in column whiteList to execute SQL = 'SELECT * FROM delivery_table WHERE deliverydate = '2021-01-01''.

### Expected Beehavior 👍

Assert is executed with Pass and no error is displayed.

### Context from delivery_ddl.sql:
```
CREATE TABLE delivery_table (
.
.
.
    deliverydate DATE,

.
.
.
);
```

### Comments:
 The suggestion I recieve from the error is to basically let any column name pass but that is not my intended behaviour.

Do you guys have any recommendation on how to proceed ?
