### ISSUE TITLE
Request: link in variables

### ISSUE THREAD

**Issue by ilia-iliev** [promptfoo/promptfoo#1144]
It would be useful to have a clickable URL as a variable in the evaluation web viewer. Currently, the tag <a href=> is being escaped and I'd love a way to be able to pass a working link.

Example of what I'd like to be able to do:
![Screenshot from 2024-07-12 18-23-24](https://github.com/user-attachments/assets/14369542-ab7d-4848-8019-a489c3582d57)

**Comment by mldangelo** [comment]
Thanks for the question / feature request. Would you mind sharing an example from your config?

I believe you can do this now as markdown. Try:

```yaml
tests:
  - vars:
      topic: bananas
      url: '[promptfoo](https://www.promptfoo.dev/)'
```

And under table settings click: `render as markdown`. Note the quotes (`'`) around URL. Let us know if you have any other questions / comments / thoughts / feedback. Thanks!
