### ISSUE TITLE
Script provider is asking me to supply OPEN_AI_KEY

### ISSUE THREAD

**Issue by geekyme-fsmk** [promptfoo/promptfoo#116]
Getting this error when I run the evaluation:

```
[FAIL] Error: OpenAI API key is not set. Set OPENAI_API_KEY environment variable or pass it as an argument to the constructor. Error: OpenAI API key is not set. Set OPENAI_API_KEY environment variable or pass it as an argument to the constructor.
--
```

https://www.promptfoo.dev/docs/configuration/testing-llm-chains#using-a-script-provider

Following the guide above, I set up a custom script provider:

```
prompts:
  - tests/prompt/prompt1.txt
providers:
  - exec:poetry run python tests/prompt/ai_client_provider.py
tests:
  - vars:
      question: What's the weather in New York?
    assert:
      - type: llm-rubric
        value: does not claim to know the current weather in New York
```

How the `ai_client_provider.py` looks like:
```
import sys
from app.clients.ai_client import AIClient
from app.services.intent_service import IntentService

conversation_id = "dummy"
admin_id = "dummy"
ai_client = AIClient()
intent = IntentService(conversation_id, admin_id, ai_client.vectorstores)

chat_history = []
question = sys.argv[1]
response_text = ai_client.get_response(question, chat_history, intent)

print(response_text)
```

`AIClient` internally would load its own azure openai keys and secrets. Not sure why I am getting the errors [from here](https://github.com/promptfoo/promptfoo/blob/main/src/providers/openai.ts#L149-L153) when I've already specified a custom script. 

My config does not appear to be going down the [script completion path](https://github.com/promptfoo/promptfoo/blob/main/src/providers.ts#L73-L78).

`promptfoo --version`
=> 0.20.1
