### ISSUE TITLE
How to set proper Azure config?

### ISSUE THREAD

**Issue by Stephenzza** [promptfoo/promptfoo#1224]
```
from openai import AzureOpenAI

client = AzureOpenAI(
    azure_endpoint="",
    api_key="",
    api_version="",
    azure_deployment="",
)
response = client.chat.completions.create(
  model="gpt-4o-mini",
  messages=[
    {"role": "user", "content": test}
  ]
)
```
 I couldn't set them up successfully due to the `azure_deployment` parameter. 
Any suggestions?

**Comment by typpo** [comment]
Hi @Stephenzza, have you taken a look at these docs? https://www.promptfoo.dev/docs/providers/azure/

If so, could you share the config you're using and what error you see?

**Comment by Stephenzza** [comment]
Thank you for your response! I briefly reviewed the source code and noticed that the model parameter in the body is the same as the deployment parameter. However, in my use case, they are set separately. I tried configuring it this way, but it didn't work. Could you please advise me on how to set it up correctly? Thanks a lot!
```
providers:
  - id: azureopenai:completion:gpt-4o
    config:
      apiBaseUrl: "xxx.azure.com/openai/deployments/{my_deployment_name}"
      apiKey: "xxx"
      apiVersion: "xxx"
```
