### ISSUE TITLE
weighted assertions

### ISSUE THREAD

**Issue by zhlmmc** [promptfoo/promptfoo#124]
![image](https://github.com/promptfoo/promptfoo/assets/1726527/5d7e7692-07a6-4299-9711-a3272702a3c1)

As stated in above image, the doc is wrong?

Also, I want to know how do I get the score and specify above which score is considered as PASS?

**Comment by typpo** [comment]
Hi @zhlmmc,

Thanks for the catch, looks like score should be 0.33!  I'll fix the docs.

The combined weighted score is shown in the results view for each output when you run `promptfoo view`.  The aggregate score for each prompt is included at the top of each table column.

Right now, pass/fail is determined on a per-assert basis.  If a single assert fails, there is an overall failure.  For numeric responses, you can set a pass threshold using the `threshold` property on individual asserts.  Would it help to have a pass/fail threshold per test case?  That would be pretty easy to add.

**Comment by typpo** [comment]
0.21.4 adds an optional threshold property to the test case object. If set, the pass/fail status of a test case is determined by whether the combined weighted score of all assertions exceeds the threshold value.

For example:

```yaml
tests:
  threshold: 0.5
  assert:
    - type: equals
      value: "Hello world"
      weight: 2
    - type: contains
      value: "world"
      weight: 1
```

If the LLM outputs `Goodbye world`, the equals assertion fails but the contains assertion passes and the final score is 0.33. Because this is below the 0.5 threshold, the test case fails. If the threshold were lowered to 0.2, the test case would succeed.
