### ISSUE TITLE
Question: Is there a way for your prompt to contain a brackeded ( {json} ) json and the vars: to ignore that ? 

### ISSUE THREAD

**Issue by SysOverdrive** [promptfoo/promptfoo#1258]
I have an llm app I want to test without making heavy changes to the prompt

Given the following prompt example:

```
**JSON Response Structure:**
The top-level JSON structure (note this is an empty example) for ALL messages is:

```{"MyTitle":"","renderType":"","Myvalue":""}```

...
other parts of the prompt
...

The question is : {question}
```

is there a way to specify and assertion yaml config that would not take the first set of brackets, basically the json definition, as a vars ?

```
- description: "Simple SQL Contains Assertions"
  vars:
    question: Can you give me the first 10 renders? 
  assert:
    - type: icontains-all
      value: ["SELECT", "FROM"]
```
