### ISSUE TITLE
sending non-string objects through the yaml file

### ISSUE THREAD

**Issue by rishimalhotra2** [promptfoo/promptfoo#1265]
Hi, i would like to send in complex non-string payload in my post request. Specifically, I want to create a list of lists in my chat_history and send that through my post request. Here is what that looks like

```yaml
name: 'my Tests'
prompts: 
  - 'file://../model/prompts/*.txt'
providers:
  - id: 'http://localhost:5000/api/query_no_stream'
    config:
      method: 'POST'
      headers:
        'Content-Type': 'application/json'
      body:
        question: "{{question}}"
        chat_history: 
        conversation_id: empty
        scenario: my_scenario
      responseParser: 'json.answer'
tests:
  - vars:
      question: What's the eather like?
      chat_history:
        - - 'hi'
          - 'hello'
        - - 'how are you'
          - 'I am good'
      reference: No ref
```

However, when i do this, the server receives the chat_history as `{'[object Object]': None}` instead of the nested lists. I know you use nunjucks as the templating engine. I tried using `{{chat_history | dump}}` but that tends to send the whole thing as a string instead of nested lists.

What's the easiest way to accomplish what I'm trying to achieve?
