### ISSUE TITLE
`{#` causes `Template render error`

### ISSUE THREAD

**Issue by mrBen** [promptfoo/promptfoo#1283]
I have a test case that contain `{#` in a variable.
I systematically get the following error:

    /usr/local/share/npm-global/lib/node_modules/promptfoo/node_modules/nunjucks/src/lib.js:32
        err = new Error(old.message);
              ^
    
    Template render error: (unknown path)
      Error: expected end of comment, got end of file
        at Object._prettifyError (/usr/local/share/npm-global/lib/node_modules/promptfoo/node_modules/nunjucks/src/lib.js:32:11)
        at Template.render (/usr/local/share/npm-global/lib/node_modules/promptfoo/node_modules/nunjucks/src/environment.js:442:21)
        at Environment.renderString (/usr/local/share/npm-global/lib/node_modules/promptfoo/node_modules/nunjucks/src/environment.js:313:17)
        at renderPrompt (/usr/local/share/npm-global/lib/node_modules/promptfoo/dist/src/evaluator.js:232:25)
        at async Evaluator.runEval (/usr/local/share/npm-global/lib/node_modules/promptfoo/dist/src/evaluator.js:267:32)
        at async processEvalStep (/usr/local/share/npm-global/lib/node_modules/promptfoo/dist/src/evaluator.js:627:25)
    
    Node.js v20.15.1

I’m pretty sure it’s because `{#` indicate the begining of a comment in Nunjucks, but couldn’t the variables be sanitized?

**Comment by mrBen** [comment]
The issues occurs when the prompt come from Python or JS, e.g.

promptfooconfig.yaml:

    prompts:
      - prompt.js
    
    providers:
      - "ollama:phi3"
    
    tests:
      - vars:
          topic: ban{#anas

prompt.js:

    module.exports = async function ({ vars, provider }) {
        return [
          {
            role: 'user',
            content: `Write a tweet about ${vars.topic}`,
          },
        ];
      };

**Comment by mldangelo** [comment]
@mrBen This is a great question about a sharp edge in promptfoo and is something our documentation currently does not explain well.

You can escape it as `{{'ban{#anas'}}`.

For example:

```yaml
prompts:
  - "Write a tweet about {{topic}}"
providers:
  - "openai:gpt-4o-mini"
tests:
  - vars:
      # does not need to be escaped
      topic: ban{#anas
    assert:
      - type: contains
        # needs to be escaped with {{'escaped content'}}
        value: "{{'ban{#anas'}}"
```

I wrote a more detailed answer to a similar question yesterday: https://github.com/promptfoo/promptfoo/issues/1258#issuecomment-2247933607 

I hope this helps!
