### ISSUE TITLE
Provider "prompts" filter does not work when importing provider from a file

### ISSUE THREAD

**Issue by orange-anjou** [promptfoo/promptfoo#1307]
**Describe the bug**
The filter does not work, here is seen behavior :
- phi3 model X phi3 template prompt
- phi3 model X gemma template prompt
- gemma model  X phi3 template prompt
- gemma model  X gemma template prompt

**To Reproduce**

**config.yml**
```yaml
# We define the models prompt templates, used to structure the whole prompt.
# The tool iterate over those, and for each one, will add iteration depending on the variables / providers to use.
prompts:
  - id: "{{phi3_template_prompt}}"
    label: phi3_template_prompt
  - id: "{{gemma_template_prompt}}"
    label: gemma_template_prompt

# Providers are the models that will be used to answer the prompts.
providers:
  - file://./providers/phi3.t_0.tokens_1024.yml
  - file://./providers/gemma.t_0.tokens_1024.yml

# Global variables and assertions that are used in all tests.
defaultTest:
  vars:
    # Template prompts source files, then used in the `prompts` section.
    phi3_template_prompt: file://./prompts/model-templates/phi3.txt
    gemma_template_prompt: file://./prompts/model-templates/gemma.txt
    # System prompts source files, then used in the `providers` section.
    system_prompt_list: [
      file://./prompts/agent-system-prompts/api-event-expert/phi3.v001.txt,
      file://./prompts/agent-system-prompts/dumb.txt
    ]
```

**gemma.t_0.tokens_1024.yml**
```yaml
id: ollama:gemma:2b
label: "[gemma:2b] | temperature 0 | tokens 1024"
prompts:
  - gemma_template_prompt
config:
  temperature: 0
  max_tokens: 1024
```

**phi3.t_0.tokens_1024.yml**
```yaml
id: ollama:chat:phi3:mini
label: "[phi3:mini] | temperature 0 | tokens 1024"
prompts:
  - phi3_template_prompt
config:
  temperature: 0
  max_tokens: 1024
```

**Expected behavior**
- phi3 model X phi3 template prompt
- gemma model  X gemma template prompt

**System information (please complete the following information):**

- Promptfoo version: 0.73.7

**Additional context**
Discussed on Discord [here](https://discord.com/channels/1153767083381903389/1265076695765880916)

The label is correctly loaded and i do see this in the logs : 
```
2024-07-25 11:47:29 Loaded provider ollama:gemma:2b from ./providers/gemma.t_0.tokens_1024.yml
2024-07-25 11:47:29 Loaded provider ollama:gemma:2b from ./providers/gemma.t_0-50.tokens_1024.yml
```
