### ISSUE TITLE
Importing provider tools from a file does not work even after #1342

### ISSUE THREAD

**Issue by orange-anjou** [promptfoo/promptfoo#1350]
**Describe the bug**

The file is taken as a string instead of an object. (tried with json, yml and txt)

![image](https://github.com/user-attachments/assets/915fae12-8760-44b6-b524-3b82ffb7a36d)

**To Reproduce**

Here is the provider code : 
```yml
  - id: openai:chat:gpt-4o-mini
    config:
      label: gpt-4o-mini
      temperature: 0
      max_tokens: 1024
      tool_choice: 'auto'
      tools:
        - file://./tool-event-api.json
```

tool-event-api.json
```
{
  "type": "function",
  "function": {
    "name": "event_api",
    ...
  }
}
```

**Expected behavior**

The provider should receive the tool configuration.

**System information (please complete the following information):**

- Promptfoo version: 0.74.0

**Additional context**

Discussion on Discord where first discussed : https://discord.com/channels/1153767083381903389/1268551965357641728
When looking up the value from a python script, here is what i get : `'tools': ['file://./tool-event-api.txt']` Instead of the file content

**Comment by orange-anjou** [comment]
I've also tried some less conventional stuff like this :

```yaml
  - id: openai:chat:gpt-4o-mini
    config:
      label: gpt-4o-mini
      temperature: 0
      max_tokens: 1024
      tool_choice: 'auto'
      tools:
        - $ref: "#/defaultTest/vars/toolEventAPIFile"
```

```
defaultTest:
  vars:
    toolEventAPIFile: file://./tool-event-api.json
```

In this case, toolEventAPIFile is correctly loaded and can be used. However, `tools` contains ['file://./tool-event-api.json']...

**Comment by typpo** [comment]
Thanks for flagging - #1357 fixes the case where `tools` is set to a filepath.  Note that right now only a single filepath is supported, e.g.

```yaml
  - id: openai:chat:gpt-4o-mini
    config:
      tools: file://external_tools.yaml
```
