### ISSUE TITLE
promptfoo doesn't detect false or 0 outputs, I get '[FAIL] No output'

### ISSUE THREAD

**Issue by balintdom** [promptfoo/promptfoo#1351]
**Describe the bug**
I use an http provider, my endpoint returns a json like:
```json
{
    "blocked": true
}
```
When the value is `true` it works as expected, but when it is `false`, promptfoo doesn't detect the value, and I get `[FAIL] No output` message. The behaviour is similar if I use 0 and 1 values (promptfoo doesn't detect 0).

**To Reproduce**
1. Save this python code to `test_api.py`:
```python
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI()

class RequestModel(BaseModel):
    message: str

class ResponseModel(BaseModel):
    blocked: bool

@app.post("/status", response_model=ResponseModel)
def post_status(request: RequestModel):
    if request.message == 'this is true':
        return_value = True
    else:
        return_value = False
    
    return ResponseModel(blocked=return_value)

```
2. Run the API with uvicorn:
```bash
uvicorn test_api:app
```
3. Save this configuration to a `promptfooconfig.yml` file:
```yaml
description: "bug test"

prompts:
  - "{{question}}"

providers:
  - id: 'http://127.0.0.1:8000/status'
    config:
      method: 'POST'
      headers:
        'Content-Type': 'application/json'
      body:
        message: '{{prompt}}'
      responseParser: 'json.blocked'
      responseType:

defaultTest:
  assert:
    - type: equals
      value: "{{is_blocked}}"
tests:
  - vars:
      question: "this is true"
      is_blocked: true
  - vars:
      question: "this is not true"
      is_blocked: false

```
3. Run promptfoo with:
```bash
promptfoo eval
```
**Expected behavior**
Both test pass, as the API return `true` for the first call and `false` for the second call. 

**System information (please complete the following information):**

- Promptfoo version: 0.74.0
