### ISSUE TITLE
TestSuite Schema Validation Error when I use boolean values

### ISSUE THREAD

**Issue by balintdom** [promptfoo/promptfoo#1352]
**Describe the bug**
I get `TestSuite Schema Validation Error` whenever I set a boolean value as `tests\vars`

**To Reproduce**
Run promptfoo with the following configuration:
```yaml
# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide
description: "bug test"

prompts:
  - "{{question}}"

providers:
  - id: 'http://127.0.0.1:8000/status'
    config:
      method: 'POST'
      headers:
        'Content-Type': 'application/json'
      body:
        message: '{{prompt}}'
      responseParser: 'json.blocked'
      responseType:

defaultTest:
  assert:
    - type: equals
      value: "{{is_blocked}}"
tests:
  - vars:
      question: "this is true"
      is_blocked: true
  - vars:
      question: "this is not true"
      is_blocked: false
```

**Expected behavior**
It should be possible to set a value to boolean.

**Screenshots**
The error screen:
<img width="600" alt="image" src="https://github.com/user-attachments/assets/9819b3e5-cc4c-4d9e-8de1-50397aead944">
**System information (please complete the following information):**

- Promptfoo version: 0.74.0
