### ISSUE TITLE
Conv history documentation does not work

### ISSUE THREAD

**Issue by SeanyCochrane** [promptfoo/promptfoo#136]
New to the tool... I tried to follow the conversation history fixture in the opening documentation but the example just doesn't work. I have tried many tweaks but the prompt.json never does what it says in the example. 
My use case is i have a really big sys prompt which is followed by one assist prompt then I want to try multiple user prompts on the same large prompt... con history should do it but it does not work.. any ideas?

**Comment by typpo** [comment]
Hi @SeanyCochrane, thanks for flagging this.  You're right that there's a problem with the example in the docs - mainly that it used an inconsistent variable name.  

I've corrected this and also added a full example [here](https://github.com/promptfoo/promptfoo/tree/main/examples/openai-chat-history) that you can reference.  Let me know if you encounter any issues!

**Comment by SeanyCochrane** [comment]
Great thanks it's working now... one additional question. My default tests system prompt is large... how would I sub in a file to the yml... e.g. 
Messages:
    - system: [file with large prompt in it]

**Comment by typpo** [comment]
As of version 0.23.1 it is now possible to load a `vars` value directly from file using the `file://` prefix.  Here's an example:

```yaml
  - vars:
      system_message: file://path/to/system_message.yaml
      foo: some other var...
```

You may find it helpful to set the `system_message` var in `defaultTest`.  This will make the var available in every test.  Something like this:

```yaml
defaultTest:
  vars:
    system_message: file://path/to/system_message.yaml

tests:
  - vars:
      previous_messages:
        # ...
```

I've updated the example to show an example of this: https://github.com/promptfoo/promptfoo/blob/main/examples/openai-chat-history/promptfooconfig.yaml

Hope this helps!
