### ISSUE TITLE
Possible to combine scenarios with Google Sheets test cases?

### ISSUE THREAD

**Issue by kad3nce** [promptfoo/promptfoo#1376]
I'm trying to combine scenarios with google sheets for the test cases. Is this supported? If so, is there something wrong with my syntax? The below causes the following error:

```yaml
scenarios:
  - config:
      - vars:
          csvFilePath: industries.csv
      - vars:
          csvFilePath: industries-with-descriptions.csv
    tests: https://docs.google.com/spreadsheets/d/1OsJDtkyshJVzOp-iw_ZAEbM2ZflNHEqIbpo/edit?usp=sharing
```

```bash
npx promptfoo@latest eval
TestSuite Schema Validation Error:

  {"_errors":[],"scenarios":{"0":{"_errors":[],"tests":{"_errors":["Expected array, received string"]}},"_errors":[]}}

Please review your promptfooconfig.yaml configuration.
/Users/jedidiah/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:388
                    ]).map((test) => {
                       ^

TypeError: (scenario.tests || [{}]).map is not a function
    at Evaluator.evaluate (/Users/jedidiah/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:388:24)
    at evaluate (/Users/jedidiah/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/evaluator.js:806:15)
    at runEvaluation (/Users/jedidiah/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/commands/eval.js:114:56)
    at async doEval (/Users/jedidiah/.npm/_npx/81bbc6515d992ace/node_modules/promptfoo/dist/src/commands/eval.js:240:5)

Node.js v20.10.0
```

**Comment by typpo** [comment]
Thanks for flagging - This is unsupported right now

**Comment by kad3nce** [comment]
Got it. Thank you 🙏🏻

**Comment by mldangelo** [comment]
Hey! We looked into this but decided not to add support for it - scenarios are a bit of a legacy feature and we're moving away from them.

The good news is there's a straightforward workaround: just add `csvFilePath` as a column directly in your Google Sheet. So instead of two scenario configs, you'd duplicate your test rows - one set with `csvFilePath: industries.csv` and another with `csvFilePath: industries-with-descriptions.csv`.

Your config becomes:

```yaml
prompts:
  - "Your prompt here with {{csvFilePath}} and {{input}}"
providers:
  - openai:gpt-5.2
tests: https://docs.google.com/spreadsheets/d/1OsJDtkyshJVzOp-iw_ZAEbM2ZflNHEqIbpo/edit
```

It's a bit more repetitive in the spreadsheet, but honestly it ends up being easier to work with since each row is fully self-describing.

If you really want to keep the configs separate, you can also just make two config files and run `promptfoo eval -c config1.yaml -c config2.yaml`.

Closing this out, but let us know if the workaround doesn't cover your use case.
