### ISSUE TITLE
Groq tools

### ISSUE THREAD

**Issue by poborin** [promptfoo/promptfoo#1445]
Groq has recently announced tools support for Llama and Mixtral models similar to OpenAI tools. e.g. https://console.groq.com/docs/tool-use

Given that, Groq model configuration should have the same `tools` parameter as OpenAI configuration:
```yaml
providers:
  - id: openai:chat:gpt-4o-mini
    config:
      tools: [
        {
        "type": "function",
          "function": {
            "name": "get_current_weather",
            "description": "Get the current weather in a given location",
            "parameters": {
              "type": "object",
                "properties": {
                  "location": {
                    "type": "string",
                      "description": "The city and state, e.g. San Francisco, CA"
                    },
                    "unit": {
                      "type": "string",
                      "enum": ["celsius", "fahrenheit"]
                    }
                  },
              "required": ["location"]
            }
          }
        }
      ]
      tool_choice: 'auto'
```
