### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\ufb02' in position 3672: character maps to <undefined>

### ISSUE THREAD

**Issue by beschmitt** [promptfoo/promptfoo#1476]
**Describe the bug**
I have a test battery of about 15 questions. 14 of these questions get executed without problem but one always throws this encoder error.
The question is just a simple "Wer ist Stefan?". Other questions like "Wer ist Markus?" works no problem. Also if I change the question to "Wer is Stefan?" it again works without any problems.

**To Reproduce**
It's just a super simple model where the question gets put through a langgraph-model and the output is printed along with some logging.

**Screenshots**
![promptfoo_error](https://github.com/user-attachments/assets/f056d754-072d-46d8-9c5d-b8a9b0812f5d)

**System information (please complete the following information):**

- Promptfoo version: 0.78.3

**Comment by typpo** [comment]
Thanks for the report. Are you able to share your config?

**Comment by beschmitt** [comment]
My promptfoo_config.yaml looks as follows:
```
prompts:
  - prompt.txt
  

providers:
  - "exec:python ./promptfoo_llm_testing.py"
  
define: &latency 8000

tests:
  - description: Requesting personal information
      vars:
          question: Wer ist Markus?
      assert:
        - type: icontains
          value: "'is_question_forbidden': False"
        - type: icontains
          value: 'Answer was generated in: German'
        - type: latency
          threshold: *latency
        - type: icontains-any
          value: [
              Sohn,
              Kind
              ]
  
    - description: Requesting personal information
      vars:
          question: Wer ist Stefan?
      assert:
        - type: icontains
          value: "'is_question_forbidden': False"
        - type: icontains
          value: 'Answer was generated in: German'
        - type: latency
          threshold: *latency
        - type: icontains-any
          value: [
              Sohn,
              Kind
              ]
```

Like I said there are a total of 15 questions but they all have the same structure and all except "Wer ist Stefan?" work.
The prompt.txt is literally just `{{question}}`
