### ISSUE TITLE
Setting default `--grader` on command line fails

### ISSUE THREAD

**Issue by typpo** [promptfoo/promptfoo#1504]
**Describe the bug**
Setting `--grader` on command line causes test failure.

**To Reproduce**
1. promptfooconfig.yaml:
```
description: 'minimal repo'

prompts:
  - 'test prompt {{input}}'

providers:
  - "openai:chat:gpt-4o"

defaultTest:
  assert:
    - type: llm-rubric
      value: 'Check if response is good'

tests:
  vars:
    - input: my test
```
2. `promptfoo eval --grader openai:gpt-3.5-turbo`

**Expected behavior**
Runs test

**Actual**
```
│ [FAIL] TypeError: finalProvider.callApi is not a function                                                  │
│ TypeError: finalProvider.callApi is not a function                                                         │
│     at matchesLlmRubric (/home/ian/code/promptfoo/dist/src/matchers.js:251:38)                             │
│     at async runAssertion (/home/ian/code/promptfoo/dist/src/asse...                                       │
└──────────────────────────────────────────────────────────────────────────
```
