### ISSUE TITLE
Issue: Difficulty in Configuring provider Property for Test Assertions

### ISSUE THREAD

**Issue by MotzWanted** [promptfoo/promptfoo#151]
### Description:
According to the documentation, all test assertion types support the provider property. However, I'm facing challenges when configuring it to use the Azure OpenAI API for extracting embeddings.

### Configuration:

```
assert:
      - type: similar
        provider: azureopenai:completion:<deploymentName>
        value: "{{variable_in_tests}}"
```
### Error:
Received API response:
```
API response error: Error: No embedding returned: {"error":{"message":"Incorrect API key provided: adf8b367********************6d0e. You can find your API key at https://platform.openai.com/account/api-keys.","type":"invalid_request_error","param":null,"code":"invalid_api_key"}}
```
Any guidance on this would be appreciated.
