### ISSUE TITLE
Question : Can you run one suite of assertions then transform the llm response and apply a different set of outputs without calling the external LLM twice?

### ISSUE THREAD

**Issue by SysOverdrive** [promptfoo/promptfoo#1528]
So I have an LLM agent that returns a JSON format. Within the JSON there is an element that contains an SQL statement.

Example:
{
...
"sqlQuery":  "SELECT * ..."
...
}

I have build a promptfoo system that evaluates de SQL statements and also managed to extract with transform.py the SQL statement from it. Basically I am running a python script : generate_assertions.py and I get the assertions needed for sql in runtime_assertions

Now I am creating a seperate JSON validator for the JSON part of the answer.

My question is : How to have the 2 sets of evaluations run on the same output from the llm without running the system twice.

I was thinking of the following solution but then I feared that for the same set of questions (that are inside of the yaml assertions) I would get the same answer processed twice thus increasing the cost unnecessarily. 

Basically I have a set of 10 questions and with those 10 I create the **runtime_assertions_json.yaml** and **runtime_assertions_sql.yaml** is there a way to make sure the calls are unique and not double for each set of asserts ? 
```
providers:
  - id: "python:Interface.py"
    label: "Development JSON"
    config:
      model: "gpt-4o"
      tokens: 2000
      temperature: 0
defaultTest:
  options:
    transform: file://transform_json.py

tests: runtime_assertions_json.yaml

providers:
  - id: "python:Interface.py"
    label: "Development SQL"
    config:
      model: "gpt-4o"
      tokens: 2000
      temperature: 0
defaultTest:
  options:
    transform: file://transform_sql.py

tests: runtime_assertions_sql.yaml

```
