### ISSUE TITLE
Is there a way to import a environment variable that is not predefined in promptfoo ?

### ISSUE THREAD

**Issue by AmineDjeghri** [promptfoo/promptfoo#1552]
**Is your feature request related to a problem? Please describe.**
Currently, it seems that only certain predefined environment variables are supported, and there isn't a straightforward way to import custom environment variables that are specific to my workflow or setup.

**Describe the solution you'd like**
I would like the ability to import any environment variable, even if it's not predefined in `promptfoo`.

**Comment by typpo** [comment]
By "import an environment variable", do you mean referencing an environment
variable in a prompt template?

**Comment by AmineDjeghri** [comment]
Yes!

**Comment by mpasternak** [comment]
@AmineDjeghri I'd either use something to generate YAML configuration file... or check out this answer: https://stackoverflow.com/questions/52287881/how-do-access-node-env-in-nunjucks-template

**Comment by mldangelo** [comment]
Thanks to @AmineDjeghri and @mpasternak for raising and discussing this issue. @typpo has shipped a fix, and you can check it out by running `npx promptfoo@latest`. Here's a quick example:

You can access environment variables in your templates using the `env` global:

```yaml
tests:
  - vars:
      headline: 'Latest news in {{ env.COUNTRY }}'
```

Please let us know if you encounter any issues or have more ideas for improving the product.

**Comment by AmineDjeghri** [comment]
Hello again,
i am trying using it in the providers but it seems that it doesn't work. Promptfoo version is 0.90.3

```
providers:
  - id: azureopenai:chat:gpt-4o-mini # env variables are in .env
  - id: file://../configs/config_json.py
    label: '{{ env.AZURE_OPENAI_DEPLOYMENT_NAME }}'
```
