### ISSUE TITLE
Streaming is used when using Ollama as provider

### ISSUE THREAD

**Issue by elsatch** [promptfoo/promptfoo#1568]
**Describe the bug**
I am using Ollama to evaluate several models using promptfoo. When running the evals using the verbose flag, I get to see several individual tokens being sent from the Ollama server.

Checking the docs from Ollama, you can suppress streaming setting the stream parameter to false. (Related issue: https://github.com/ollama/ollama/pull/639).  I have used this configuration but the output is streamed (making no difference).

```yaml
providers:
  - id: ollama:chat:llama3.1:8b-instruct-q8_0
    label: llama31_8B_Q8
    config:
      temperature: 0
      stream: false
      system: "You are an expert in foobar test generation ..."
```

Setting stream to false makes no difference and all requests are processed as streaming. Note that this also applies when using Ollama for the grader LLM.

Sample output:

```
Ollama generate API response: {"model":"llama3.1:8b-instruct-q8_0","created_at":"2024-09-02T12:49:16.348475547Z","message":{"role":"assistant","content":"No"},"done":false}
{"model":"llama3.1:8b-instruct-q8_0","created_at":"2024-09-02T12:49:16.36468283Z","message":{"role":"assistant","content":" tengo"},"done":false}
{"model":"llama3.1:8b-instruct-q8_0","created_at":"2024-09-02T12:49:16.38080782Z","message":{"role":"assistant","content":" información"},"done":false}
{"model":"llama3.1:8b-instruct-q8_0","created_at":"2024-09-02T12:49:16.396949072Z","message":{"role":"assistant","content":" sobre"},"done":false}
{"model":"llama3.1:8b-instruct-q8_0","created_at":"2024-09-02T12:49:16.413265688Z","message":{"role":"assistant","content":" las"},"done":false}
```

**To Reproduce**
Use the previous config snippet in a yaml file as a provider and call the evaluation as `promptfoo eval --verbose` to visualize the output.

**Expected behavior**
Non interactive evaluations should not use stream as it might be less efficient.

**System information (please complete the following information):**

- Promptfoo version: 0.78.3
