### ISSUE TITLE
Custom nunjucks filters for the the paramters being passed in the custom api config body

### ISSUE THREAD

**Issue by mehnoorsiddiqui** [promptfoo/promptfoo#1658]
**Is your feature request related to a problem? Please describe.**

I want to pass a list of strings as a variable in the test case but promptfoo does not treat it as a list instead it iterates over it and run test case for each value in the provided list in vars.

**Describe the solution you'd like**

Treating the list as individual test input is now a default promptfoo behaviour, so I want to use the nunjucks filter. So that I can take the input as a string and when passing it inside the custom API config body I can covert it into a list of strings separated by commas 
```
nunjucksFilters:
  splitIntoList: ../utils/splitIntoList.js

providers:
  - id: 'https://localhost:44800/requiresCodeSample-test'
    config:
      method: 'POST'
      headers:
        'Content-Type': 'application/json'
      body:
        apiName: '{{apiName}}'
        messages: '{{messages | dump}}'
        endpointNames: '{{ endpointNames | splitIntoList }}'

scenarios:
  - config:
      - vars:
          apiName: Books API
          endpointNames: "books.search,books.get,books.create,books.update,books.delete"
    tests:
      - vars:
          messages:
            - role: 'user'
              content: "Which endpoints don't need a subscription?"             
            - role: 'assistant'
              content: 'You can use the search endpoint without a subscription.'             
            - role: 'user'
              content: 'How do I use it?'                                         
        assert:
        - type: starts-with
          value: 'Yes'   
```
**Describe alternatives you've considered**

```
providers:
  - id: 'https://localhost:44800/requiresCodeSample-test'
    config:
      method: 'POST'
      headers:
        'Content-Type': 'application/json'
      body:
        apiName: '{{apiName}}'
        messages: '{{messages | dump}}'
        endpointNames: '{{ endpointNames.names | dump }}'
      responseParser: 'json.requiresCodeSample'

scenarios:
  - config:
      - vars:
          apiName: Books API
          endpointNames:
            names: [ books.search,books.get,books.create,books.update,books.delete]
```
**Additional context**
