### ISSUE TITLE
Error when generating dataset

### ISSUE THREAD

**Issue by albertlieyingadrian** [promptfoo/promptfoo#1673]
I tried generating dataset but kept getting an error
```shell
 ███░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 6% | ETA: 16s | 1/16/Users/albertlieadrian/Documents/Random/a4
    throw new Error(value);
          ^

Error: Invariant failed: Expected exactly one JSON object in the response for persona Tourist looking fs
    at invariant (/Users/albertlieadrian/Documents/Random/ai-llm-playground/evals/node_modules/tiny-inv)
    at generateTestCasesForPersona (/Users/albertlieadrian/Documents/Random/ai-llm-playground/evals/nod)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async retryWithDeduplication (/Users/albertlieadrian/Documents/Random/ai-llm-playground/evals/no)
    at async synthesize (/Users/albertlieadrian/Documents/Random/ai-llm-playground/evals/node_modules/p)
    at async doGenerateDataset (/Users/albertlieadrian/Documents/Random/ai-llm-playground/evals/node_mo)
```

Here is the command
```shell
npx promptfoo generate dataset --config promptfoo-data.yaml  -o addresses.yaml
```

And here is the config file (following the example here https://www.promptfoo.dev/docs/configuration/datasets/#prepare-your-prompts)
```yaml
prompts:
  - 'Act as a travel guide for {{location}}'
  - 'I want you to act as a travel guide. I will write you my location and you will suggest a place to visit near my location. In some cases, I will also give you the type of places I will visit. You will also suggest me places of similar type that are close to my first location. My current location is {{location}}'

tests:
  - vars:
      location: 'San Francisco'
  - vars:
      location: 'Wyoming'
  - vars:
      location: 'Kyoto'
  - vars:
      location: 'Great Barrier Reef'
```

**Comment by mldangelo** [comment]
Hi @albertlieyingadrian, thanks so much for engaging with Promptfoo and trying out the dataset generation feature! The error you're encountering might be related to your provider configuration. Could you please share the providers section of your promptfooconfig.yaml? Dataset generation may not work well with smaller models, and you can refer to this section for more details: [testCases.ts#L329](https://github.com/promptfoo/promptfoo/blob/main/src/testCases.ts#L329).

If you're open to helping us debug and improve the feature, I'd gladly accept a PR. Feel free to share more of your config, and I'll try to reproduce the issue on my end to help resolve it. If the error is coming from the default OpenAI model, it might be a matter of forcing the response mode to JSON and adjusting the generation prompt. Thanks again!

**Comment by albertlieyingadrian** [comment]
@mldangelo My provider 
```yaml
providers:
  - label: 'gpt 3.5 low temperature'
    id: openai:gpt-3.5-turbo
    config:
      temperature: 0.1
```
