### ISSUE TITLE
Can rubricPrompt reference a prompt text from an external file?

### ISSUE THREAD

**Issue by albertlieyingadrian** [promptfoo/promptfoo#1680]
https://www.promptfoo.dev/docs/configuration/expected-outputs/model-graded/llm-rubric/#customizing-the-rubric-prompt

```yaml
defaultTest:
  options:
  rubricPrompt: >
    [
        {
            "role": "system",
            "content": "Evaluate the following output based on these criteria:\n1. Clarity of explanation\n2. Accuracy of information\n3. Relevance to the topic\n\nProvide a score out of 10 for each criterion and an overall assessment."
        },
        {
            "role": "user",
            "content": "Output to evaluate: {{output}}\n\nRubric: {{rubric}}"
        }
    ]
```

Trying to store the prompt in a separate prompt / json file. Wasn't able to find the reference from the docs.
