### ISSUE TITLE
Possible to pass env variables for external prompt's path?

### ISSUE THREAD

**Issue by albertlieyingadrian** [promptfoo/promptfoo#1685]
For example, I'd love to pass `env.ROOT_PATH = ${pwd}` here
```yaml
prompts:
  - file://{{ env.ROOT_PATH }}/something.txt

providers:
  - label: 'gpt 3.5 low temperature'
    id: openai:gpt-3.5-turbo
    config:
      temperature: 0.1
```
