### ISSUE TITLE
Adding config for custom assertion

### ISSUE THREAD

**Issue by albertlieyingadrian** [promptfoo/promptfoo#1701]
### Question
Is it possible to add "config" for custom assertion? eg.

```yaml
assert:
  - type: javascript
    value: file://relative/path/to/script.js
```

I would love to pass certain parameters to the respective script as 3rd argument after `context`

```javascript
module.exports = (output, context, customArgs?) => {
  return output.length > 10;
};
```

### Reference
- https://www.promptfoo.dev/docs/configuration/expected-outputs/javascript/#external-script

**Comment by albertlieyingadrian** [comment]
My workaround now
```yaml
assert:
  - type: javascript
    value: file://relative/path/to/script.js
    config:
      argA: valueA
```


```javascript
module.exports = (output, context) => {
  // Log the assert object
  const assertionMetricName = 'YOUR_METRIC_NAME'
  const assertion = context.test?.assert?.find(assertion => assertion.metric === assertionMetricName);

  const assertionConfig = assertion?.config

  // ... 
}

```
