### ISSUE TITLE
OpenAI provider error when referencing external file for `response_format`

### ISSUE THREAD

**Issue by albertlieyingadrian** [promptfoo/promptfoo#1710]
I got an error when referencing an external file following what is mentioned in the docs https://www.promptfoo.dev/docs/providers/openai/#external-file-references

```shell
API error: Invalid type for 'response_format': expected an object, but got a string instead., Type: invalid_request_error, Code: invalid_type

{
  "error": {
    "message": "Invalid type for 'response_format': expected an object, but got a string instead.",
    "type": "invalid_request_error",
    "param": "response_format",
    "code": "invalid_type"
  }
}
```

Files:
- sample.yaml
```yaml
prompts:
  - 'You are a helpful math tutor. Solve {{ problem }}'

providers:
  - id: openai:chat:gpt-4o-mini
    config:
      response_format: file://sample_schema.yaml
      # response_format: 
      #   type: json_schema
      #   json_schema:
      #     name: math_response
      #     schema:
      #       type: object
      #       properties:
      #         answer:
      #           type: string

tests:
  - vars:
      problem: 1+2
  - vars:
      problem: 4+8
```

- sample_schema.yaml
```yaml
type: json_schema
json_schema:
  name: math_response
  schema:
    type: object
    properties:
      answer:
        type: string
```
