### ISSUE TITLE
Unexpected token error when running openAI assistant provider

### ISSUE THREAD

**Issue by albertlieyingadrian** [promptfoo/promptfoo#1716]
I tried running exactly the same openAI assistant. It ran smoothly on version 0.87 but it failed on version 0.88 & 0.89

```yaml
  - label: "[Albert] Eval Example | Assistant + function call"
    id: "openai:assistant:asssxxxx"
    config:
      temperature: 0.2
      model: gpt-4o
      tools: file://provider/datamodel/__generated__/openai_tools/sample.yaml
```

Error logs on promptfoo's UI
```shell
SyntaxError: Unexpected token 'A', "[Assistant]"... is not valid JSON

SyntaxError: Unexpected token 'A', "[Assistant]"... is not valid JSON
    at JSON.parse (<anonymous>)
    at eval (eval at getInlineTransformFunction (/Users/albertlieadrian/Documents/Random/ai-llm-playground/evals/node_modules/promptfoo/dist/src/util/transform.js:75:12), <anonymous>:3:13)
    at transform (/Users/albertlieadrian/Documents/Random/ai-llm-playground/evals/node_modules/promptfoo/dist/src/util/transform.js:105:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Evaluator.runEval (/Users/albertlieadrian/Documents/Random/ai-llm-playground/evals/node_modules/promptfoo/dist/src/evaluator.js:238:48)
    at async processEvalStep (/Users/albertlieadrian/Documents/Random/ai-llm-playground/evals/node_modules/promptfoo/dist/src/evaluator.js:527:25)
```

<img width="917" alt="Screenshot 2024-09-19 at 3 23 55 AM" src="https://github.com/user-attachments/assets/bb3fe754-bfbb-43c4-a86c-5bed1bd9ead5">
