### ISSUE TITLE
prompt from external JS file not working

### ISSUE THREAD

**Issue by hakiemaul-flai** [promptfoo/promptfoo#1720]
**Describe the bug**
When using prompt from external file
```
prompts:
  - file://prompt.js

providers:
  - label: "fun"
    id: "openai:gpt-4o-mini"

tests:
  - vars:
      topic: bananas
```

with `prompt.js` written like
```
module.exports = async function ({ vars }) {
    return `Write a tweet about ${vars.topic}`;
};
```

The input prompt into openAI provider seems to be an actual code
```
[
  {
    role: 'user',
    content: 'async function ({ vars }) {\n' +
      '    return `Write a tweet about ${vars.prompt}`;\n' +
      '  }'
  }
]
```

**To Reproduce**
Install latest version of promptfoo, define a prompt as a JS file, and try running.

**Expected behavior**
JS file to run and resolved to be a string as returned

**Screenshots**

**System information (please complete the following information):**

- Promptfoo version:
0.89.0

**Additional context**
Previously working fine on version 0.87.1
might be similar issue as #1717 and #1716 as well
