### ISSUE TITLE
`outputPath` is not working

### ISSUE THREAD

**Issue by albertlieyingadrian** [promptfoo/promptfoo#1733]
Tried setting up outputPath in the config as both string and array of string following this guide https://www.promptfoo.dev/docs/configuration/parameters/#output-file. However, both didn't work 

```yaml
tests:
  - file://datasets/customer/mini_default_test.yaml

outputPath: 
  - reports/customer_output.html
# outputPath: 'reports/customer.html'
```

Suspect that it is caused by `outputPath` is not read in `readConfigs` function

https://github.com/promptfoo/promptfoo/blob/e6089ec7594282f9be6094a52e8483e044cd7e78/src/config.ts#L357-L390
