### ISSUE TITLE
Different prompts per provider doesn't work

### ISSUE THREAD

**Issue by albertlieyingadrian** [promptfoo/promptfoo#1738]
I tried to load different prompts for different providers following this instruction https://www.promptfoo.dev/docs/configuration/parameters/#different-prompts-per-model

```yaml
prompts:
  - id: file://prompts/gpt_chat_prompt.json
    label: gpt_chat_prompt
  - id: file://prompts/llama_completion_prompt.txt
    label: llama_completion_prompt

providers:
  - id: openai:gpt-4o-mini
    prompts:
      - gpt_chat_prompt
  - id: openai:gpt-4o
    prompts:
      - gpt_chat_prompt
  - id: replicate:meta/meta-llama-3.1-405b-instruct
    label: llama-3.1-405b-instruct
    prompts:
      - llama_completion_prompt
```

I got an error by `invariant`
```shell
/Users/albertlieadrian/Documents/Random/ai-llm-playground/evals/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:14
    throw new Error(value);
          ^

Error: Invariant failed: Invalid prompt
```

I traced it back and I figured it was caused by this checking https://github.com/promptfoo/promptfoo/blob/main/src/config.ts#L339-L342

The prompt's data structure, in this case, would have no `raw`, only `id` and `label`. Hence this configuration will never be able to be executed by promptfoo.

**Comment by albertlieyingadrian** [comment]
This is super hacky way to make it work -- by adding `raw` field in the config
```yaml
prompts:
  - id: file://prompts/gpt_chat_prompt.json
    label: gpt_chat_prompt
  - id: file://prompts/llama_completion_prompt.txt
    label: llama_completion_prompt

providers:
  - id: openai:gpt-4o-mini
    prompts:
      - gpt_chat_prompt
  - id: openai:gpt-4o
    prompts:
      - gpt_chat_prompt
  - id: replicate:meta/meta-llama-3.1-405b-instruct
    label: llama-3.1-405b-instruct
    prompts:
      - llama_completion_prompt
```

But seems like it's not intuitive for users and this might be a blocker for them to run even basic evals if they are gonna involve different prompts per provider @mldangelo @typpo
