### ISSUE TITLE
Add more deterministic/math-based assertions

### ISSUE THREAD

**Issue by sinedied** [promptfoo/promptfoo#1740]
**Is your feature request related to a problem? Please describe.**
Some of the common math-based evaluation metrics for NLP/LLM includes ROUGE (already supported), BLEU, METEOR, GLEU and some others.

See https://github.com/Aldenhovel/bleu-rouge-meteor-cider-spice-eval4imagecaption and https://huggingface.co/spaces/evaluate-metric/google_bleu for details and examples. 

**Describe the solution you'd like**
I'd like these common evaluation metrics to be available as assertions in promptfoo.

**Describe alternatives you've considered**
Use a custom assertion to implement them. I believe it would be beneficial to all promptfoo users to have such assertions built-in.

**Comment by adityabharadwaj198** [comment]
@mldangelo Hi, I was looking at tackling this issue. Here's how I'm planning to go about this: 

1. define meteor, glue in the enum here: https://github.com/promptfoo/promptfoo/blob/main/src/types/index.ts#L387
2. register a corresponding handler here: https://github.com/promptfoo/promptfoo/blob/main/src/assertions/index.ts#L231
3. define the handlers in their individual files similar to `rouge.ts` 

does this sound good? Let me know if you see any concerns

**Comment by mldangelo** [comment]
Awesome @adityabharadwaj198! 

I just opened a PR with guidance on adding a new assertion: https://github.com/promptfoo/promptfoo/pull/3610 Please feel free to leave comments on the PR if you think parts of it can be improved. 

You can reference https://github.com/promptfoo/promptfoo/pull/3605, https://github.com/promptfoo/promptfoo/pull/2469, and https://github.com/promptfoo/promptfoo/pull/2081 as recent assertion PRs. 

Good luck! And send me an email when you're done to michael @ promptfoo.dev and I'll send you some swag.

**Comment by adityabharadwaj198** [comment]
@mldangelo I opened a PR for adding meteor score: https://github.com/promptfoo/promptfoo/pull/3776. Would love to hear your thoughts on it!

**Comment by mldangelo** [comment]
Hey @sinedied, circling back on this one. Thanks for the suggestion back in September 2024!

We've since added all the metrics you mentioned:

- **BLEU** (`bleu`) #2081
- **GLEU** (`gleu`) #3674
- **METEOR** (`meteor`) #3776
- **ROUGE** (`rouge-n`) already existed at the time

These join our other deterministic assertions like `levenshtein`, `similar` (cosine/dot/euclidean), and `perplexity`.

Example usage:

```yaml
tests:
  - vars:
      input: "The quick brown fox jumps over the lazy dog"
    assert:
      - type: bleu
        value: "A fast brown fox leaps over a sleepy dog"
        threshold: 0.3
      - type: meteor
        value: "The quick brown fox jumps over the lazy dog"
        threshold: 0.8
```

If you ever need something more specialized (domain-specific metrics), the `python` and `javascript` assertion types let you plug in arbitrary scoring logic:

```yaml
assert:
  - type: python
    value: file://my_custom_metric.py
```

Closing this one out since the original request is covered. If there's a specific metric you'd still like to see built-in, open a new issue and we can discuss, always interested in what evaluation approaches people are using in practice.
