### ISSUE TITLE
Trying to OR between multiple asserts

### ISSUE THREAD

**Issue by mrafnadeem-apimatic** [promptfoo/promptfoo#1741]
**Is your feature request related to a problem? Please describe.**
I have an assertion where I want to check whether the response contains either one set of strings or another set of strings. So, it's basically like an OR between two `icontains-all` assertions. There is an existing way to do this with promptfoo but it's an awkward workaround and easy to make mistakes with.

**Describe the solution you'd like**
```yaml
    assert:
      - type: assert-any
        assert:
          - type: contains
            value: "string A"
          - type: contains
            value: "string B"
```
or something similar.

**Describe alternatives you've considered**
Currently, the docs say:
>Example - if one of two assertions need to pass or 50%:
>```yaml
>tests:
>  - description: 'Test that the output is cheap or fast'
>    vars:
>      example: 'Hello, World!'
>    assert:
>      - type: assert-set
>        threshold: 0.5
>        assert:
>          - type: cost
>            threshold: 0.001
>          - type: latency
>            threshold: 200
>```

So, I would have to do this:
```yaml
    assert:
      - type: assert-set
        threshold: 0.5
        assert:
          - type: contains
            value: "string A"
          - type: contains
            value: "string B"
```

and if I add another assertion, I have to update the threshold by calculating 1/(number of assertions):
```yaml
    assert:
      - type: assert-set
        threshold: 0.333 # rounded to 3 decimal places :)
        assert:
          - type: contains
            value: "string A"
          - type: contains
            value: "string B"
          - type: contains
            value: "string C"
```

It's also not obvious what I'm doing here just by reading the assertion so it's not readable.

**Additional context**
Promptfoo v0.85.0

**Comment by mldangelo** [comment]
Hi @mrafnadeem-apimatic, thanks for the suggestion! As a workaround and for your use case, I recommend using a custom JavaScript or Python assertion. For example: 

```yaml
assert:
  - type: javascript
    value: |
      // Check if the output contains either "string A" or "string B"
      const containsA = output.includes("string A");
      const containsB = output.includes("string B");
      return containsA || containsB;
```

You can also save them in a separate file and reference it using the `file://` prefix:

```yaml
assert:
  - type: python
    value: file://path/to/your_assertion.py
```

Check out https://www.promptfoo.dev/docs/configuration/expected-outputs/javascript/ and https://www.promptfoo.dev/docs/configuration/expected-outputs/python/
