### ISSUE TITLE
HTTP provider URL as template

### ISSUE THREAD

**Issue by AlexRRR** [promptfoo/promptfoo#1742]
**Is your feature request related to a problem? Please describe.**
I wanted to use the HTTP provider for setting tests against an HTTP endpoint but ran into a limitation, currently the URL is configured as the `id` of the provider, eg: 
```yaml
providers:
  - id: 'https://example.com/generate'
    config:
      method: 'POST'
      headers:
        'Content-Type': 'application/json'
      body:
        myPrompt: '{{prompt}}'
      responseParser: 'json.output'
```
but the `id` is not a template so it cannot be replaced during runtime. The usecase would be that during a CI pipeline execution the endpoint can be changed to a specific environment (qa|dev|etc).

I noticed that https://github.com/promptfoo/promptfoo/issues/1552 allows to use envvars in templated properties, but this does not work for the HTTP provider.

**Describe the solution you'd like**
Something like 
```
providers:
  - id: 'api-endpoint'
    url: 'https://{{ env.MYHOST }}:{{ env.MYPORT }}/query'
    config:
      method: 'POST'
      headers:
        'Content-Type': 'application/json'
      body:
        myPrompt: '{{prompt}}'
      responseParser: 'json.output'
```
or simply be able to do
```
providers:
  - id: 'https://{{ env.MYHOST }}:{{ env.MYPORT }}/query'
```    

**Describe alternatives you've considered**
- writing own Custom JS or Python, but seems such a simple change that should be part of the HTTP Provider
- Generating the YAML for the test before execution, via `sed` or similar

**Comment by mldangelo** [comment]
Hi @AlexRRR, thanks for raising this issue! We’ve just merged a PR that adds templating support for provider URLs (#1747). This feature will allow you to use templated values in the `id` field, similar to your examples:

```yaml
providers:
  - id: 'https://{{ env.MYHOST }}:{{ env.MYPORT }}/query'
    config:
      method: 'POST'
      headers:
        'Content-Type': 'application/json'
      body:
        myPrompt: '{{prompt}}'
      responseParser: 'json.output'
```

This update will be included in the next release (tomorrow). Please let us know if you have any other feedback or run into issues!
