### ISSUE TITLE
`o1-preview` not working as expected: no output

### ISSUE THREAD

**Issue by diego-delarue-ai** [promptfoo/promptfoo#1746]
**Describe the bug**
I tried setting up my evaluations as [instructed here](https://www.promptfoo.dev/docs/guides/gpt-vs-o1/) and have been  getting no output from `o1-preview`. My `config.yaml` looks like:

```
description: "Testing o1-preview"
prompts:
  - file://src/prompts.py:regular_prompt
  - file://src/prompts.py:augmented_prompt
providers:
  - id: openai:chat:gpt-4o-2024-08-06
    label: base
  - id: openai:o1-preview
    label: o1-preview
```
*I tried running this by using `openai:chat:o1-preview` and this ran but gave me the same output. I tested this using `o1-mini` and obtained the same results.

**To Reproduce**
With this set up, I get reasonable outputs from `base` but get empty outputs for `o1-preview`. Instaed of an output, I only get te assertion output strings such as `[BAD_FORMATTING] Error  JSON.`

**Expected behavior**
I expected the `o1-preview` model to output reasonable responses where nothing was output.

**Screenshots**
![image](https://github.com/user-attachments/assets/e3e5b3cf-87cf-405c-a7d0-3719693db620)
**System information (please complete the following information):**

- Promptfoo version:
0.89.4
