### ISSUE TITLE
HTTP Provider: responseParse not working

### ISSUE THREAD

**Issue by AlexRRR** [promptfoo/promptfoo#1770]
**Describe the bug**
JSON response is not parsed anymore

**To Reproduce**
Steps to reproduce the behavior, including example Promptfoo configurations if applicable:
Configuration
```
description: HTTP ENDPOINT TEST

prompts: 
  - '{{ query }}'

providers:
  # using public mock API
  - id: 'https://jsonplaceholder.typicode.com/posts'
    config:
      method: 'POST'
      headers:
        'Content-Type': 'application/json'  
      responseParser: 'json.m'    
      body:
        m: moo  

tests:
  - vars:
      query: 'dummy'     
```
response from API directly: 
```json 
{
  "m": "moo",
  "id": 101
}
```

Output when running the config `promptfoo eval -c http-mock.yaml  --no-cache`
``` 
Cache is disabled.
[████████████████████████████████████████] 100% | ETA: 0s | 1/1 | https://jsonplaceholder.typicode.com/posts "{{ query }" query=dumm

┌─────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────┐
│ query                                                                   │ [https://jsonplaceholder.typicode.com/posts] {{ query }}                │
├─────────────────────────────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ dummy                                                                   │ [FAIL] No output                                                        │
│                                                                         │ ---                                                                     │
│                                                                         │ No output                                                               │
└─────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────┘
```

changing the parser to just `responseParser: 'json'` (no property extraction)

```
[████████████████████████████████████████] 100% | ETA: 0s | 1/1 | https://jsonplaceholder.typicode.com/posts "{{ query }" query=dumm

┌─────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────┐
│ query                                                                   │ [https://jsonplaceholder.typicode.com/posts] {{ query }}                │
├─────────────────────────────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ dummy                                                                   │ [PASS] {                                                                │
│                                                                         │   "m": "moo",                                                           │
│                                                                         │   "id": 101                                                             │
│                                                                         │ }                                                                       │
└─────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────┘
```

**Expected behavior**
nested properties are extracted

**System information (please complete the following information):**

- Promptfoo version: 0.90.1
