### ISSUE TITLE
Is there an option to add a custom provider configuration with variables from a vars file?

### ISSUE THREAD

**Issue by Starday2009** [promptfoo/promptfoo#1773]
It is necessary to pass a variable from the var file to custom provider, the reference to which is in the test, to the provider file
Like that: 

```
providers:
  - id: python:providers/get_existing_aws_file.py
    config:
      s3FileName: context['vars']['AWS_SUMMARY_S3_KEY']
      aws_bucket_name: context['vars']['AWS_BUCKET_NAME']

```
`s3FileName` and `aws_bucket_name` located in the `vars` folder, and specific for each test. 

I made a variable call like I do in the test file, but it didn't work. Any ideas how to do it right and is it even possible?
