### ISSUE TITLE
feat: transformations / path

### ISSUE THREAD

**Issue by MentalGear** [promptfoo/promptfoo#18]
As mentioned earlier `contains-json` is a neat output test. It'd be also great to be able to transform the input, like already somewhat possible with `prefix` and `suffix`.

I propose expanding on this and introducing:
- a `"transforms"` property for both global and specific `vars`, which would allow transforming the input using arbitrary js.
- a path() keyword which points towards a file

### Use-Case:
As a dev, I have a JSON example for my prompt that I keep in separate .json file for maintainability (readability / formatting, ...), but I'd like the generated prompt to contain the stringified version to omit unnecessary tokens and set the expected outcome.

It'd be super convenient to being able to simply do:

```yaml
  - vars:
      outputExample: path("example.json")
      transforms: path("stringify_function.js")
```

`stringify_function.js`
```ts
function( input:string ) {
    const parsedJSON = JSON.parse( input )
    return JSON.stringify(parsedJSON)
}
```

**Comment by MentalGear** [comment]
Just to clarify: this would also be useful for variables that are used within the prompt itself. So, basically being able to have some `global vars`.
```yaml
prompts:
   vars:
     prompt_example1: ...
```

So we don't need to define them for each `- vars` item.

**Comment by MentalGear** [comment]
This would also be useful for `global variables` that can be used within the prompt itself. 
```yaml
prompts:
   vars:
     - prompt_example_var: ...
```

So we don't need to define them for each `- vars` item.

For clarity, a full example:

---

```md
Think about the text below and output an object with these properties:
{
positive: number,
negative: number,
neutral: number,
tags: string[]
}

Example:

--
Input:
{{ input_example_review_1 }}

Output:
{{ output_example_json_1 }}

--

Input:
{{ user_query_input }}

Output:
```

Here, I want to only test `user_query_input`, but use vars for the example to:
- keep the main prompt clean
- add transforms to the output_example_json_1 (stringify)

Also, this setup allows to occasionally add more or less examples if there are different prompts.
