### ISSUE TITLE
output context truncated in python assertions

### ISSUE THREAD

**Issue by rlaabs** [promptfoo/promptfoo#1812]
**Describe the bug**
It looks like all output may be truncated, even when running something like 'promptfoo eval -o output.txt'

**To Reproduce**
config:
```
description: "My eval"
prompts:
  - "Create a numbered list of 200 birds that are native to North America."
providers:
  - "openai:gpt-4o-mini"
tests:
  - assert:
    - type: python
      value: file://assert.py
      config: 
        foo: 10
```

assert.py
```
from typing import Union, Dict, Any

def get_assert(output: str, context) -> Union[bool, float, Dict[str, Any]]:
    with open('/Users/robertlaabs/Desktop/output_len_test.txt', 'wt') as f:
        f.write(str(len(output)))
    with open('/Users/robertlaabs/Desktop/output_test.txt', 'wt') as f:
        f.write(output)
    return True

```

**System information (please complete the following information):**

- Promptfoo version: 0.91.1
