### ISSUE TITLE
Cannot set custom provider for LLM grader override

### ISSUE THREAD

**Issue by AnkitTheCoder** [promptfoo/promptfoo#182]
As per the docs https://www.promptfoo.dev/docs/configuration/expected-outputs#overriding-the-llm-grader
We should be able to use custom providers for the LLM grading.
However, when setting custom provider via any of the methods (defaultTest.options and assertion.provider), the following error is thrown

`Error: Invariant failed: Provider supplied to llm-rubric must have an id
at invariant (/usr/local/share/npm-global/lib/node_modules/promptfoo/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:14:11)
at getGradingProvider (/usr/local/share/npm-global/lib/node_modules/promptfoo/dist/src/matchers.js:50:38)
at matchesLlmRubric (/usr/local/share/npm-global/lib/node_modules/promptfoo/dist/src/matchers.js:118:31)
at runAssertion (/usr/local/share/npm-global/lib/node_modules/promptfoo/dist/src/assertions.js:383:55)
at runAssertions (/usr/local/share/npm-global/lib/node_modules/promptfoo/dist/src/assertions.js:49:30)
at Evaluator.runEval (/usr/local/share/npm-global/lib/node_modules/promptfoo/dist/src/evaluator.js:182:74)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async /usr/local/share/npm-global/lib/node_modules/promptfoo/dist/src/evaluator.js:418:25`

Providing the id, as suggested by the error does not matter.
The same custom provider works fine when set as the configuration file's "providers" property. 

Below is the promptfooconfig.yaml file that reproduces the issue for me.

```yaml
prompts: [prompt.yaml]
providers: [../../providers/custom.js]
defaultTest:
  assert:
    - type: llm-rubric
  options:
    provider: [../../providers/custom.js]
    rubricPrompt:
      - role: system
        content: >-
          Grade the output by the following specifications, keeping track of the points scored:

          Did the output include code? +1 point
          Was the output in markdown format? +1 point
          Is the output relevant to the {{ query }}? +1 point

          Calculate the score and pass the test if total points is greater than 2.5.
          Output must be in the following JSON format:
          {pass: true, score: number, reason: string}
      - role: user
        content: 'Output: {{ output }}'
tests: tests/user-prompts.csv
```
