### ISSUE TITLE
Output provider labels do not match up with the config

### ISSUE THREAD

**Issue by brendanator** [promptfoo/promptfoo#1832]
**Describe the bug**

In these images you can see that the label does not match the config

![image](https://github.com/user-attachments/assets/d5c8203c-7805-4d58-8c02-6d913be470bc)

![image](https://github.com/user-attachments/assets/e8a837e3-5f2f-47e3-8aeb-a3971b055f88)

**To Reproduce**
Steps to reproduce the behavior, including example Promptfoo configurations if applicable:

Here's my provider config:
```yaml
providers:
  - id: file://provider_structured_response.py
    label: claude-3-5-sonnet
    config:
      provider: anthropic
      model: claude-3-5-sonnet-20240620
      model_args:
        temperature: 0.0
  - id: file://provider_structured_response.py
    label: openai_gpt-4o
    config:
      provider: openai
      model: gpt-4o
      model_args:
        temperature: 0.0
```

Run it a few times. About half of the time it is correct and half the time wrong

**System information (please complete the following information):**

- Promptfoo version: 0.92.0

**Additional context**
Before I added the labels, both of the results were merged into a single output column
