### ISSUE TITLE
Provider for instructor? 

### ISSUE THREAD

**Issue by albertlieyingadrian** [promptfoo/promptfoo#1838]
https://js.useinstructor.com/

**Comment by mldangelo** [comment]
You can use Instructor with promptfoo via a custom JavaScript provider. Here's a minimal example:

**1. Install dependencies:**
```bash
npm install @instructor-ai/instructor openai zod
```

**2. Create `instructor_provider.js`:**
```javascript
const Instructor = require("@instructor-ai/instructor").default;
const OpenAI = require("openai").default;
const { z } = require("zod");

const schemas = {
  UserInfo: z.object({
    name: z.string().describe("The user's full name"),
    age: z.number().describe("The user's age"),
    occupation: z.string().optional(),
  }),
};

class InstructorProvider {
  constructor(options) {
    this.providerId = options.id || "instructor-provider";
    this.config = options.config || {};
    this.schemaName = this.config.schema || "UserInfo";

    const oai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
    this.client = Instructor({ client: oai, mode: "TOOLS" });
  }

  id() { return this.providerId; }

  async callApi(prompt) {
    const schema = schemas[this.schemaName];
    const result = await this.client.chat.completions.create({
      model: this.config.model || "gpt-4o-mini",
      messages: [{ role: "user", content: prompt }],
      response_model: { schema, name: this.schemaName },
    });
    return { output: JSON.stringify(result, null, 2) };
  }
}

module.exports = InstructorProvider;
```

**3. Create `promptfooconfig.yaml`:**
```yaml
providers:
  - id: file://instructor_provider.js
    config:
      model: gpt-4o-mini
      schema: UserInfo

prompts:
  - "{{input}}"

tests:
  - vars:
      input: "Sarah Johnson is a 28-year-old data scientist."
    assert:
      - type: is-json
      - type: javascript
        value: |
          const data = JSON.parse(output);
          return data.name === "Sarah Johnson" && data.age === 28;
```

**4. Run:**
```bash
npx promptfoo eval
```

Since Instructor works well as a custom provider and doesn't require a dedicated built-in provider, I'm closing this issue. Please feel free to comment or re-open if you have any follow ups!
