### ISSUE TITLE
How to use `vars` within 

### ISSUE THREAD

**Issue by jamesbraza** [promptfoo/promptfoo#184]
Here is a subset of my `promptfooconfig`:

```yaml
    - vars:
          value: foo
          result: bar
      assert:
          - type: similar
            value: The answer is {{ result }}.
```

Is it possible to use `vars` in an assertion's `value`?

The details pages suggests the substitution didn't take place

![screenshot of details pane](https://github.com/promptfoo/promptfoo/assets/8990777/4f038c3b-cafe-40e7-ba90-b061da2028a7)

**Comment by jamesbraza** [comment]
Realizing this may be enabled by https://github.com/promptfoo/promptfoo/issues/150

**Comment by jamesbraza** [comment]
Okay @typpo just to follow up on this, use of `vars` is now possible in assertions via code files, and thank you for that 👍.

Is it possible to use `vars` in an assertion in a vanilla `promptfooconfig.yaml` (no external `.py`/`.js` code file, and not using `scenarios`)?

```yaml
    - vars:
          value: foo
          result: bar
      assert:
          - type: similar
            value: The answer is {{ result }}.
```
