### ISSUE TITLE
Filter Targets

### ISSUE THREAD

**Issue by ktalebian** [promptfoo/promptfoo#1861]
**Is your feature request related to a problem? Please describe.**

We want to run a series of test on dev/stage/prod environment. Right now we have `promptfoo.dev.yaml` etc and each has a `target` to the same provider but with different config (different username/password/url).

Alternatively, we should be able to have a single `promtpfoo.config.yaml` and have

```
targets:
  - id: aProvider
     label: dev
     config:
       username: user1
       password: pass1 
  - id: aProvider
     label: stage
     config:
       username: user2
       password: pass2
```

Then do `promptfoo eval --filter-target dev` 

If that makes sense, I can make a PR to add support for this. Thoughts/suggestions/alternatives?

**Comment by typpo** [comment]
We actually support this through the `--filter-providers` flag on `eval`.  It takes a regex which matches on `id` and `label`.  Here's the implementation: https://github.com/promptfoo/promptfoo/blob/main/src/commands/eval/filterProviders.ts#L3

`targets` is just an alias for `providers`, which I know is confusing.  #1863 adds support for `--filter-targets`.  Hope this helps

**Comment by ktalebian** [comment]
@typpo I tried that, but that filters by the `id`. I would like to filter by `label` since it's the same provider with different configuration

**Comment by typpo** [comment]
hmm, it _should_ match the label as well: https://github.com/promptfoo/promptfoo/blob/main/src/commands/eval/filterProviders.ts#L17

**Comment by ktalebian** [comment]
@typpo okay thanks ya that works. However, there is a potential bug. Here is our custom provider:

```
targets:
  - id: file://customProvider.js
    label: Dev
    config:
      env: 'dev'
      username: abc1
      passwordKey: PASS_KEY1

  - id: file://customProvider.js
    label: Stage
    config:
      env: 'stage'
      username: abc2
      passwordKey: PASS_KEY2
```

Inside the `customProvider` I am doing a check if `if (!process.env[options.config.passwordKey]) { /* error out */ })` 

What is happening now is even if I run `promptfoo eval --filter-providers Dev`, `promptfoo` is first loading the providers (by instantiating them) before filtering them. So I unless I provide both environment variables, I get an error and the app crashes. 

I am guessing we need to update `--filter-providers` to read a static `.name/.label` from the functions so it can do a filter pre-instantiation. 

Thughts? I can make a PR here
