### ISSUE TITLE
assertion values should support array of files

### ISSUE THREAD

**Issue by danpe** [promptfoo/promptfoo#1896]
Instead of doing the following:
```
- description: 'Testing Full Summary prompt quality'
    vars:
      input: file://evaluation/inputs/full-1.txt
    assert:
      - type: contains-json
      - type: similar
        value: file://evaluation/outputs/full-1.txt
        threshold: 0.8

  - description: 'Testing Full Summary prompt quality'
    vars:
      input: file://evaluation/inputs/full-2.txt
    assert:
      - type: contains-json
      - type: similar
        value: file://evaluation/outputs/full-2.txt
        threshold: 0.8

  - description: 'Testing Full Summary prompt quality'
    vars:
      input: file://evaluation/inputs/full-3.txt
    assert:
      - type: contains-json
      - type: similar
        value: file://evaluation/outputs/full-3.txt
        threshold: 0.8

  - description: 'Testing Full Summary prompt quality'
    vars:
      input: file://evaluation/inputs/full-4.txt
    assert:
      - type: contains-json
      - type: similar
        value: file://evaluation/outputs/full-4.txt
        threshold: 0.8
```

**Describe the solution you'd like**
I would love to be able to do:
```
- description: 'Testing Full Summary prompt quality'
    vars:
      input:  
        - file://evaluation/inputs/full-1.txt
        - file://evaluation/inputs/full-2.txt
        - file://evaluation/inputs/full-3.txt
        - file://evaluation/inputs/full-4.txt
        
    assert:
      - type: contains-json
      - type: similar
        value: 
          - file://evaluation/outputs/full-1.txt
          - file://evaluation/outputs/full-2.txt
          - file://evaluation/outputs/full-3.txt
          - file://evaluation/outputs/full-4.txt
        threshold: 0.8
```
