### ISSUE TITLE
Support authenticated HTTP providers

### ISSUE THREAD

**Issue by bennibbelink** [promptfoo/promptfoo#2005]
**Is your feature request related to a problem? Please describe.**
I am using the promptfoo web interface. I want to query an HTTP provider at an API that I host, which requires authentication.  My evaluation results come back with every query response as "401 unauthorized", since the Promptfoo server making the api call is not sending a valid bearer token. 

**Describe the solution you'd like**
I'd like to be able to register my promptfoo deployment as a client in keycloak, so that when I deploy my promptfoo instance I can provide it with its keycloak client credentials.  Then I would like the promptfoo server to go through a proper auth flow to retrieve an authorization token from keycloak which it can then pass to my HTTP provider when it makes a query during evaluation.

**Describe alternatives you've considered**
For the time being I will probably work off of a fork and implement custom logic in the express server to pass my Bearer token along, but that is not generalizable.

**Comment by typpo** [comment]
Hi Benni, would it work to set the appropriate header in your HTTP provider?  https://www.promptfoo.dev/docs/providers/http/

For example
```yaml
providers:
  - id: 'https://example.com/generateWithAuth'
    config:
      method: 'POST'
      headers:
        'Content-Type': 'application/json'
        'Authorization': 'Basic {{encodedAuth}}'
      body:
        prompt: '{{prompt}}...'
```
