### ISSUE TITLE
problem with running multiple tests

### ISSUE THREAD

**Issue by tttbone8122** [promptfoo/promptfoo#203]
I was running two tests roughly in the following manner (I will illustrate using a notebook example):

```
%%writefile prompts/prompt1.txt
{{document}}
Question: {{question}}
```

```
%%writefile promptfooconfig1yaml
prompts:
  - prompts/prompt1.txt
providers: 
  - id: openai:gpt-3.5-turbo
    config:
      temperature: 0
tests: 
  - tests/test1.yaml
outputPath: output/output1.csv
```

And the second one similarly:

```
%%writefile prompts/prompt2.txt
Question: {{question}}
Document: {{document}}
```

```
%%writefile promptfooconfig2.yaml
prompts:
  - prompts/prompt2.txt
providers: 
  - id: openai:gpt-3.5-turbo
    config:
      temperature: 0
tests: 
  - tests/test2.yaml
outputPath: output/output2.csv
```

These were two completely different tests with different logic. However, I would like to implement this solution in a way that they run cyclically. To achieve this, I would like to somehow combine them so that they work and can be executed with a single command, like npx promptfoo view.
