### ISSUE TITLE
Cannot set `response_format` with external file for Azure OpenAI provider

### ISSUE THREAD

**Issue by joakimriedel** [promptfoo/promptfoo#2091]
**Describe the bug**

For Azure OpenAI provider, when setting the `response_format` config setting linking to an external file like so;

```
providers:
  - id: azureopenai:chat:xxx-gpt4o
    label: gpt-4o
    config:
      apiHost: "xxx.openai.azure.com"
      apiVersion: 2024-08-01-preview
      response_format: file://schema.json
```

I get the following error;

```
[FAIL] API response error: null 400: There was an error parsing the body 
```

It does not even matter what path I set, it could be to an non-existant file and still reproduce the same error message.

But adding the response format manually such as;

```
      response_format:
        type: json_schema
        json_schema:
          name: reasoning_schema
          strict: true
          schema:
            type: object
            properties:
              reasoning_steps:
                type: array
                items:
                  type: string
                description: The reasoning steps leading to the final conclusion.
              answer:
                type: string
                description: The final answer, taking into account the reasoning steps.
            required:
              - reasoning_steps
              - answer
            additionalProperties: false
```

works like a charm, as long as I remember to set the latest API version (`apiVersion: 2024-08-01-preview`) in the `gpt-4o` provider.

I would expect it to be possible to use external JSON or YAML schema instead of inline, as indicated by [this issue](https://github.com/promptfoo/promptfoo/issues/1710).

- Promptfoo version: 0.95
