### ISSUE TITLE
Broken Anthropic System Message

### ISSUE THREAD

**Issue by kaulsh** [promptfoo/promptfoo#2123]
**Describe the bug**

I use JS functions to return prompts. Here's how a test file looks:

```
description: "Audit"

providers:
  - id: "anthropic:messages:claude-3-5-haiku-20241022"
    config:
      temperature: 0
      max_tokens: 4096

prompts:
  - ../build/prompts/index.js:audit_criteria

tests: GOOGLE_SHEETS_URL
```

In the latest version (v0.96.0) I get this error on prompts that use the system message:
```
API call error: messages: Unexpected role "system". The Messages API accepts a top-level `system` parameter, not "system" as an input message role., status 400, type invalid_request_error
```

After reviewing some code, I think this change in `src/providers/anthropic.ts` broke it:
https://github.com/promptfoo/promptfoo/commit/3c29b39ff26c6a9e77c1a0da344960a81fc8b59c#diff-afce651d866a1cd4afb1936e9e431f2aab127727a60530b1774dac7348961c65

~~It also seems as though anthropic's prefill messages aren't working anymore. I could not find any related code to such.~~ This could just be a model issue. Prefill works with other models. Can ignore.
