### ISSUE TITLE
Erroneous warning that `$ref` is invalid in the providers section of promptfooconfig

### ISSUE THREAD

**Issue by sobjornstad** [promptfoo/promptfoo#2125]
**Describe the bug**
In 0.95 and earlier, `$ref` worked great to retrieve the model(s) you wanted to use, e.g.:

```yaml
providers:
  - anthropic:messages:claude-3-5-sonnet-20240620
  - $ref: promptfoo/defaultParams.yaml#/model
  - openai:gpt-4o-mini
```

Now in 0.96, I get a yellow warning when I run an eval:

```
Invalid configuration file promptfoo/magic_copy_paste_text_to_cards_advanced/all_card_types/promptfooconfig.yaml:
Validation error: Unrecognized key(s) in object: '$ref' at "providers[1]"
```

Despite this “validation error,” the eval still runs as expected, with the correct value retrieved from the ref.

**To Reproduce**

Create a promptfooconfig.yaml, e.g.:

```yaml
description: concept_panel_define
prompts:
  - test {{text}}
providers:
  - $ref: promptfoo/defaultParams.yaml#/model
temperature: 1

tests:
  - vars:
      text: bla bla bla
```

Create the `defaultParams.yaml` file referenced, with some value for `model` that's a valid model, e.g.:

```yaml
model: openai:gpt-4o-mini
```

Run `promptfoo eval` on the config.

**Expected behavior**
No warning appears, since the syntax is valid and the eval runs normally.

**Screenshots**

**System information (please complete the following information):**

- Promptfoo version: 0.96
