### ISSUE TITLE
Pass assert result down to next assert

### ISSUE THREAD

**Issue by BenjaminBruenau** [promptfoo/promptfoo#2132]
First of all I just want to say, that I have used promptfoo for two projects so far and really enjoy using it, especially all the possibilities for customization.

I was just wondering if it is possible to pass down the result of a previous assert or have some sort of conditional asserts, as I could not find anything regarding this in the documentation or existing issues.

My use case is that i have asserts defined like this:

```yaml
assert:
      - type: is-sql
        value: ...
      - type: python
        value: file://metrics/execution_accuracy.py
      - type: python
        value: file://metrics/...
 ```
 
Where it might not make sense to execute my custom python metric if the output isn't SQL in the first place and passing down the result of the `is-sql` assert saves me the time to check for sql validity before computing my custom metrics and just return a failure immediately.
 
Maybe this is intended and having asserts be independent of each other is actually desirable. If that is the case feel free to close this issue and I will just double-check sql validity for each assert.
