### ISSUE TITLE
Facing isuue with API call for LLM model hosted in private VPC.

### ISSUE THREAD

**Issue by sagarghutke** [promptfoo/promptfoo#2148]
**Describe the bug**
I am trying to run `promptfoo eval` command and getting the below error.

`API call error: Error: Request failed after 4  API call error: Error: Request failed after 4 retries: fetch failed.`

We have hosted the "huggingface:text-generation:llama3-8b-instruct" LLM model in our private VPC.

**To Reproduce**
I am running promptfoo as a container using below command:

`docker run --rm -it --entrypoint /bin/sh -p 3000:15500 ghcr.io/promptfoo/promptfoo:0.96.2`

below is my "promptfooconfig.yaml":

```
description: 'HF private inference endpoint'

prompts:
  - write few lines about {{artist}} & summarize it.

providers:
  - id: huggingface:text-generation:llama3-8b-instruct
    config:
      apiEndpoint: https://api_endpoint_of_LLM_model

tests:
  - vars:
      artist : "jordi"
```

1. Run '...'

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**

- Promptfoo version:

**Additional context**
