### ISSUE TITLE
Webhook provider support "body" message

### ISSUE THREAD

**Issue by zhlmmc** [promptfoo/promptfoo#215]
Currently, webhook provider only transfer one parameter to backend:
```json
{
  "prompt": "..."
}
```
which is fine but it would be better to support transfer arbitrary data to backend to support more scenarios. It could be implemented like:
```yaml
providers: 
  - webhook:https://fabb16d9-c83b-4128-a498-d0df44e65faf--main.babel.run/minimax:
      id: minimax
      memo: "arbitrary string"
```
The POST message may look like:
```json
{
  "prompt": "...",
  "memo": "arbitrary string"
}
```
