### ISSUE TITLE
Cannot list multiple scenarios in separate yaml file

### ISSUE THREAD

**Issue by rvernica** [promptfoo/promptfoo#2188]
**Describe the bug**

I have the following in `promptfooconfig.yaml`:
```
scenarios:
 - file://scenarios.yaml
```
And the following in the `scenarios.yaml` file:
```
- config:
    - vars: ...
  tests:
    - vars: ...
- config:
    - vars: ...
  tests:
    - vars: ...
```
When running `eval` I get the following error:
```
> promptfoo eval
TestSuite Schema Validation Error:

  Validation error: Expected object, received array at "scenarios[0]"

Please review your promptfooconfig.yaml configuration.
node_modules/promptfoo/dist/src/evaluator.js:413
                for (const data of scenario.config) {
                                            ^

TypeError: scenario.config is not iterable
    at Evaluator.evaluate (node_modules/promptfoo/dist/src/evaluator.js:413:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runEvaluation (node_modules/promptfoo/dist/src/commands/eval.js:189:9)
    at async doEval (node_modules/promptfoo/dist/src/commands/eval.js:352:5)

Node.js v20.18.0
```

**To Reproduce**
See above

**Expected behavior**
List multiple scenarios in the same yaml file.

**Screenshots**
N/A

**System information (please complete the following information):**

- Promptfoo version: `0.97.0`

**Additional context**
N/A

**Comment by mldangelo** [comment]
Hey @rvernica! Thanks for reporting this – sorry it took us a while to circle back!

Good news: this has been fixed! The issue was resolved in PR #4761 (v0.116.5+), which added proper array flattening when loading scenarios from external files.

## What was happening

When you used:
```yaml
scenarios:
  - file://scenarios.yaml
```

And `scenarios.yaml` contained an array of scenarios, the loader was returning a nested array `[[scenario1, scenario2]]` instead of `[scenario1, scenario2]`. This caused both the schema validation error and the `scenario.config is not iterable` TypeError you saw.

## The fix

We now flatten the scenarios array after loading from external files, so your original config should work as expected:

```yaml
# promptfooconfig.yaml
scenarios:
  - file://scenarios.yaml
```

```yaml
# scenarios.yaml
- config:
    - vars:
        foo: bar
  tests:
    - vars:
        baz: qux
- config:
    - vars:
        foo: bar2
  tests:
    - vars:
        baz: qux2
```

As a bonus, we also added glob pattern support in the same fix, so you can now do things like:
```yaml
scenarios:
  - file://scenarios/*.yaml
```

## Next steps

Just upgrade to v0.116.5 or later and you should be all set!
