### ISSUE TITLE
import environment variables in the providers

### ISSUE THREAD

**Issue by AmineDjeghri** [promptfoo/promptfoo#2224]
Hello,
First of all, i would like to thank you for your reactivity in implementing new features asked by the community.

Following this issue that has been closed #1552 , is it possible to you env variables in the yaml config file for all the fields ?

Here is an exemple : 

```
# env variables are in .env
providers:
  - id: azureopenai:chat:{{ env.AZURE_OPENAI_DEPLOYMENT_NAME }}
    config:
      apiBaseUrl: {{ env.AZURE_OPENAI_ENDPOINT }}
      apiKey: {{ env.AZURE_OPENAI_API_KEY }}
      apiVersion: {{ env.AZURE_OPENAI_API_VERSION }}
```
When using it in this example : 

```

providers:
  - id: azureopenai:chat:gpt-4o-mini
    config:
      apiBaseUrl: {{ env.AZURE_OPENAI_ENDPOINT }}

```

i get the following error : 

```
TypeError: this.apiBaseUrl.replace is not a function
    at AzureChatCompletionProvider.getApiBaseUrl (/Users/aminedjeghri/PycharmProjects/ai-cloud-project-template/node_modules/promptfoo/dist/src/providers/azure.js:262:36)
    at AzureChatCompletionProvider.callApi (/Users/aminedjeghri/PycharmProjects/ai-cloud-project-template/node_modules/promptfoo/dist/src/providers/azure.js:474:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Evaluator.runEval (/Users/aminedjeghri/PycharmProjects/ai-cloud-project-template/node_modules/promptfoo/dist/src/evaluator.js:182:28)
    at async processEvalStep (/Users/aminedjeghri/PycharmProjects/ai-cloud-project-template/node_modules/promptfoo/dist/src/evaluator.js:552:25)
```
