### ISSUE TITLE
Bug: `--no-cache` leads to no embeddings found

### ISSUE THREAD

**Issue by jamesbraza** [promptfoo/promptfoo#223]
I have a `promptfooconfig.yaml` with `promptfoo==0.25.0` that looks like this:

```yaml
---
defaultTest:
    options:
        provider: localai:embeddings:bert-embeddings
prompts: [prompts.txt]
providers: ["ollama:llama2:13b"]
sharing: false
tests:
    - vars:
          area: foo
          result: bar
      assert:
          - type: similar
            value: {{ result }} <redacted> {{ area }}.
```

Running `promptfoo eval --no-cache`, I get:

```
[FAIL] API response error: Error: No embedding found in LocalAI embeddings API response: {"error":{"code":500,"message":"rpc error: code = Unavailable desc = error reading from server: EOF","type":""}}
```

I think somehow the `--no-cache` option is preventing `promptfoo` from using LocalAI embeddings.  It seems there's still a dependency on cache entries to pass data.
