### ISSUE TITLE
Nested Nunjucks variables aren't rendered when config variable points to a file

### ISSUE THREAD

**Issue by sbichenko** [promptfoo/promptfoo#2284]
**Describe the bug**<br>Nested Nunjucks variables, such as `{{ foo.bar }}` aren't rendered when rendering the content of a variable in prompt that points to a file.

**To Reproduce**<br>See the shared promptfoo: [https://app.promptfoo.dev/eval/f:701acdb5-d5f6-48ec-bad8-647780a25d79/](<https://app.promptfoo.dev/eval/f:701acdb5-d5f6-48ec-bad8-647780a25d79/>)

Config:

```yaml
prompts: Output the following "{{ prompttest }}"
providers:
  - openai:gpt-4o-mini
tests:
  - description: 'Test translation to French'
    vars:
      test1: test1-content
      test2: 
        sub: hello-content
      prompttest: file://test.txt
    assert:
      - type: contains
        value: hello-content
```

Test.txt contains the following line:

```
"Hey, this is {{ test1 }}, this is {{ test2 }} and this is {{ test2.sub }}"
```

**Expected behavior**<br>`{{ test2.sub }}` is rendered as `hello-content`

**Actual behaviour**

**Screenshots**<br>If applicable, add screenshots to help explain your problem.

**System information:**

If possible, please output the results of `promptfoo debug` and paste the output here.

```json
{
  "version": "0.99.1",
  "platform": {
    "os": "darwin",
    "release": "23.3.0",
    "arch": "arm64",
    "nodeVersion": "v20.17.0"
  },
  "env": {},
  "configInfo": {
    "configExists": false,
    "configContent": null
  }
}
```
