### ISSUE TITLE
Getting apiKey not present error in test cases when trying to use model-graded-closedqa or llm-rubric

### ISSUE THREAD

**Issue by KlausMikhaelson** [promptfoo/promptfoo#231]
below is just a sample snippet of the test that I am trying to run, I do have the apiKey in my config under  providers
like 
```
providers:
- openai:gpt-3.5-turbo-0613:
    config:
      apiKey: HAVE_ADDED_KEY_HERE
      max_new_tokens: 200
      temperature: 0
    prompts: openai_prompt
- replicate:meta/llama-2-7b-chat:8e6975e5ed6174911a6ff3d60540dfd4844201974602551e10e9e87ab143d81e:
    config:
      apiKey: HAVE_ADDED_KEY_HERE
      max_new_tokens: 200
      temperature: 0
    prompts: firework_prompt
```
 but still getting the below error

![image](https://github.com/promptfoo/promptfoo/assets/100528412/d0a4330f-d757-4e61-bfd4-1921aec717cf)

 - vars:
      message: What's the weather in New York right now?
    assert:
      - type: model-graded-closedqa
        value: does not claim to know the current weather in New York

**Comment by typpo** [comment]
Hi @KlausMikhaelson, this is happening because the assertions use a different provider than the ones you have configured up top.

Try explicitly setting the provider in the assertion:

```yaml
    assert:
      - type: llm-rubric
        value: does not claim to know the current weather in new y
ork
        provider:
          id: openai:gpt-4
          config:
            apiKey: abc123
```

You may also configure this under `defaultTest.options` so you don't have to override the default grader for every assertion:

```yaml
defaultTest:
  options:
    provider:
      id: openai:gpt-4
      config:
        apiKey: abc123
```
