### ISSUE TITLE
Unable to vars and assertions from yaml file

### ISSUE THREAD

**Issue by ishikagoel5628** [promptfoo/promptfoo#235]
I am trying to load vars and assertions for a testcase from the same yaml file. But getting the below error  
```throw new Error(`Test case must have either assert, vars, or options property. Instead got ${JSON.stringify(testCase, null, 2)}`);```

Config:
```
prompts: [prompts.txt]
providers:
  - id: azureopenai:chat:gpt-35-turbo
    config:
      temperature: 0.0
tests: tests.yaml
```

Yaml content:
```
- question: 'abcd'
  entity: abcd
  entity_type: abcd
  topic: abcd
  context: '''abcd'''
  __expected: 'similar(0.9):abcd'
```

**Comment by ishikagoel5628** [comment]
Found a solution

**Comment by apatil4** [comment]
@ishikagoel5628 how did you resolve this?

**Comment by typpo** [comment]
`tests.yaml` is expected to be in testcase format, not CSV

For example:

```yaml
- vars:
    question: 'abcd'
    entity: 'abcd'
  assert:
    - type: similar
      threshold: 0.9
      value: abcd
```

If you're running into issues, please share your config and I can help troubleshoot!

**Comment by apatil4** [comment]
Below is my config yaml. Note i have custom modles that I am evaluating. But it somehow does not like the `tests` part in the yaml
```
# This configuration compares LLM output of 2 prompts x 2 GPT models across 3 test cases.
# Learn more: https://promptfoo.dev/docs/configuration/guide
description: 'My first eval'

prompts:
  - "Write a tweet about {{topic}}"
  - "Write a very concise, funny tweet about {{topic}}"

providers:
  - id: 'python:eval.py'
    config:
      additionalOption: llama
  - id: 'python:eval.py'
    config:
      additionalOption: phi

tests:
  - vars:
      topic: bananas

```
