### ISSUE TITLE
Testing providers w/ same model but diff params seems broken

### ISSUE THREAD

**Issue by dmahlow** [promptfoo/promptfoo#239]
According to this PR: https://github.com/promptfoo/promptfoo/pull/83 I should be able to do the following:
```
providers:
  - openai:gpt-3.5-turbo-0613:
     id: openai:gpt-3.5-turbo-lowtemp
     config:
       temperature: 0

  - openai:gpt-3.5-turbo-0613:
     id: openai:gpt-3.5-turbo-hightemp
     config:
       temperature: 1
```

However, that results in this error:

```
Error: Unknown OpenAI model type: gpt-3.5-turbo-lowtemp. Use one of the following providers: openai:chat:<model name>, openai:completion:<model name>
    at loadApiProvider (/Users/daniel/code/node_modules/promptfoo/dist/src/providers.js:123:19)
    at /Users/daniel/code/node_modules/promptfoo/dist/src/providers.js:69:24
    at Array.map (<anonymous>)
    at loadApiProviders (/Users/daniel/code/node_modules/promptfoo/dist/src/providers.js:57:42)
    at Command.<anonymous> (/Users/daniel/code/node_modules/promptfoo/dist/src/main.js:256:72)
    at Command.listener [as _actionHandler] (/Users/daniel/code/node_modules/promptfoo/node_modules/commander/lib/command.js:482:17)
    at /Users/daniel/code/node_modules/promptfoo/node_modules/commander/lib/command.js:1283:65
    at Command._chainOrCall (/Users/daniel/code/node_modules/promptfoo/node_modules/commander/lib/command.js:1177:12)
    at Command._parseCommand (/Users/daniel/code/node_modules/promptfoo/node_modules/commander/lib/command.js:1283:27)
    at /Users/daniel/code/node_modules/promptfoo/node_modules/commander/lib/command.js:1081:27
```

Version: 0.25.1

The reason I'd like to do that, is because otherwise it's really difficult to gauge in the result which provider had which settings:

![Screenshot 2023-10-24 at 16 08 24](https://github.com/promptfoo/promptfoo/assets/489843/0d1c12f0-7bed-4845-ac41-38070d9b98bd)

Is there another mechanism (like a label or such) I can use to show a specific model name in the result for the case where the model is the same, but only the configs are different?

**Comment by typpo** [comment]
Hi @dmahlow, I wonder if there's a different part of your setup that's causing this.  This config works without error for me:

```yaml
prompts: [prompts.txt]
providers:
  - openai:gpt-3.5-turbo-0613:
     id: openai:gpt-3.5-turbo-lowtemp
     config:
       temperature: 0

  - openai:gpt-3.5-turbo-0613:
     id: openai:gpt-3.5-turbo-hightemp
     config:
       temperature: 1
tests:
  - vars:
      var1: test 1
  - vars:
      var1: test 2
  - vars:
      var1: test 3
```

As well as [this example](https://github.com/promptfoo/promptfoo/tree/main/examples/gpt-3.5-temperature-comparison).

Can you double check on your end or share other details of your setup?

I agree that a `label` field would be nice to have and a bit clearer to use.
