### ISSUE TITLE
Error asserting factuality with Bedrock Claude

### ISSUE THREAD

**Issue by dliuupgrade** [promptfoo/promptfoo#2573]
**Describe the bug**
When asserting with type factuality and overriding the test provider to `bedrock:anthropic.claude-3-5-sonnet-20240620-v1:0`, we get the error:

```
ValidationException: Malformed input request: #: subject must not be valid against schema {"required":["messages"]}#/messages: expected minimum item count: 1, found: 0, please reformat your input and try again. 
```

**To Reproduce**
1. Create a test query that is asserted on factuality. Override the test provider to `bedrock:anthropic.claude-3-5-sonnet-20240620-v1:0`
2. Run Promptfoo Eval
3. See error

**Expected behavior**
The evaluation should not fail.

- Promptfoo version: 0.103.3

**Additional context**
We recently upgraded to latest from 0.92.2 and started seeing this issue. We had no issues on the older version.

**Comment by MrFlounder** [comment]
Thanks @dliuupgrade for the report. I wasn't able to replicate the error you are getting in version 0.103.3. Do you mind sharing your config.yaml?

Setup below works for me

```
prompts:
  - 'What is the capital of {{state}}?'
providers:
  - bedrock:anthropic.claude-3-5-sonnet-20240620-v1:0
tests:
  - vars:
      state: California
    assert:
      - type: factuality
        value: Sacramento is the capital of California
  - vars:
      state: New York
    assert:
      - type: factuality
        value: Albany is the capital city of New York state
```

**Comment by mldangelo** [comment]
@dliuupgrade if you can't get it working feel free to throw some time on my calendar: https://cal.com/michael-dangelo/15min

**Comment by dliuupgrade** [comment]
Hey @MrFlounder, below is my config:

```
prompts: ['prompt.txt']
providers:
  - id: 'python:script.py'
    label: 'Test Sonnet 3-5v2 - cohere deduped - rerank, increase top k, operations pages added'
    config:
      model_name: anthropic.claude-3-5-sonnet-20241022-v2:0
      index_path: "some_path_to_index"
      top_k: 30
      ranking_model: "cohere.rerank-v3-5:0"

defaultTest:
  options:
    provider: bedrock:anthropic.claude-3-5-sonnet-20240620-v1:0

tests:
  - description: Intake Marketing Opt Out
    vars:
      query: "How do I intake a marketing opt out request?"
    assert:
      - type: factuality
        value: >
            Answer to the question
```

The script.py is code that runs the `call_api` function through our RAG pipeline. Let me know if you want to see that as well. 

@mldangelo if it can't be resolved here, happy to schedule something thanks!
