### ISSUE TITLE
Promptfoo eval with temperature 0 generates different responses for different users.

### ISSUE THREAD

**Issue by DarioBernardo** [promptfoo/promptfoo#2729]
This is quite a big issue, because is hampering trust in the tool.

 I have a number of promptfoo tests in a github repo. The same code checked out by different users and executed with promptfoo eval generates different failing test cases for different users. 

Something else that I have noticed is that the exact same prompt generates slightly different responses from the actual app I am trying test cases for. I believe I am using the same prompts and settings (temperature of 0 and seed) and yet the app every now and then is giving slightly different responses from propmptfoo tests.

```
providers:
  - id: "openai:gpt-4o"
    config:
      temperature: 0.0
      seed: 111
``` 

Any idea on how i can fix the issue or I can check what's going on?
