### ISSUE TITLE
Deepseek R1 is not working

### ISSUE THREAD

**Issue by zhlmmc** [promptfoo/promptfoo#2752]
**Describe the bug**
The model name of deepseek R1 is deepseek-reasoner https://api-docs.deepseek.com/quick_start/pricing . I'm trying to evaluate this model using promptfoo.

**To Reproduce**
Steps to reproduce the behavior, including example Promptfoo configurations if applicable:

consider the following config:
```yaml
providers:
### Deepseek
  - openai:chat:deepseek-chat:
      id: deepseek-chat
      config:
        apiKey: sk-
        apiBaseUrl: https://api.deepseek.com
  - openai:chat:deepseek-reasoner:
      id: deepseek-reasoner
      config:
        apiKey: sk-
        apiBaseUrl: https://api.deepseek.com
```
When invoke both deepseek models, we will see the following error:
```
API error: 400 Bad Request
{"error":{"message":"deepseek-reasoner does not support the parameter `presence_penalty`","type":"invalid_request_error","param":null,"code":"invalid_request_error"}}
```

**Expected behavior**
should be working just like deepseek-chat

**Screenshots**

**System information:**

- Promptfoo version:
0.103.8

**Additional context**
