### ISSUE TITLE
How can I upload a file to be read during prompt testing with Promptfoo?

### ISSUE THREAD

**Issue by funmise** [promptfoo/promptfoo#2785]
I am currently using Promptfoo and would like to test prompts that require uploading and processing a file (e.g., a PDF document or dataset). How can I configure Promptfoo to include a file upload as part of the testing process so that the file can be read and used during the evaluation?

**Comment by jaya437** [comment]
Did you find a solution for the issue? Please post if you have any.

**Comment by nt9142** [comment]
Hey @jaya437, you can load your file contents as a variable and then reference to it as base64:

https://www.promptfoo.dev/docs/configuration/parameters/#loading-images-and-other-file-types

**Comment by mldangelo** [comment]
Hi @funmise,

Thanks for your question about using Azure OpenAI for model-graded assertions.

You can specify Azure as the grader provider in your assertions:

```yaml
tests:
  - assert:
      - type: llm-rubric
        value: "Check if the output is helpful"
        provider:
          id: azure:chat:your-grader-deployment
          config:
            apiHost: your-azure-endpoint.openai.azure.com
            apiKey: ${AZURE_OPENAI_API_KEY}
```

Key points:
- Use `azure:chat:deployment-name` format
- Specify the grader provider in the assertion's `provider` field
- Include necessary Azure configuration (apiHost, apiKey, etc.)

See the [Azure Provider documentation](https://www.promptfoo.dev/docs/providers/azure) and [Model-Graded Assertions](https://www.promptfoo.dev/docs/configuration/expected-outputs/model-graded) for more details.

Thanks!
