### ISSUE TITLE
Feature request: ability to reference all outputs in tests

### ISSUE THREAD

**Issue by miltondp** [promptfoo/promptfoo#289]
Unless I missed something in the documentation, in tests we can only access the output of one combination of provider/prompt. For each input data, I'd like to be able to compare the outputs of all prompts. For example, I'm testing prompts that revise manuscripts' abstracts. So if I have three prompts, I'd like to reference the three revised abstracts given one input. The idea of this is to ask another LLM model to grade them.

Based on my understanding of the documentation, in tests, we are limited to accessing the output from only one prompt at a time. However, for each input data, I would like to compare outputs from all the prompts. For instance, when testing prompts that revise manuscript abstracts, if I use three different prompts, I want to be able to review the three corresponding revised abstracts for a single input. So in a test, I'd like to be able to reference `output[0]`, `output[1]` and `output[2]`. The purpose of this is to have another LLM model evaluate and grade these revised abstracts together.

**Comment by typpo** [comment]
Hi @miltondp, thanks for the suggestion.  I understand the usefulness of being able to compare multiple outputs in a single prompt.  

You're correct that right now the eval runner executes each provider/prompt combo independently, rather than per row.  I'm interested in implementing this and will consider the best way to incorporate other outputs.

**Comment by typpo** [comment]
Hi @miltondp, this functionality has been added via the `select-best` assertion type in #438.  It will be in the next release.

For example:
```yaml
prompts:
  - "Write a tweet about {{topic}}"
  - "Write a very concise, funny tweet about {{topic}}"

providers: [openai:gpt-4]

tests:
  - vars:
      topic: bananas
    assert:
      - type: select-best
        value: choose the funniest tweet

  - vars:
      topic: nyc
    assert:
      - type: select-best
        value: choose the tweet that contains the most facts
```

Let me know what you think!
