### ISSUE TITLE
Transform context for model based evaluation from custom provider

### ISSUE THREAD

**Issue by blafab-hg** [promptfoo/promptfoo#2893]
**Is your feature request related to a problem? Please describe.**

We want to use promptfoo to evaluate the performance of our RAG system.

```
import promptfoo from 'promptfoo';

export default {
    prompts: ['{{input}}'],
    providers: [{
        id: API_URL,
        label: ENV,
        config: {
            headers: {
                "Content-Type": "application/json",
            },
            body: {
                prompt: "{{input}}",
                type: "text",
            },
            evaluateOptions: {
                maxConcurrency: 1,
                delay: 1000
            }
        },
    }],
    defaultTest: {
        options: {
            transform: "output.content", // extract the "content" field from the response
        }
    },
    "tests": get_test_set(),
};
```

The page about the context-recall (https://www.promptfoo.dev/docs/configuration/expected-outputs/model-graded/context-recall/) shows that the context needs to be provided within the testcase:
```
tests:
  - vars:
      query: 'What is our maternity leave policy?'
      context: file://docs/policies/maternity.md
    assert:
      - type: context-recall
        threshold: 0.9
        value: |
          Employees get 4 months paid maternity leave.
          Leave can be taken before or after birth.
          Additional unpaid leave is available upon request.
```
In our case the custom provider also returns the documents in the "output.source_documents" field. 

**Describe the solution you'd like**

A way to add a transformer of some kind to take the custom provider response and get the context from it.

**Describe alternatives you've considered**

**Additional context**

**Comment by mldangelo** [comment]
Hey @blafab-hg, this is now supported via the `contextTransform` property on assertions.

For your RAG system where the context is in `output.source_documents`, you can do:

```yaml
tests:
  - vars:
      query: 'What is our maternity leave policy?'
    assert:
      - type: context-recall
        threshold: 0.9
        contextTransform: 'output.source_documents.map(d => d.content).join("\n")'
        value: |
          Employees get 4 months paid maternity leave.
          Leave can be taken before or after birth.
```

The `contextTransform` accepts a JavaScript expression that receives the full provider response as `output`. You can use it to extract and format the context however you need.

Docs: https://www.promptfoo.dev/docs/configuration/expected-outputs/model-graded/#dynamically-via-context-transform
