### ISSUE TITLE
After upgrading to latest version 0.103.17 from 0.93.3, I get provider not found issue

### ISSUE THREAD

**Issue by alinv0** [promptfoo/promptfoo#2910]
**Describe the bug**
I have a docker image that runs promptfoo version 0.93.3. I am using an Azure OpenAI model.
I created a new version for this image, with the latest version - 0.103.17 and when I try to run promptfoo tests, I get the error: 
Could not identify provider: .

This is my test.yaml confguration for the provider:
```
defaultTest:
  options:
    provider:
      id: azureopenai:chat:gpt-4o
      label: gpt-4o-2024-05-13
```

**To Reproduce**
Steps to reproduce the behavior, including example Promptfoo configurations if applicable:

1. add the provider configuration to the tests file:
```
defaultTest:
  options:
    provider:
      id: azureopenai:chat:gpt-4o
      label: gpt-4o-2024-05-13
```
2. Make sure you have promptfoo version 0.93.3.
3. Set environment variables:
- AZURE_OPENAI_API_KEY
- AZURE_OPENAI_API_HOST
- SINGULARITY_API_URI

4. Run 'promptfoo eval -c tests/default.yaml --verbose --output test_results.json'
5. See that it is working
6. Update to latest promptfoo version 0.103.17
7. See the error: Could not identify provider: .

**Screenshots**

**System information:**

If possible, please output the results of `promptfoo debug` and paste the output here.

{
  "version": "0.103.17",
  "platform": {
    "os": "linux",
    "release": "6.10.14-linuxkit",
    "arch": "x64",
    "nodeVersion": "v20.18.0"
  },
  "env": {},
  "configInfo": {
    "configExists": false,
    "configContent": null
  }
}

- Promptfoo version: 0.103.17

**Additional context**
