### ISSUE TITLE
Automatic tests does not work with Azure

### ISSUE THREAD

**Issue by pierrelandry** [promptfoo/promptfoo#292]
I have set the AZURE_OPENAI_API_KEY and : 

tests are failing like this :
![Capture d’écran 2023-11-24 à 17 14 24](https://github.com/promptfoo/promptfoo/assets/17323800/b043f96c-f41e-4bbf-aff4-48c4ff58d8d3)

with`promptfooconfig.yaml` set like this : 
```
prompts: file://prompts.txt
providers:
  - id: azureopenai:chat:xxxxx
    config:
      apiHost: 'xxxxxxx.openai.azure.com'
      temperature: 0.5
      max_tokens: 1024
defaultTest:
  assert:
    - type: llm-rubric
      value: Do not mention that you are an AI or chat assistant
tests:
  - vars:
      name: Bob
      question: Can you help me find a specific product on your website?
```
      
 Tests are Ok like this :
![Capture d’écran 2023-11-24 à 17 17 15](https://github.com/promptfoo/promptfoo/assets/17323800/28b189fd-7111-45f3-9c06-7a574169f0db)

when `promptfooconfig.yaml` is set like this : 
```
prompts: file://prompts.txt
providers:
  - id: azureopenai:chat:xxxxx
    config:
      apiHost: 'xxxxxxx.openai.azure.com'
      temperature: 0.5
      max_tokens: 1024
tests:
  - vars:
      name: Bob
      question: Can you help me find a specific product on your website?
```

**Comment by typpo** [comment]
Hi @pierrelandry,

The `llm-rubric` assertion uses OpenAI by default.  You'll have to override that provider.  Try something like this:

```yaml
defaultTest:
  assert:
    - type: llm-rubric
      value: Do not mention that you are an AI or chat assistant
      provider:
        id: azureopenai:chat:xxxx
        config:
          apiHost: 'xxxxxxx.openai.azure.com'
          temperature: 0.5
          max_tokens: 1024
```
