### ISSUE TITLE
[BUG] `rubricPrompt` breaks when using `.json` file

### ISSUE THREAD

**Issue by mshavliuk** [promptfoo/promptfoo#2929]
**Describe the bug**

The `rubricPrompt` throws an error when used with json file

**To Reproduce**
I am using custom LLM rubric messages stored in a `.json` file:

```json
[
  {
    "role": "system",
    "content": "Evaluate the summary for factual correctness"
  },
  {
    "role": "user",
    "content": "Here is the form in YAML format {{ form }}.\n\nThis is the summary generated by the system: {{ output }}.\n\nYour Task: {{ rubric }}.\n\nReply in JSON format as follows: {\"reason\": \"<Analysis of the rubric and the output>\", \"score\": <0.0-1.0>, \"pass\": <true or false>}"
  }
]
```

And use the following `promptfooconfig.yaml`:
```yaml
description: "Bug demo"

prompts:
  - 'summarize this form value in 10 words: {{ form }}'

providers:
  - bedrock:amazon.nova-micro-v1:0

tests:
  - vars:
      form: |
        title: "bug report"
        description: "I found a bug: the system crashed."
    assert:
      - type: llm-rubric
        rubricPrompt: file://rubric.json
        value: Evaluate summary correctness and clarity.
        provider: bedrock:amazon.nova-micro-v1:0
```

As a result, I get an error:
```
Error: Invariant failed: rubricPrompt must be a string
```

Meanwhile, if I just switch the file type of `rubric.json` to `.txt` it works just fine:

<img width="1154" alt="Image" src="https://github.com/user-attachments/assets/dbffc196-85ed-49c9-b439-b92ecb400bef" />

**Expected behavior**

Support `.json` files for `rubricPrompt`.

**System information:**

- Promptfoo version: 0.103.17
