### ISSUE TITLE
Error invoke o3-mini

### ISSUE THREAD

**Issue by zhlmmc** [promptfoo/promptfoo#2944]
**Describe the bug**
When invoke latest OpenAI o3-mini, I got the following error:
```
API error: 400 Bad Request
{"error":{"message":"Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.","type":"invalid_request_error","param":"max_tokens","code":"unsupported_parameter"}}
```

**To Reproduce**
I'm using the following config
```yaml
providers: 
### OpenAI
  - openai:o3-mini:
      id: openai-o3-mini
      config:
        apiKey: xxxx
```

**System information:**

MacOS

- Promptfoo version:
0.103.18
