### ISSUE TITLE
Promptfoo splits big prompts

### ISSUE THREAD

**Issue by mkrudele** [promptfoo/promptfoo#2948]
**Describe the bug**
When using a big prompt, I noticed that it gets split in multiple parts. So, the tests are all invalidated because performed with partial prompts.

**To Reproduce**
Simple. Use > 4k prompt with a model that supports it. You'll see that the prompt is split in multiple parts and the provider called multiple times. In the promptfoo ui that's evident because you'll see multiple prompt columns.

I used this config:

```
description: "My eval"

prompts:
  - file://big-prompt.txt

providers:
  - "watsonx:meta-llama/llama-3-2-11b-vision-instruct"

tests:
  - vars:
      inquiry: "I have a problem with my order"
```

with the attached prompt:

[big-prompt.txt](https://github.com/user-attachments/files/18628727/big-prompt.txt)

**Expected behavior**
Send the entire configured prompt to the provider.

**Screenshots**
Multiple output columns for the split prompt.

![Image](https://github.com/user-attachments/assets/bdc5ac11-125d-4b41-b4ed-3907bdd81906)

**System information:**

If possible, please output the results of `promptfoo debug` and paste the output here.

- Promptfoo version:

**Additional context**
