### ISSUE TITLE
[BUG] `rubricPrompt` does not render '.json' templates

### ISSUE THREAD

**Issue by mshavliuk** [promptfoo/promptfoo#2961]
**Describe the bug**

The `rubricPrompt` throws an error when used with `.json` nunjucks template

**To Reproduce**
I am using custom LLM rubric messages stored in a `.json` file:

```json
[
  {%- set system_prompt -%}
    Evaluate the summary for factual correctness
  {%- endset -%}
  {
    "role": "system",
    "content": {{ system_prompt | dump }}
  },
  {
    "role": "user",
    "content": "Here is the form in YAML format {{ form }}.\n\nThis is the summary generated by the system: {{ output }}.\n\nYour Task: {{ rubric }}.\n\nReply in JSON format as follows: {\"reason\": \"<Analysis of the rubric and the output>\", \"score\": <0.0-1.0>, \"pass\": <true or false>}"
  }
]
```

And use the following `promptfooconfig.yaml`:
```yaml
description: "Bug demo"

prompts:
  - 'summarize this form value in 10 words: {{ form }}'

providers:
  - bedrock:amazon.nova-micro-v1:0

tests:
  - vars:
      form: |
        title: "bug report"
        description: "I found a bug: the system crashed."
    assert:
      - type: llm-rubric
        rubricPrompt: file://rubric.json
        value: Evaluate summary correctness and clarity.
        provider: bedrock:amazon.nova-micro-v1:0
```

As a result, I get an error:
```
SyntaxError: Expected property name or '}' in JSON at position 5
```

Meanwhile, if I just switch the file type of `rubric.json` to `.txt` it works just fine, renders proper JSON string and sends the following to the provider API:

```json
[ {
  "role" : "system",
  "content" : "\n    Evaluate the summary for factual correctness"
}, {
  "role" : "user",
  "content" : "Here is the form in YAML format title: \"bug report\"\ndescription: \"I found a bug: the system crashed.\".\n\nThis is the summary generated by the system: Bug report found system crash..\n\nYour Task: Evaluate summary correctness and factual accuracy..\n\nReply in JSON format as follows: {\"reason\": \"<Analysis of the rubric and the output>\", \"score\": <0.0-1.0>, \"pass\": <true or false>}"
} ]
```

**Expected behavior**

Template rendering works equivalently for `.json` and `.txt` files

**System information:**

- Promptfoo version: 0.103.19
