### ISSUE TITLE
question: rag evaluation with amazon bedrock

### ISSUE THREAD

**Issue by arm-diaz** [promptfoo/promptfoo#303]
I would like to evaluate rag systems with models from Amazon Bedrock. Got an error when running `npx promptfoo@latest eval` with `providers: [bedrock:anthropic.claude-v2]` using the examples in example/rag-eval. It says, `Error: OpenAI API key is not set. Set the OPENAI_API_KEY environment variable or add `apiKey` to the provider config.`

1) Which functions need to be implemented to support RAG evaluation? 
2) I found some providers have an ApiEmbeddingProvider. How is the embedding used in this project? AWS supports multiple embedding models via Bedrock. I'd like to understand this more and see if we can add them in the near feature.

**Comment by typpo** [comment]
[Model-graded assertions](https://promptfoo.dev/docs/configuration/expected-outputs/model-graded/) such as `factuality` or `context-recall`, etc, use OpenAI by default. If you are using Bedrock/Anthropic, you must override the grader to point to Bedrock:

The easiest way to do this for all your test cases is to add the [defaultTest](https://promptfoo.dev/docs/configuration/guide/#default-test-cases) property to your config:

```yaml
defaultTest:
  options:
    provider: bedrock:anthropic.claude-v2
```

You can also do this for individual assertions:

```yaml
  # ...
  assert:
    - type: llm-rubric
      value: ...
      provider: bedrock:anthropic.claude-v2
```

For embeddings (used for e.g. similarity assertions), you can override the provider in a similar way, but we'd have to implement `callEmbeddingApi` in the Bedrock provider.
