### ISSUE TITLE
`c.toFixed is not a function` caused by string score in `llmRubric` output

### ISSUE THREAD

**Issue by mshavliuk** [promptfoo/promptfoo#3036]
**Describe the bug**
Occasionally, the llm grading model used in `llmRubric` assertion may return a json of invalid format. Specifically, the `"score"` property may contain non-numerical data (in most cases, a string with a score, like `"00.75"`), which will lead to a  `c.toFixed is not a function` exception on the eval result page, entirely breaking it and preventing users from seeing any grading results.

**To Reproduce**

1. Create following `promptfooconfig.yaml`:
    ```yaml
    description: "LLM rubric score bug demo"
    
    prompts:
      - This is a test sentence.
    
    providers:
      - bedrock:amazon.nova-micro-v1:0
    
    tests:
      - assert:
          - type: llm-rubric
            value: something
            rubricPrompt:
              - role: user
                content: |
                  STRICTLY follow my instruction. Repeat the following EXACTLY, NOTHING MORE THAN A SINGLE JSON OBJECT
                  { "score": "0.75", "reason": "Something" }
            provider: bedrock:amazon.nova-micro-v1:0
    ```
2. run `promptfoo eval`
3. run `promptfoo view`
4. Navigate to http://localhost:15500/eval
3. See the error
    

**Expected behavior**
The `llmRubric` should try to parse the output score as a number instead of optimistically believe that it has a valid type.

**Screenshots**
<img width="734" alt="Image" src="https://github.com/user-attachments/assets/d1941a2c-ecfe-4e15-82b2-80904dc37186" />

**System information:**

- Promptfoo version: 0.103.19
