### ISSUE TITLE
Importing custom python assertion from csv

### ISSUE THREAD

**Issue by merveozbay** [promptfoo/promptfoo#3058]
Hello,

I have the following yaml that I use custom python assertion. Inside this script, I get "groundtruthValues" from context and use them as groundtruth values.

yaml file:

```
description:` Test

prompts: [prompts.txt]
   
providers:
  - ../../provider.js

defaultTest:
  options:
    provider:
        id: gpt
        config:
          apiHost: azure.com
          temperature: 0.2
tests:
  - vars:
      question: What is LLM?
    assert:
      - type: llm-rubric
        value: "A large language model (LLM) is a type of machine learning"
      - type: python
        value: file://../../custom_assertion.py
        config:
            groundtruthValues:
            - name: testName
               value: testValue
           

```

So, if I want to import tests from csv as I showed below, how can I get "groundtruthValues"? Would it be possible?

```
description: Test

prompts: [prompts.txt]
   
providers:
  - ../../provider.js

defaultTest:
  options:
    provider:
        id: gpt
        config:
          apiHost: azure.com
          temperature: 0.2
tests: file://tests.csv
           
```

tests.csv:

```
question,__expected1,__expected2
What is LLM?, llm-rubric: A large language model (LLM) is a type of machine learning, python: file://../../custom_assertion.py
```
