### ISSUE TITLE
Access Models configured in LiteLLM Proxy Server

### ISSUE THREAD

**Issue by ramnamy** [promptfoo/promptfoo#3096]
In my litellm, I have configured the below bedrock models.  In promptfoo, when I the model name like this "openai:chat:bedrock:amazon-nova-lite-v1:0" i am getting the error not found at LiteLLM side. What is the correct way to litellm models?

```yaml
model_list:
  - model_name: amazon-nova-lite-v1:0
    litellm_params: 
      model: bedrock/amazon.nova-lite-v1:0 
  - model_name: amazon-nova-micro-v1:0
    litellm_params:
      model: bedrock/amazon.nova-micro-v1:0
  - model_name: amazon-nova-pro-v1:0
    litellm_params:
      model: bedrock/amazon.nova-pro-v1:0
```
