### ISSUE TITLE
Google provider broken with OpenAI-compatible prompt format containing multiple content parts

### ISSUE THREAD

**Issue by sobjornstad** [promptfoo/promptfoo#3129]
**Describe the bug**

In the `google` provider with (at least) Gemini models, when using OpenAI compatible prompt format with multiple `content` elements in the user role (whether or not there is actually more than one part), the following error occurs:

```
API did not return any candidate responses: {"error":{"code":400,"message":"Invalid JSON payload received. Unknown name \"content\" at 'contents[0]': Cannot find field.\nInvalid JSON payload received. Unknown name \"content\" at 'contents[1]': Cannot find field.","status":"INVALID_ARGUMENT","details":[{"@type":"type.googleapis.com/google.rpc.BadRequest","fieldViolations":[{"field":"contents[0]","description":"Invalid JSON payload received. Unknown name \"content\" at 'contents[0]': Cannot find field."},{"field":"contents[1]","description":"Invalid JSON payload received. Unknown name \"content\" at 'contents[1]': Cannot find field."}]}]}}
```

This was previously mentioned in [issue 1876](https://github.com/promptfoo/promptfoo/issues/1876), but I don't think the PR that's mentioned at the end of the linked issue was actually relevant to that issue because that change was to the Vertex provider, and the issue was about the Google provider. This is, however, the same error that was reported there.

This format works:

```
- role: system
  content: |-
    You are a helpful AI assistant.
- role: user
  content: |-
    What is {{thing}}?
```

But this one doesn't:

```
- role: system
  content: |-
    You are a helpful AI assistant.
- role: user
  content:
    - type: text
      text: |-
        What is {{thing}}?
```

(Of course, in reality, there would be no reason to use this form unless there were multiple content parts; I've shown it with one to be as minimal as possible.)

This second format works fine with other providers, like OpenAI and Anthropic – it's only the Google provider that has an issue with it.

**To Reproduce**

Failing `promptfooconfig.yaml`:
```
description: test
prompts:
    - file://prompt.yaml
providers:
    - google:gemini-1.5-flash-002
    - google:gemini-2.0-flash
tests:
    - vars:
        thing: 2 + 2
```

Add bad prompt and `promptfooconfig.yaml` files and run promptfoo on the config.

**Expected behavior**

The request would return a completion, rather than a 400 Bad Request.

**System information:**

If possible, please output the results of `promptfoo debug` and paste the output here.

- Promptfoo version:  0.104.4

```
{
  "version": "0.104.4",
  "platform": {
    "os": "linux",
    "release": "5.10.233-1-MANJARO",
    "arch": "x64",
    "nodeVersion": "v18.17.0"
  },
  "env": {},
  "configInfo": {
    "configExists": false,
    "configContent": null
  }
}
```
