### ISSUE TITLE
Can't use 'rouge_score' in custom metrics due to circular import

### ISSUE THREAD

**Issue by Valkea** [promptfoo/promptfoo#3148]
**Describe the bug**
I'm creating a bunch of custom metrics and they all work very well except for one based one the "rouge_score" library (https://pypi.org/project/rouge-score/).

When I try to import this specific library to a custom metric script (even a working one), I get the following error : 
`ImportError: cannot import name 'rouge_scorer' from partially initialized module 'rouge_score' (most likely due to a circular import)`

**To Reproduce**

1. Install the rouge_score library
2. Select an existing and working custom metric script
3. Add `from rouge_score import rouge_scorer` with the other imports 
4. Run the evaluation and see the error

If I run the very same custom script directly (without promptfoo, but using a main entrypoint) it works perfectly.

- Promptfoo version: 0.104.4

**Additional infos**
I know you added the `rouge-n` score to promptfoo, so it might come from here. However, I have also implemented a custom BLUE score metric (using the sacrebleu library) and I don't have similar problem (And I get different scores with your `blue` metric and my custom blue metric, but I will open a different issue to discuss that).

**Comment by mldangelo** [comment]
Hey @Valkea, I am sorry you're running into this issue. Can you help with a minimal example so I can try to reproduce and resolve your issue? A short promptfoo config such as:

```yaml
# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
provider:
  - echo
prompts: '{{prompt}'
tests:
  - vars:
      prompt: ....
    assert:
      - type: ...
```

along with your python script would be really helpful
