### ISSUE TITLE
Can't use Claude Models on Google Vertex (with images)

### ISSUE THREAD

**Issue by ricardovf** [promptfoo/promptfoo#3191]
```yaml
  - id: "vertex:claude-3-5-sonnet-v2@20241022"
    label: vertex-claude-3-5-sonnet-v2@20241022-0-temp
    config:
      region: us-east5
      publisher: anthropic
      temperature: 0
```

```js
function makePromptVertexClaude(file, imageBase64) {
  const promptText = fs.readFileSync(
    path.join(__dirname, file),
    'utf-8'
  );

  return [
    {
      role: "user",
      content: [
        {
          type: "text",
          text: promptText
        },
        {
          type: "image",
          source: {
            type: "base64",
            media_type: "image/jpeg",
            data: imageBase64
          }
        }
      ]
    }
  ];
}
```

Return:

```
"message":"messages: Field required"
```
