### ISSUE TITLE
Empty output when tool is being called by OpenRouter provider

### ISSUE THREAD

**Issue by Valian** [promptfoo/promptfoo#3204]
**Describe the bug**
We're unable to make assertions on tool calls using providers other than OpenAI, eg OpenRouter or Google. Somehow output seems to be empty string when tool is being called by one of these providers. 

We want to switch from gpt-4o-mini to gemini 2.0, but sadly we're not able to run out test suite :( 

**To Reproduce**
Running this config causes error, while switching to openai:gpt-4o-mini works just fine

```yaml
prompts:
  - 'What is the weather like in {{city}}?'

providers:
  - id: openrouter:openai/gpt-4o-mini
    config:
      tools: [
        {
          "type": "function",
          "function": {
            "name": "get_current_weather",
            "description": "Get the current weather in a given location",
            "parameters": {
              "type": "object",
              "properties": {
                "location": {
                  "type": "string",
                  "description": "The city and state, e.g. San Francisco, CA"
                },
                "unit": {
                  "type": "string",
                  "enum": ["celsius", "fahrenheit"]
                }
              },
              "required": ["location"]
            }
          }
        }
      ]

tests:
  - vars:
      city: Boston
    assert:
      # just to debug output value
      - type: javascript
        value: "output"
      - type: is-valid-openai-tools-call
      - type: javascript
        value: output[0].function.name === 'get_current_weather'
      - type: javascript
        value: JSON.parse(output[0].function.arguments).location === 'Boston, MA'
```

**Expected behavior**
Test should pass

**Screenshots**

<img width="1203" alt="Image" src="https://github.com/user-attachments/assets/23714fe6-f95f-4114-8750-c6dfd8e0ba2e" />

**System information:**

```
  "version": "0.104.4",
  "platform": {
    "os": "darwin",
    "release": "23.5.0",
    "arch": "arm64",
    "nodeVersion": "v22.8.0"
  },
```
