### ISSUE TITLE
"Error: OpenAI API key must be set for similarity comparison" comes up after using AZURE_OPENAI_API_KEY

### ISSUE THREAD

**Issue by anoura12** [promptfoo/promptfoo#323]
I'm using the Azure integration to run a similarity check for my prompts but this error comes up which asks me for my OPENAI_API_KEY instead. I've tried the overrides as well but that doesn't seem to work either.

I exported the AZURE_OPENAI_API_KEY separately in the command line.

`promptfooconfig.yaml`
```
prompts:
  - "Generate one very interesting fact about {{topic}}"

providers:
    - id: azureopenai:chat:gpt-35-turbo-16k
      config:
        apiHost: 'llm.openai.azure.com'

tests:
  - vars:
      topic: bananas
    assert:
    - type: similar
      value: Bananas are naturally radioactive.
      provider: azureopenai:chat:gpt-35-turbo-16k
```

**Comment by anoura12** [comment]
Hi @typpo 

I tried adding the apiHost and the apiKey in the provider this time and it seems that I'm getting the same error again.

```
prompts:
  - "Generate one very interesting fact about {{topic}}"

providers:
    - id: azureopenai:chat:gpt-35-turbo-16k
      config:
        apiHost: 'xxxx.openai.azure.com'
        apiKey: abc123

tests:
  - vars:
      topic: bananas
    assert:
      - type: similar
        value: Bananas are naturally radioactive.
        provider:
          id: azureopenai:chat:gpt-35-turbo-16k
          config:
            apiHost: 'xxxx.openai.azure.com'
            apiKey: abc123
    
```

Here is the error
![Screenshot from 2023-12-06 11-30-47](https://github.com/promptfoo/promptfoo/assets/73518403/29370e20-0809-42f6-8fea-909723579cbe)

Is there something I'm missing? Any idea what I should look into the Azure setup?
