### ISSUE TITLE
Google providers: Adding an API key as an env var is not working

### ISSUE THREAD

**Issue by jakubLangr** [promptfoo/promptfoo#3256]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, including example Promptfoo configurations if applicable:

I've tried all permutations of the below
```
# Define providers (LLM models)
providers:
  - id: "google:gemini-2.0-flash-exp"
    config:
      temperature: 0.2
      apiKey: ${process.env.GOOGLE_API_KEY}
or 
      # apiKey: "${GOOGLE_API_KEY}"
      # apiKey: env.GOOGLE_API_KEY


env:
  GOOGLE_API_KEY: ${GOOGLE_API_KEY}
```

With several permutations of
```
GOOGLE_API_KEY=key npx promptfoo eval --verbose --config tests/promptfoo.yaml 
GOOGLE_API_KEY=key promptfoo eval --verbose --config tests/promptfoo.yaml --env-path ~/code/axis_codebase/workers/event-quantifier-processor/.env
```
etc. 
With no results. and always 
```
        Google API response: {"error":{"code":400,"message":"API key not valid. Please pass a valid API key.","status":"INVALID_ARGUMENT","details":[{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"API_KEY_INVALID","domain":"googleapis.com","metadata":{"service":"generativelanguage.googleapis.com"}},{"@type":"type.googleapis.com/google.rpc.LocalizedMessage","locale":"en-US","message":"API key not valid. Please pass a valid API key."}]}}
```
Can anyone pls help? 

I'm using an .env file as well it's in `.` not `tests` though

**Expected behavior**

**Screenshots**

**System information:**

If possible, please output the results of `promptfoo debug` and paste the output here.

- Promptfoo version:
0.105.1

**Additional context**
