### ISSUE TITLE
Loading variables from a file with scenarios does not work

### ISSUE THREAD

**Issue by miltondp** [promptfoo/promptfoo#328]
According to the [documentation](https://promptfoo.dev/docs/configuration/guide#avoiding-repetition), it is possible to load the content of a variable (under `vars`) from a file using the `file://` prefix. However, this does not seem to work when the variables are under `scenarios` / `config`. For example:

```yaml
prompts:
  [file://../../prompts/baseline.txt, file://../../prompts/candidate.txt]
providers:
  - ollama:mistral:7b-instruct-fp16
scenarios:
  - config:
      - vars:
          test_description: spelling/grammar errors
          title: Projecting genetic associations through gene expression patterns highlights disease etiology and drug mechanisms
          keywords: 'genetic studies, functional genomics, gene co-expression, therapeutic targets, drug repurposing, clustering of complex traits'
          paragraph: file://./spelling_errors.md
    tests:
      - description: Introduction
        assert:
          - type: python
            # Contains the header
            value: |
              print("## Introduction\n" in output)
```

does not load the file `spelling_errors.md` on the variable `paragraph`, but instead the value `file://./spelling_errors.md`. The file `spelling_errors.md` has Markdown content like this:

```md
## Introductin

Genes work together in context-specific networks to carry out different functions [@pmid:19104045; @doi:10.1038/ng.3259].
Variations in these genes can change their functional role and, at a higher level, affect disease-relevant biological processes [@doi:10.1038/s41467-018-06022-6].
```

Maybe this only works when the variables are defined under `tests`? It would be nice to load the content of variables regardless of the test structure (standard tests vs scenarios).
