### ISSUE TITLE
evaluateOptions are not honored if config file is in another directory

### ISSUE THREAD

**Issue by hwaxxer** [promptfoo/promptfoo#3286]
**Describe the bug**
When running `promptfoo eval -c somefolder/promptfooconfig.yaml` from a directory other than the config file’s own directory, the evaluateOptions defined in the config file (e.g. maxConcurrency: 3) are not applied during evaluation.

**To Reproduce**
1. Define a `promptfooconfig.yaml`
```yaml:promptfooconfig.yaml
providers:
  - id: openai:gpt-4o-mini

prompts:
  - "translate {{ input }} into language {{ language }}"

tests:
  - vars:
      language: French
      input: Hello world
  - vars:
      language: Spanish
      input: Where is the library?

evaluateOptions:
  maxConcurrency: 3
```
2. Run it from the same folder, eg `promptfoo eval -c promptfooconfig.yaml`
maxConcurrency is set to 3

3. Run it from some other folder, eg `promptfoo eval -c some-folder/promptfooconfig.yaml`
maxConcurrency defaults to 4

**Expected behavior**
Should be no difference where the config file resides.

**System information:**

- Promptfoo version:
0.106.0
