### ISSUE TITLE
Env variables not supported anymore in header fields

### ISSUE THREAD

**Issue by gesslinger** [promptfoo/promptfoo#3331]
I have custom providers which uses env variables in the id, the body, the header.
Till v0.104.4 everything was working. With v0.105.x the env variables in the **header** section are empty / ignored.

**To Reproduce**

Use a provider like that:

```
id: 'https://{{env.TENANT}}-{{env.APPLICATION}}.{{env.BASE_URL}}/api/{{env.ASSISTANT_API}}'
config:
  method: 'POST'
  headers:
    'Content-Type': 'application/json'
    'Cookie': 'REGION-SESSION={{ env.REGION_SESSION }}; XSRF-TOKEN={{ env.XSRF_TOKEN }}; SESSION={{ env.SESSION }};'
    'X-XSRF-TOKEN': '{{env.XSRF_TOKEN}}'
  body:
    messages: '[{"role":"user","content":"{{question}}"}]'
  responseParser: 'json'
```

All these parameters must defined in the env file. But when running a test using this provider the variables below headers are ignored and empty.

With 0.104.4 it is working
With > 0.105.x it is not working anymore.

Workaround: use 0.104.4 till it is fixed.
