### ISSUE TITLE
[Bedrock] AI21 TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by moltar** [promptfoo/promptfoo#3355]
Configuring like this:

```ts
    {
      'bedrock:ai21.jamba-1-5-large-v1:0': {
        id: 'AI21 Jamba 1.5 Large',
        config: {
          region: 'us-east-1',
          temperature: TEMPERATURE,
        },
      },
    },
```

Fails with:

> TypeError: Cannot read properties of undefined (reading '0')

Happens here:

https://github.com/promptfoo/promptfoo/blob/70c3c403b3426785616e99072c2f6c82e275b157/src/providers/bedrock.ts#L430-L434

**Comment by typpo** [comment]
I'm not able to repro with the following yaml:

```yaml
description: 'Bedrock A21 Eval'

prompts:
  - 'Write a tweet about {{topic}}'

providers:
  - id: bedrock:ai21.jamba-1-5-large-v1:0
    config:
      region: us-east-1

tests:
  - vars:
      topic: Our eco-friendly packaging
```

Can you please provide the full debug output with `--verbose`?  It would help to know what the API is actually returning.
