### ISSUE TITLE
Not all models from AWS Bedrock work as providers

### ISSUE THREAD

**Issue by PavelPolyakov** [promptfoo/promptfoo#3360]
**Describe the bug**
Not all models from `bedrock` work.
For example:
```
us.deepseek.r1-v1:0
meta.llama3-2-3b-instruct-v1:0
```
fail

**To Reproduce**
This is my config, I just tried to run against number of random models.
All models were enabled on my AWS account.
```yaml
description: 'Getting started'
prompts:
   - "What is 1+1?"

providers:
  - id: bedrock:us.anthropic.claude-3-5-sonnet-20241022-v2:0
    config:
      profile: 'bedrock'
      region: 'us-east-1'
  - id: bedrock:us.anthropic.claude-3-7-sonnet-20250219-v1:0
    config:
      profile: 'bedrock'
      region: 'us-east-1'
  - id: bedrock:us.deepseek.r1-v1:0
    config:
      profile: 'bedrock'
      region: 'us-east-1'
  - id: bedrock:meta.llama3-2-3b-instruct-v1:0
    config:
      prfile: 'bedrock'
  - id: bedrock:amazon.nova-pro-v1:0
    config:
      profile: 'bedrock'

tests:
  - assert:
      - type: contains
        value: '2'
```

**Expected behavior**
All models work

**Screenshots**

<img width="1272" alt="Image" src="https://github.com/user-attachments/assets/c7b46be6-24a5-48bc-ad8c-48a6c700d655" />

**System information:**

```
{
  "version": "0.106.3",
  "platform": {
    "os": "darwin",
    "release": "24.3.0",
    "arch": "arm64",
    "nodeVersion": "v18.19.0"
  },
  "env": {},
  "configInfo": {
    "defaultConfigPath": "/%REDACTED%/promptfoo-test/promptfooconfig.yaml",
    "configExists": true,
    "configContent": {
      "config": {
        "tags": {},
        "description": "Getting started",
        "prompts": [
          "What is 1+1?"
        ],
        "providers": [
          {
            "id": "bedrock:us.anthropic.claude-3-5-sonnet-20241022-v2:0",
            "config": {
              "profile": "bedrock",
              "region": "us-east-1"
            }
          },
          {
            "id": "bedrock:us.anthropic.claude-3-7-sonnet-20250219-v1:0",
            "config": {
              "profile": "bedrock",
              "region": "us-east-1"
            }
          },
          {
            "id": "bedrock:us.deepseek.r1-v1:0",
            "config": {
              "profile": "bedrock",
              "region": "us-east-1"
            }
          },
          {
            "id": "bedrock:meta.llama3-2-3b-instruct-v1:0",
            "config": {
              "prfile": "bedrock"
            }
          },
          {
            "id": "bedrock:amazon.nova-pro-v1:0",
            "config": {
              "profile": "bedrock"
            }
          }
        ],
        "tests": [
          {
            "assert": [
              {
                "type": "contains",
                "value": "2"
              }
            ]
          }
        ],
        "scenarios": [],
        "env": {},
        "sharing": true,
        "defaultTest": {
          "vars": {},
          "assert": [],
          "options": {},
          "metadata": {}
        },
        "outputPath": [],
        "extensions": [],
        "metadata": {}
      },
      "testSuite": {
        "description": "Getting started",
        "tags": {},
        "prompts": [
          {
            "raw": "What is 1+1?",
            "label": "What is 1+1?"
          }
        ],
        "providers": [
          {
            "env": {},
            "modelName": "us.anthropic.claude-3-5-sonnet-20241022-v2:0",
            "config": {
              "profile": "bedrock",
              "region": "us-east-1",
              "basePath": "/%REDACTED%/promptfoo-test"
            },
            "label": ""
          },
          {
            "env": {},
            "modelName": "us.anthropic.claude-3-7-sonnet-20250219-v1:0",
            "config": {
              "profile": "bedrock",
              "region": "us-east-1",
              "basePath": "/%REDACTED%/promptfoo-test"
            },
            "label": ""
          },
          {
            "env": {},
            "modelName": "us.deepseek.r1-v1:0",
            "config": {
              "profile": "bedrock",
              "region": "us-east-1",
              "basePath": "/%REDACTED%/promptfoo-test"
            },
            "label": ""
          },
          {
            "env": {},
            "modelName": "meta.llama3-2-3b-instruct-v1:0",
            "config": {
              "prfile": "bedrock",
              "basePath": "/%REDACTED%/promptfoo-test"
            },
            "label": ""
          },
          {
            "env": {},
            "modelName": "amazon.nova-pro-v1:0",
            "config": {
              "profile": "bedrock",
              "basePath": "/%REDACTED%/promptfoo-test"
            },
            "label": ""
          }
        ],
        "providerPromptMap": {
          "bedrock:us.anthropic.claude-3-5-sonnet-20241022-v2:0": [
            "What is 1+1?"
          ],
          "bedrock:us.anthropic.claude-3-7-sonnet-20250219-v1:0": [
            "What is 1+1?"
          ],
          "bedrock:us.deepseek.r1-v1:0": [
            "What is 1+1?"
          ],
          "bedrock:meta.llama3-2-3b-instruct-v1:0": [
            "What is 1+1?"
          ],
          "bedrock:amazon.nova-pro-v1:0": [
            "What is 1+1?"
          ]
        },
        "tests": [
          {
            "assert": [
              {
                "type": "contains",
                "value": "2"
              }
            ]
          }
        ],
        "scenarios": [],
        "defaultTest": {
          "metadata": {},
          "options": {},
          "vars": {},
          "assert": []
        },
        "nunjucksFilters": {},
        "extensions": []
      },
      "basePath": "/%REDACTED%/promptfoo-test"
    }
  }
}
```

- Promptfoo version: `0.106.3`

**Additional context**
