### ISSUE TITLE
Security threat. /bin/sh: 1: Syntax error due to improper character handling

### ISSUE THREAD

**Issue by emsi** [promptfoo/promptfoo#339]
When using exec provider with variable with special characters. eg:
```
prompts:
  - "{{violation}}"


providers: 
  - exec:python3 provider.py:

tests:
  - description: exploit
    vars:
      violation: "`('"
``` 

Whenever a variable contains special shell characters we might get an error like:
```
Error: Command failed: python3 provider.py "[{\"role\":\"user\",\"content\":\"`('\"}]" "{\"id\":\"exec:python3 provider.py\",\"config\":{\"basePath\":\"\"}}" "{\"vars\":{\"violation\":\"`('\"}}"
/bin/sh: 1: Syntax error: Unterminated quoted string
```

**Using shell when executing script providers is also a security threat! The provider should be executed directly (via exec call) rather that via system call  through shell.** Adding more escaping rules is not the right path as it can quickly get convoluted and either brake the passed values or leave a gap for another escaping trick.
For example if the variable is:
```
      violation: "`rm -rf /*`"
```

It will execute the `rm -rf /*` command rather than passing that to provider. This behavior is not only insecure but also inconsistent with other providers.
