### ISSUE TITLE
TogetherAI provider do not support max_tokens config

### ISSUE THREAD

**Issue by artefactop** [promptfoo/promptfoo#3442]
**Describe the bug**
I'm using TogherAI provider but the response tokens are limited to 1024. I tried to config `max_tokens` but it has no effect and it is supported in their API https://docs.together.ai/reference/chat-completions-1:
```yaml
  - id: togetherai:chat:Qwen/Qwen2.5-Coder-32B-Instruct
    config:
      temperature: 0.0
      apiKeyEnvar: TOGETHER_API_KEY
      cache: false
      max_tokens: 4096
```

**To Reproduce**
Steps to reproduce the behavior, including example Promptfoo configurations if applicable:

1. Configure togetherai provider with max_tokens greater than 1024
2. Make a call where you know the response will be greater.
3. See the response, it is cut by 1024 tokens.

**Expected behavior**
`max_tokens` config passthrough the together API

**Screenshots**
I can add it if needed.

**System information:**

```
====================================================================================================================================================================
Promptfoo Debug Information
====================================================================================================================================================================
{
  "version": "0.107.3",
  "platform": {
    "os": "darwin",
    "release": "24.3.0",
    "arch": "arm64",
    "nodeVersion": "v23.10.0"
  },
  "env": {},
  "configInfo": {
    "configExists": false,
    "configContent": null
  }
}
```

- Promptfoo version:
0.107.3

**Additional context**
As a workaround, if I set `OPENAI_MAX_TOKENS=4096` it works.
