### ISSUE TITLE
Adding AZURE_OPENAI_API_KEY in the  config.yaml file. Is it possible?

### ISSUE THREAD

**Issue by FJLopezGarcia** [promptfoo/promptfoo#348]
Is there any way to run promntfoo eval adding the Azure and OpenAI API keys in the config YAML file? i dont want to add the Keys in my environment variables. What are the option we have for this? -- Thanks  a lot

promt.txt
`
Answer the following concisely: {{message}}
`

Here my "promptfooconfig.yaml" --> addind the keys as follow since is the way used when running "promtfoo view". but is not running:
```
env:
  AZURE_OPENAI_API_KEY: XXXXXXXXXXXXXXXX
  OPENAI_API_KEY: YYYYYYYYYYYYYYYYYY
description: ''
providers:
  - id: openai:chat:gpt-3.5-turbo
    config:
      temperature: 0
      max_tokens: 128
  - id: azureopenai:chat:gpt4
    config:
      apiHost: testinstance.openai.azure.com
      temperature: 0
      max_tokens: 128
prompts:
  - prompt.txt
tests:
  - description: 'poem'
    vars:
      message: Write a poem about the sea.
    assert:
      - type: contains
        value: sea

```

![image](https://github.com/promptfoo/promptfoo/assets/6631983/9a9d0ea1-f928-464e-8adb-8b54e752a97f)

**Comment by typpo** [comment]
Hi @FJLopezGarcia,

You can add the `apiKey` property under each provider config, like so:

```yaml
providers:
  - id: openai:chat:gpt-3.5-turbo
    config:
      apiKey: abc123
      temperature: 0
      max_tokens: 128
  - id: azureopenai:chat:gpt4
    config:
      apiKey: abc123
      apiHost: testinstance.openai.azure.com
      temperature: 0
      max_tokens: 128
```

It looks like `env` config is not being passed when used in CLI.  e8170a7f0e9d4033ef219169115f6474d978f1a7 fixes this in the next release.  Thanks for opening this issue!
