### ISSUE TITLE
Does the provider support loading from files?

### ISSUE THREAD

**Issue by jojoLockLock** [promptfoo/promptfoo#349]
## Does the provider support loading from files?

my `promptfooconfig.yaml` file
```yaml
prompts: [prompt.txt]
providers:
  - id: openai:chat:gpt-3.5-turbo-0613
    config:
      functions:
        [
          {
            'name': 'get_current_weather',
            'description': 'Get the current weather in a given location',
            'parameters':
              {
                'type': 'object',
                'properties':
                  {
                    'location':
                      {
                        'type': 'string',
                        'description': 'The city and state, e.g. San Francisco, CA',
                      },
                    'unit': { 'type': 'string', 'enum': ['celsius', 'fahrenheit'] },
                  },
                'required': ['location'],
              },
          },
        ]
```

I want to have this grammar

**promptfooconfig.yaml**

```yaml
prompts: [prompt.txt]
providers:
  - id: openai:chat:gpt-3.5-turbo-0613
    config:
      functions:
         - file://./get_current_weather.json
```

**get_current_weather.json**

```json 
{
    'name': 'get_current_weather',
    'description': 'Get the current weather in a given location',
    'parameters':
      {
        'type': 'object',
        'properties':
          {
            'location':
              {
                'type': 'string',
                'description': 'The city and state, e.g. San Francisco, CA',
              },
            'unit': { 'type': 'string', 'enum': ['celsius', 'fahrenheit'] },
          },
        'required': ['location'],
 }
```
