### ISSUE TITLE
Add provider for Together AI

### ISSUE THREAD

**Issue by miltondp** [promptfoo/promptfoo#351]
Together AI is a popular cloud provider to run LLMs: https://www.together.ai/

**Comment by miltondp** [comment]
Hm, it looks like we can use the OpenAI's environment variable name with the Together AI API token: https://docs.together.ai/docs

**Comment by typpo** [comment]
Based on their documentation, something like this should work although I haven't tried it myself:

```yaml
providers:
  - id: openai:chat:mistralai/Mixtral-8x7B-Instruct-v0.1
    config:
      apiBaseUrl: https://api.together.xyz
      apiKey: xxx    # can also set OPENAI_API_KEY envar
```
Let me know how that works for you and I can add it to the documentation.
