### ISSUE TITLE
Python assert do not work

### ISSUE THREAD

**Issue by miltondp** [promptfoo/promptfoo#352]
After upgrading to version 0.33.1, no Python asserts work anymore. I get the following error for all python asserts, single and multiline ones:

```
Python code execution failed: Python assertion must return a boolean, number, or {pass, score, reason} object
```

Some python asserts that I have in the config file:

```yaml
          # Starts with capital letter
          - type: python
            value: output.strip()[0].isupper()

          - type: python
            value: |
              paragraph = context["vars"]["paragraph"]
              paragraph_words = len(paragraph.strip().split())
              output_words = len(output.strip().split())
              response = (output_words > 0.5 * paragraph_words) and (output_words < 1.6 * paragraph_words)
              print(response)
```

Using version 0.32 works as expected.
