### ISSUE TITLE
factuality and llm-rubric with Anthropic model causing bug when used at same time

### ISSUE THREAD

**Issue by dhodun** [promptfoo/promptfoo#3623]
**Describe the bug**
When `llm-rubric` and `factuality` provider are both on with an ANTHROPIC_API_KEY, the `resp.output` returns an `Object` instead of a `string`, causing eval to fail.

**To Reproduce**
Steps to reproduce the behavior, including example Promptfoo configurations if applicable:

eval this config:

```yaml
# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: "Testing Claude Sonnet 3.7 with factuality and llm-rubric"

providers:
  - id: anthropic:messages:claude-3-7-sonnet-20250219
    config:
      max_tokens: 1000

prompts:
  - "{{input}}"

tests:
  - vars:
      input: "What is the capital of California?"
    assert:
      - type: factuality
        value: "The capital of California is Sacramento."
      - type: llm-rubric
        value: "Based on your internal knowledge, is the answer right?"

```

If you remove `llm-rubric` the `factuality` providers operates as expected.

**Expected behavior**
Both tests should be run

**Screenshots**

<img width="1281" alt="Image" src="https://github.com/user-attachments/assets/4aca225f-f73c-4f88-b540-c96a45c1f3cd" />

`resp.output` is of type `Object` instead of `string` here: https://github.com/promptfoo/promptfoo/blob/3e6b2eeb3c14c6f825dd2f8546b84b93a511e898/src/matchers.ts#L448

**System information:**

If possible, please output the results of `promptfoo debug` and paste the output here.

- Promptfoo version: 0.109.0
