### ISSUE TITLE
`promptfoo share` ignores `sharing.apiBaseUrl` and `sharing.appBaseUrl` in `promptfooconfig.yaml`

### ISSUE THREAD

**Issue by Dobiasd** [promptfoo/promptfoo#3667]
Given the following in `promptfooconfig.yaml` (as described in [the docs](https://www.promptfoo.dev/docs/usage/sharing/#advanced-self-hosted-sharing)):

```yaml
sharing:
  apiBaseUrl: https://doesnotexist.google.com
  appBaseUrl: https://doesnotexisteither.google.com
```

and running

```bash
promptfoo share
```

I get

```
» You need to have a cloud account to securely share your results.

1. Please go to https://promptfoo.app to sign up or log in.
2. Follow the instructions at https://promptfoo.app/welcome to login to the command line.
3. Run promptfoo share
```

So it looks like promptfoo is ignoring `sharing.apiBaseUrl` and `sharing.appBaseUrl` from `promptfooconfig.yaml`.

I would expect to get the same error as when doing this:

```bash
PROMPTFOO_REMOTE_API_BASE_URL=https://doesnotexist.google.com PROMPTFOO_REMOTE_APP_BASE_URL=https://doesnotexisteither.google.com 
```

which is:

```
[...]
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'doesnotexist.google.com'
[...]
```

---

I've confirmed that my `promptfooconfig.yaml` is really parsed by adding some nonsense to it:

```yaml
sharing:
  apiBaseUrl: https://doesnotexist.google.com
  appBaseUrl: https://doesnotexisteither.google.com
asdasd
```

and running

```bash
promptfoo share
```

again:

```
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key (5:1)
```

---

Version used:

```bash
promptfoo --version
```

```
0.109.1
```
