### ISSUE TITLE
huggingface dataset wrong test case count

### ISSUE THREAD

**Issue by colorzhang** [promptfoo/promptfoo#3685]
**Describe the bug**

run the huggingface dataset example. I got 4 test cases with one row dataset. each test case has one choice. 
expected 1 test case with choices column has 4 options.

```yaml
description: 'DeepSeek-R1 vs o1 comparison on MMLU reasoning tasks'

prompts:
  - prompts.py:prompt

providers:
  - bedrock:amazon.nova-lite-v1:0
  # - bedrock:amazon.nova-pro-v1:0
  # - bedrock:us.anthropic.claude-3-5-sonnet-20241022-v2:0
  # - deepseek:deepseek-reasoner

defaultTest:
  assert:
    # Inference should complete within 60 seconds
    - type: latency
      threshold: 60000
    # Check for step-by-step reasoning
    # - type: llm-rubric
      # value: Response must include clear step-by-step reasoning
    # Check that it ends with a clear answer choice
    - type: regex
      value: "Therefore, the answer is {{answer}}."

tests:
  # Load MMLU test sets for reasoning-heavy subjects
  # - huggingface://datasets/cais/mmlu?split=test&subset=abstract_algebra&config=abstract_algebra&limit=10
  # Optionally load other subjects
  # - huggingface://datasets/cais/mmlu?split=test&subset=formal_logic&config=formal_logic&limit=10
  # - huggingface://datasets/cais/mmlu?split=test&subset=high_school_mathematics&config=high_school_mathematics&limit=10
  # - huggingface://datasets/cais/mmlu?split=test&subset=college_mathematics&config=college_mathematics&limit=10
  # - huggingface://datasets/cais/mmlu?split=test&subset=logical_fallacies&config=logical_fallacies&limit=10
  - huggingface://datasets/cais/mmlu?split=test&subset=machine_learning&config=machine_learning&limit=1

evaluateOptions.maxConcurrency: 1
```

**Expected behavior**
1 test case

**Screenshots**

![Image](https://github.com/user-attachments/assets/b4af0c14-b646-436f-80be-165529cb543b)

**System information:**
node 22

- Promptfoo version: prompt 0.109
