### ISSUE TITLE
Reading prompts, providers and assertions from environment variables

### ISSUE THREAD

**Issue by merveozbay** [promptfoo/promptfoo#3691]
Hello,

Is it possible to read paths from an environment variable in the promptfooconfig.yaml?
As you can see in the following config.yaml, I read prompt, provider, assertions from path "../../test". I want to read this path from an environment variable and then concatenate with the file name like '{{env.TEST_PATH}}'+'\prompt.txt'. Or I'm also open to any other suggestions. 

```yaml
description: 'test'

prompts: 
  - ../../test/prompt.txt

providers:
  - ../../test/custom_provider.js

defaultTest:
  options:
    provider: file://../../../test/model_provider.yaml
tests:

  - vars:
      question: What is the capital of France?
    assert:
      - type: python
        value: file://../../test/custom_assert.py

```

Thank you
