### ISSUE TITLE
o4-mini is supported only on responses api and not chat completions

### ISSUE THREAD

**Issue by OrGivati** [promptfoo/promptfoo#3738]
**Describe the bug**
o4-mini is not working with yaml configuration when using `openai:o4-mini` or `openai:chat:o4-mini`.
It is always throws an exception in openai API about using `max_tokens` is not supported, use `max_completion_tokens`

**To Reproduce**
Steps to reproduce the behavior, including example Promptfoo configurations if applicable:

use this configuration:
```
  - id: openai:o4-mini // or openai:chat:o4-mini
    label: 'o4-medium'
    config:
      isReasoningModel: true
      max_completion_tokens: 60000
      reasoning_effort: medium
      response_format:
        type: json_object
```

And you will get an error:
```
API error: 400 Bad Request
{"error":{"message":"Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.","type":"invalid_request_error","param":"max_tokens","code":"unsupported_parameter"}}
```

**Expected behavior**
Expect that max_tokens not be sent and the request to work

**Screenshots**

<img width="513" alt="Image" src="https://github.com/user-attachments/assets/817fc98a-0d97-47f1-be9f-df0f38c0bcf1" />

**System information:**
```
"version": "0.110.0",
  "platform": {
    "os": "darwin",
    "release": "24.4.0",
    "arch": "arm64",
    "nodeVersion": "v22.14.0"
  },

```
- Promptfoo version: 0.110.0
