### ISSUE TITLE
Truncated Test Name in CLI Progress Bar

### ISSUE THREAD

**Issue by arsena** [promptfoo/promptfoo#3797]
**Describe the bug**
The CLI progress bar doesn't display enough characters to see which test is being run.

**To Reproduce**
Run promptfoo eval

Sample Configuration:
```YAML
description: "Promptfoo test cases for different stories"
prompts:
  - ./test/promptfoo/common/prompts.mjs:a
  - ./test/promptfoo/common/prompts.mjs:b
providers:
  - id: file://./test/promptfoo/providers/MockAppProvider.mjs
    label: "MockApp"
defaultTest:
  options:
    provider:
      id: file://./test/promptfoo/providers/CustomGPTProvider.mjs
      label: "CustomGPT"
      config:
        api_version: "2024-02-01"
        chat_completions_model: "gpt-4o"
        embeddings_model: "text-embedding-ada-002"
        temperature: 0.7
        max_tokens: 2000
  assert:
    - type: answer-relevance
      threshold: 0.7
tests:
  - file://./test/promptfoo/*-stories.*
outputPath: ./test-reports/promptfoo/promptfoo-result.json
evaluateOptions:
  maxConcurrency: 8
```

**Expected behavior**
Expected more characters reserved for displaying variables, because our vars contain the input differences.  Therefor displaying more vars would indicate better which test is being run.

**Screenshots**

<img width="848" alt="Image" src="https://github.com/user-attachments/assets/d82e0487-6370-4043-a0cc-81e808bd154b" />

**System information:**

- Promptfoo version: 0.107.7
