### ISSUE TITLE
AzureOpenAI and ClientSecretCredential

### ISSUE THREAD

**Issue by FJLopezGarcia** [promptfoo/promptfoo#382]
Hi.
I need to use AzureOpenAI with ClientSecretCredential to authenticate.
then, I need to pass to the ClientSecretCredential a tenant_id, client_id, client_secret, authority and scope tp get a Token.
![image](https://github.com/promptfoo/promptfoo/assets/6631983/4f2de3bf-79c9-43ce-92a4-d4007ce33e18)

I also need to pass to the LLM the 
- deployment_name
- model_name
- openai_api_base
- openai_api_version
- openai_api_key
- openai_api_type
- temperature
- max_tokens

How I should proceed to setup my Azure provider in my YML? should i need to create a custom provider? is there any example passisng all this parameters?

**Comment by typpo** [comment]
Right now you would have to generate the token manually and pass it in the YML or as an environment variable, or use a [custom script](https://promptfoo.dev/docs/providers/custom-script) (python) or [custom ApiProvider](https://promptfoo.dev/docs/providers/custom-api) (javascript).

I'll look into how we can support ClientSecretCredential for Azure natively in promptfoo...

**Comment by typpo** [comment]
#389 adds support for Azure ClientSecretCredential flow

**Comment by typpo** [comment]
Support for ClientSecretCredential landed in 0.35.1

**Comment by FJLopezGarcia** [comment]
Hi @typpo 
hope you are doing fine!!
I am playing with ClientSecretCredential using promptfoo 0.35.1 version and I have some issues;

Based on my AvureOpenAI configuration, I need to pass a "openai_api_type" and a "openai_api_version". Are these two parameters setup in the Azure ClientSecretCredential flow implemented? I am not able to see them in #389 

Here you have my provider configuration:

```
providers:
  - id: azureopenai:chat:gpt4
    config:
      apiHost: cs-oai-XXXX-genai35dev.openai.azure.com
      azureTenantId: e0793d39-XXXX-XXXXX-b129-198edd916feb
      azureClientId: fb2bf190-33f1-XXXX-XXXXX-0dd94e106797
      azureClientSecret: hje8Q~XXXXX-RwHlTS2p-IILVh.t.XXXXXX
      deploymentName: csdep-XXXXXX-gpt-4
      deployment_id: gpt-4
      #openai_api_type="azure_ad", 
      #openai_api_version=2023-09-01-preview
      temperature: 0
      max_tokens: 50
```
And this is the error i have running the eval (where the preview is not the correct one, I need to pass "2023-09-01-preview") 

`API call error: Error: Request failed after 4 retries: request to https://xcs-oai-25730602-genai35dev.openai.azure.com/openai/deployments/gpt4/chat/completions?api-version=2023-07-01-preview failed, reason: getaddrinfo ENOTFOUND xcs-oai-25730602-genai35dev.openai.azure.com`

Thanks!
