### ISSUE TITLE
How to escape the `{{ placeholder }}`?

### ISSUE THREAD

**Issue by bhky** [promptfoo/promptfoo#3855]
Hello team!
Thank you very much for the awesome software!

I have a question regarding placeholders.

In my use case I need to keep the string pattern `{{ something }}` as is, but unfortunately this collides with the Promptfoo placeholders. Is there a way to escape it?

**Comment by Dobiasd** [comment]
Augmenting this with a minimal example:

I'd like to give this prompt to the LLM: `Output this exact string:{{some_string}}"`, i.e., `{{some_string}}` shall not be replaced by Promptfoo with some variable, but be verbatim instead.

My current attempt looks as follows:


```yaml
description: "test_2025-04-30_003"

prompts:
  - "Output this exact string:{{ '{{some_string}}' }}"

providers:
  - "openai:gpt-4o-mini"

tests:
    assert:
      - type: contains-all
        value: "{{ '{{some_string}}' }}"
```

But the output of

```bash
promptfoo eval --verbose
```

shows this:

```
[chat.js:107] Calling OpenAI API: {"model":"gpt-4o-mini","messages":[{"role":"user","content":"Output this exact string:"}],"max_tokens":1024}
```

So the `{{some_string}}` is missing in the message.

**Comment by Dobiasd** [comment]
Thanks for the response! But that's exactly what I already tried. Or am I missing something?

**Comment by typpo** [comment]
Hmm sorry about that and thank you for the repro.  This is something we'll have to look into.  

BTW, you can set the `PROMPTFOO_DISABLE_TEMPLATING` environment variable to completely disable templating - not sure if it helps you here.

**Comment by will-holley** [comment]
Do the ergonomics of

```yaml
prompts:
  - "Output this exact string:{% raw %}{{some_string}}{% endraw %}"

providers:
  - "openai:gpt-4o-mini"

tests:
  - assert:
      - type: contains
        value: "{% raw %}{{some_string}}{% endraw %}"
```

work for you, @bhky / @Dobiasd?  Using [`raw`](https://mozilla.github.io/nunjucks/templating.html#raw) solves your escaping problem.
