### ISSUE TITLE
Providing "completion" to custom factuality prompt

### ISSUE THREAD

**Issue by ghadialhajj** [promptfoo/promptfoo#3871]
I need to change the default factuality prompt and I tried doing that by modifying the prompt as suggested [here](https://www.promptfoo.dev/docs/guides/factuality-eval/#customizing-the-evaluation-prompt). It also says in the docs:

> You must implement the following template variables:
> 
> {{input}}: The original prompt/question
> {{ideal}}: The reference answer (from the value field)
> {{completion}}: The LLM's actual response

I could pass input and ideal as part of `vars` since they are static and no model calls are involved, but I'm unable to do that. One way of course, would be to manually call the model when populating the `test_cases` dict, but I'm wondering if there is a way to keep that (i.e. the API call to the defined model) automated instead of doing that explicitly. I assume that the library behind the scenes calls whatever is provided in options[provider][id].

I just want to use the good old
```
{
    'type': 'factuality',
    'value': correct_answer,
    'metric': 'some_name'
},
```

**Comment by billybonks** [comment]
Just to make sure we are on the same page

for a factuality test like this

```
providers:
  - openai:gpt-4.1-mini
prompts:
  - |
    Please answer the following question accurately:
    Question: What is the capital of {{location}}?
tests:
  - vars:
      location: California
    assert:
      - type: factuality
        value: The capital of California is Sacramento
```

what will happen is there will be a llm call being made 

```
....
      Question:  Please answer the following question accurately:\nQuestion: What is the capital of California?\n\n
      Reference answer: The capital of California is Sacramento
      Submitted answer: <What ever the llm responded with>
....
```

so the  Reference answer and Question are static in the example. How does your example differ that you are unable to do have these parts be static or am i missing something.

**Comment by mldangelo** [comment]
Hey @ghadialhajj - this should be working now!

The issue was that `rubricPrompt` was being rendered before the `{{completion}}` variable was available. We fixed this in #5340 by deferring the prompt rendering until after the LLM response comes back.

You can now use custom factuality prompts like:

```yaml
defaultTest:
  options:
    rubricPrompt: |
      Input: {{input}}
      Reference: {{ideal}}
      Completion: {{completion}}

      Evaluate the factual consistency...
```

All three variables get populated automatically - no need to make manual API calls.

Docs were also updated to clarify this: https://www.promptfoo.dev/docs/configuration/expected-outputs/model-graded/factuality/#customizing-the-prompt

Let me know if you run into any issues!
