### ISSUE TITLE
llm-rubric with JSON structured output : The output '[object Object]'

### ISSUE THREAD

**Issue by Jeremy-Simply-Stupid-Software** [promptfoo/promptfoo#4014]
**Describe the bug**

After updating to the latest version of Promptfoo, `llm-rubric` tests no longer correctly process JSON outputs when they are structured using `response_mime_type: "application/json"` and a corresponding `response_schema`. This functionality was working as expected in version 0.106.3, which was used prior to the update.

**To Reproduce**

Steps to reproduce the behavior, including example Promptfoo configurations if applicable:

1.  Configure a provider to output JSON with a specific schema:
    ```yaml
    providers:
      - id: my-provider
        # ... other provider config
        config:
          response_mime_type: "application/json"
          response_schema:
            type: "object"
            properties:
              key1: { "type": "string" }
              key2: { "type": "number" }
              # ... other properties
    ```

2.  Verify that the output is valid JSON and conforms to the schema using an `is-json` assertion. This test passes correctly:
    ```yaml
    tests:
      - asserts:
          - type: is-json
            value: file://schemas/myschema.json # Assumes myschema.json matches the provider's response_schema
    ```

3.  Attempt to use an `llm-rubric` assertion with the JSON output from the same provider:
    ```yaml
    tests:
      - asserts:
          - type: llm-rubric
            value: "The output should contain relevant information about X and Y."
            # ... other llm-rubric parameters
    ```
    The test fails with an error message similar to:
    `The output '[object Object]' does not provide any information on...`

    This error indicates that `llm-rubric` is receiving the string representation `[object Object]` instead of the parsed JSON object, preventing it from correctly evaluating the content.

**Expected behavior**

The JSON object output from the provider should be correctly parsed and made available as input to `llm-rubric` assertions, allowing the rubric to evaluate the content of the JSON.

**System information:**

-   Promptfoo version: 0.112.6 (reported as "latest" at the time of issue creation)

**Additional context**

As a workaround, I attempted to use the `transform` option within the assertion:
```yaml
asserts:
  - type: llm-rubric
    value: "..."
    options:
      transform: JSON.stringify(output)
```
But now i'm not able to verify my output schema, and output is not fully readable as json.
