### ISSUE TITLE
why openai is requested here and how to change it to deepseek

### ISSUE THREAD

**Issue by blu3sh0rk** [promptfoo/promptfoo#4091]
why openai is requested here and how to change it to deepseek

**Comment by blu3sh0rk** [comment]
![Image](https://github.com/user-attachments/assets/0b0053c9-a30f-4055-a54b-bd5ca6fede0d)

**Comment by mldangelo** [comment]
You can override the redteam provider in your config with 

```yaml
redteam: 
  plugins: ...
  provider: `openouter:deepseek-r1`
```
 for example. Who is hosting deepseek for you?

**Comment by blu3sh0rk** [comment]
The redteam part has been modified to the following but still reports an error. Could you please tell me what the problem is?
```
redteam:
  purpose: 'The objective of the application is: Electric Power Knowledge Assistant'
  plugins:
    - id: ascii-smuggling  # Tests vulnerability to Unicode tag-based instruction smuggling attacks
  strategies:
    - id: jailbreak  # Single-shot optimization of safety bypass techniques
    - id: jailbreak:composite  # Combines multiple jailbreak techniques for enhanced effectiveness
  providers:
  - id: deepseek:deepseek-chat
    config:
      temperature: 0.7
      max_tokens: 4000
      apiKey: sk-xxx
```

**Comment by blu3sh0rk** [comment]
> You can override the redteam provider in your config with
> 
> redteam: 
>   plugins: ...
>   provider: `openouter:deepseek-r1`
> for example. Who is hosting deepseek for you?

base_url:https://api.siliconflow.cn

**Comment by billybonks** [comment]
Hi @blu3sh0rk could you run your evaluation with the -v command `promptfoo redteam run -v --force --no-progress-bar` and paste the output so its easier to see where the error might be occurring.

**Comment by mldangelo** [comment]
@blu3sh0rk - this question was answered above. You can override the redteam provider in your config with the `provider` key under `redteam`.

For DeepSeek via SiliconFlow:

```yaml
redteam:
  plugins: [...]
  provider:
    id: openai:deepseek-chat
    config:
      apiBaseUrl: https://api.siliconflow.cn/v1
      apiKey: your-key
```

Closing as answered. Feel free to open a new issue if you're still having trouble with the configuration.
