### ISSUE TITLE
{{env.variable}} does not work in prompts (question / answer)

### ISSUE THREAD

**Issue by gesslinger** [promptfoo/promptfoo#4143]
I want to use env variables in my prompt. Currently  in the testrun it works like an escaped variable. When I run `promptfoo view` it seems converted to the variable value, but not in all cases

**To Reproduce**

This is my yml file for the test.

```
tests:
  - vars:
      question: 'How is the wheather at location {{env.LOCATION}}?'
    assert:
      - type: llm-rubric
        value: 'The wheather is {{env.WHEATHER}}'
```

env.LOCATION=Karlsruhe
env.WHEATHER=sunny

**Expected behavior**

It should resolve the environment variables and use the values of it - in the question and also in the answer.

**Screenshots**

In `promptfoo view` it shows, that it cannot resolve the variable in the prompt - but it seems in the failure description.
![Image](https://github.com/user-attachments/assets/8afb3875-cf75-4121-a0a9-a832a3c50b33)

When I look into the details, it also looks weird:

![Image](https://github.com/user-attachments/assets/830f4b78-a90b-443f-be09-f480e1993dbf)

**System information:**

```
  "version": "0.113.2",
  "platform": {
    "os": "win32",
    "release": "10.0.19045",
    "arch": "x64",
    "nodeVersion": "v22.14.0"
  },
```
