### ISSUE TITLE
Cannot set `response_format` to external file with OpenAiResponsesProvider

### ISSUE THREAD

**Issue by jennkao** [promptfoo/promptfoo#4148]
**Describe the bug**
The `openai-structured-output` [example](https://github.com/promptfoo/promptfoo/blob/main/examples/openai-structured-output/promptfooconfig.responses.yaml) seems to suggest that passing an external json schema file as the `response_format` is supported for the Responses API. However the logs in openai seems to suggest that  `response_format` is always `text`. Is this supported yet, or am I using this incorrectly?

I am able to specify the schema properly when using the inline schema format.

Thanks! 

**To Reproduce**
External file as response_format
```
providers:
  - id: openai:responses:o3
    config:
      response_format: file://response_format.json
```

Inline response_format
```
providers:
  - id: openai:responses:o3
    config:
      response_format:
        type: json_schema
        json_schema:
          name: example
          strict: true
          schema:
            type: object
            properties:
              rows:
                type: array
                items:
                  type: array
                  items:
                    type: string
            additionalProperties: false
            required:
              - rows
```

- Promptfoo version: 0.113.2
