### ISSUE TITLE
How to do red teaming evaluation with different language?

### ISSUE THREAD

**Issue by FaceBasin** [promptfoo/promptfoo#4207]
I walked through the doc and change add a line to the YAML file: 

```
redteam:
     language: 'Chinese'
```

However the prompts generated are still in English and feedback results are in English too. Do you have some idea how to solve this problem so that I want most prompts and response in the report are in Chinese, thank you in advance!

- Promptfoo version: 0.112.4

**Comment by Mantej-Singh** [comment]
Try this 

```
  strategies:
    - jailbreak
    - prompt-injection
    - id: multilingual
      config:
        languages: ['en', 'es', 'fr','cn']  # Testing multilingual capabilities
```
