### ISSUE TITLE
Deepseek-R1-0528 is here

### ISSUE THREAD

**Issue by mpasternak** [promptfoo/promptfoo#4235]
**Is your feature request related to a problem? Please describe.**
https://api-docs.deepseek.com/news/news250528

**Describe the solution you'd like**
Please add this model to propmtfoo. 

**Describe alternatives you've considered**
Not having the latest Deepseek in promptfoo -- unacceptable :-)

**Comment by mldangelo** [comment]
Hi @mpasternak -  DeepSeek-R1-0528 is already fully supported in promptfoo through the deepseek: provider. DeepSeek uses stable API aliases, so `deepseek-reasoner` automatically points to the latest DeepSeek-R1-0528 model behind the scenes.

```yaml
providers:
  - id: deepseek:deepseek-reasoner
    config:
      max_tokens: 8000
      showThinking: true  # Shows the reasoning process
```

I'm going to update the docs to clarify! Please let me know if you'd like to see it in any other inference providers too.
