### ISSUE TITLE
Provider-level xfail setting

### ISSUE THREAD

**Issue by yanirs** [promptfoo/promptfoo#4261]
**Is your feature request related to a problem? Please describe.**<br>I've taken over an eval suite that is partly failing and I want to get it running in CI. Failure causes are varied, but some appear to come from changes to the grader and promptfoo. I don't know exactly what settings were used originally. To move forward, it'd be useful to mark certain assertions as expected to fail for specific providers, and then fix things incrementally.

Also, I think that this sort of setting would be useful in general as a way to document provider choice: If evals are failing for provider X and passing for provider Y, it'd be great to assert that this remains the case when the eval suite is rerun.

**Describe the solution you'd like**<br>As I want the full suite to be green in CI, it'd be great to be able to mark assertions as expected to fail for specific providers, in the style of [pytest's xfail](<https://docs.pytest.org/en/stable/how-to/skipping.html>) or the [equivalent jest feature](<https://github.com/jestjs/jest/issues/4627>).

**Describe alternatives you've considered**<br>The main alternative I can think of is to parse/query the outputs and implement my own solution.

However, I'm new to promptfoo, so I'm missing something obvious I'd love to hear about it.

**Comment by immu4989** [comment]
@yanirs — flagging interest in tackling this since it has the `help-wanted` label and the use case (incremental green-CI under provider drift) is real for a lot of teams. Before writing code, wanted to surface schema options because the design space is broader than typical bug fixes here, and the right shape depends on promptfoo conventions I'd like a maintainer steer on.

**Semantics, briefly:** an assertion marked xfail for specific providers is scored as `xfailed` (doesn't break CI) when it fails on those providers. Unexpected passes (xpassed) are either ignored or warned about depending on `strict`, mirroring [pytest's xfail](https://docs.pytest.org/en/stable/how-to/skipping.html#xfail-mark-test-functions-as-expected-to-fail).

**Three schema options:**

**A — Per-assertion `xfail` block** (pytest-aligned, most granular):

```yaml
tests:
  - vars: { ... }
    assert:
      - type: llm-rubric
        value: "Response should be polite"
        xfail:
          providers: ['openai:gpt-3.5-turbo']
          reason: "Known rude on this model"
          strict: false
```

**B — Per-test `xfail` list** (simpler, less granular — applies to all assertions on the test):

```yaml
tests:
  - vars: { ... }
    assert: [ ... ]
    xfail:
      - provider: openai:gpt-3.5-turbo
        reason: "Known to fail on this model"
```

**C — Top-level `xfail` matrix** (decouples from test definitions; easier to audit, harder to keep in sync):

```yaml
xfail:
  - test: "<test-id-or-description>"
    provider: openai:gpt-3.5-turbo
    assertion: 0
    reason: "..."
```

**Maintainer questions (happy to wait for steer):**

1. **Which shape fits promptfoo's config conventions?** My instinct is A — co-locates the expectation with the assertion it modifies and matches the pytest reference @yanirs cited.
2. **Provider matching — exact string, glob (`'openai:*'`), or both?**
3. **Default `strict` to false (pytest convention) or true (safer for CI)?**
4. **Anything in the existing config that already does this** that I'm missing? @yanirs flagged that possibility in the original issue.

If any of this is already in progress or off the table, happy to step aside or pivot.
