### ISSUE TITLE
Https concatenation issue

### ISSUE THREAD

**Issue by theodelobelle** [promptfoo/promptfoo#440]
Hi again, i just wanted to share that i had issues to call Azure OpenAI model cause i was filling the yaml like this :
```yaml
providers:
  - id: azureopenai:chat:gpt-35-deployement-name
    config:
      apiHost: https://apiAdress.azure.com
```

but  on execute it prefill the apiHost with an **https://**, giving 

>https://https://apiAdress.azure.com

instead of : 

>https://apiAdress.azure.com

Is it possible to implement a basic test (constains "https"...), to prevent any new user wasting time to detect this double https concatenation.

I know this is a dumb trap, i just need to readcarefully but when we copy URL from azure there is already the https. 

No one would thing to remove this https when copy pasting 😄 

Thanks
