### ISSUE TITLE
Feature Request: Gemini api (generative language api) support

### ISSUE THREAD

**Issue by mehnoorsiddiqui** [promptfoo/promptfoo#444]
Google offers the [Gemini API as a standalone API ](https://ai.google.dev/docs/gemini_api_overview)that only requires an API key, instead of complex authentication as needed in Gemini via Vertex AI. Anyone who does not have a Google Cloud account can easily access this API without using a credit card.

Although both APIs apparently offer the same model, in my experiments with models, the results differ. Therefore, I would like to test the standalone Gemini API using PromptFoo. This feature will hep developers using this version of gemini seamlessly.

**Comment by typpo** [comment]
Hi @mehnoorsiddiqui,

Thanks for pointing this out.  #445 updates the existing provider for Google's standalone API with Gemini support.  It will be in the next release published tonight.  You can use it like so:

```yaml
prompts:
  - "Write a short tweet about {{topic}}"

providers:
  - palm:gemini-pro

tests:
  - vars:
      topic: bananas
```

(and set the `PALM_API_KEY` environment variable)

**Comment by typpo** [comment]
This is part of v0.39.1

**Comment by typpo** [comment]
promptfoo doesn't load an .env file - you will have to actually set the variable in your environment

**Comment by mehnoorsiddiqui** [comment]
Thanks @typpo now i am not getting any authentication errors. But I am unable to set config as I was doing for the gemini vertex API. Promptfoo is working without config but with config facing the following error:
![image](https://github.com/promptfoo/promptfoo/assets/57288492/13ac6a43-ce70-4afc-bdd3-a5e12dd0d577)

I am setting the config like below:

```
providers:
  - id: google:gemini-pro   
    config:
      temperature: 0
      topP: 1
      
```
