### ISSUE TITLE
defaultTest to override embedding provider is not working

### ISSUE THREAD

**Issue by wobrien-pronetx** [promptfoo/promptfoo#4478]
**Describe the bug**
When adding options to provide an embedding provider to override, an error is displayed. 

Error: Test case must contain one of the following properties: assert, vars, options, metadata, provider, providerOutput, threshold.

Instead got:
```json
{
  "defaultTest": {
    "options": {
      "provider": {
        "embedding": {
          "id": "bedrock:embeddings:amazon.titan-embed-text-v2:0",
          "config": {
            "profile": "ptx-master",
            "region": "us-west-2"
          }
        }
      }
    }
  }
}
```

**To Reproduce**
Add the following to config:

```yaml
defaultTest:
  options:
    provider:
      embedding:
        id: bedrock:embeddings:amazon.titan-embed-text-v2:0
        config:
          region: us-east-1
```

**Expected behavior**
The default embedding provider for tests using embeddings should be overridden

- Promptfoo version: 0.114.7

**Comment by will-holley** [comment]
Can you share your full config?

**Comment by wobrien-pronetx** [comment]
defaultTest:
  options:
    provider:
      embedding:
        id: bedrock:embeddings:amazon.titan-embed-text-v2:0
        config:
          region: us-east-1description: 'the prompt generated by the script, ****PROMPT_DESCRIPTION****'
env: {}
prompts:
  - file://original-prompt.yaml
  - file://prompt-update-v1.yaml
providers:
  - id: 'file://../../promptfooProviders/qic_promptfoo_provider.py'
    label: 'qic provider'
    config:
      profile: 'ptx-master'
      region: 'us-west-2'
      assistantId: '067c9e25-7189-4fa5-ad36-3b9e240c910f'


scenarios: []
tests: file://tests.yaml
writeLatestResults: true
sharing: true

**Comment by mldangelo** [comment]
Hi @wobrien-pronetx,

Thanks for reporting this issue! You encountered a bug that was preventing `defaultTest.options.provider.embedding` from working correctly.

This was **fixed in PR #4732** (merged July 26, 2025) which specifically addressed your report. The fix allows `defaultTest` to contain partial test case properties like embedding provider overrides.

**Additional improvements:**
- PR #5348 (merged Aug 25, 2025) - Further improved `defaultTest.provider` handling
- PR #5931 (merged Oct 15, 2025) - Added full support for `defaultTest.options.provider` with model-graded assertions

**Your config should now work correctly:**
```yaml
defaultTest:
  options:
    provider:
      embedding:
        id: bedrock:embeddings:amazon.titan-embed-text-v2:0
        config:
          region: us-east-1

providers:
  - id: file://../../promptfooProviders/qic_promptfoo_provider.py
    label: qic provider

tests: file://tests.yaml
```

Please update to the latest version:
```bash
npm install -g promptfoo@latest
```

See the [Google provider docs](https://www.promptfoo.dev/docs/providers/google#overriding-providers) for more examples of provider overrides.

If you're still experiencing issues after updating, feel free to comment or re-open.

Thanks!
