### ISSUE TITLE
Promptfoo does not escape characters in HTML reports

### ISSUE THREAD

**Issue by beroal** [promptfoo/promptfoo#4550]
**Describe the bug**
If a prompt contains a character that has special meaning in HTML (for example, `<`), promptfoo copies this character into HTML reports verbatim.

**To Reproduce**

Create the file “a.yaml”:
```yaml
# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

description: "test"

prompts:
  - 'Is 1<2?'

providers:
  - "openai:gpt-4.1-nano"

tests:
  - vars:
      a: b
```

Generate an HTML report:
```bash
promptfoo eval -c a.yaml -o a.html
```

The file “a.html” will contain
```
<th>[openai:gpt-4.1-nano] Is 1<2?</th>
```
This is invalid HTML.

**Expected behavior**
The file “a.html” contains
```html
<th>[openai:gpt-4.1-nano] Is 1&lt;2?</th>
```

**System information:**

```
=====================================================================================================================================================================================================================================
Promptfoo Debug Information
=====================================================================================================================================================================================================================================
{
  "version": "0.115.1",
  "platform": {
    "os": "linux",
    "release": "6.14.10-arch1-1",
    "arch": "x64",
    "nodeVersion": "v24.1.0"
  },
  "env": {},
  "configInfo": {
    "configExists": false,
    "configContent": null
  }
}
=====================================================================================================================================================================================================================================
```

- Promptfoo version: 0.115.1
