### ISSUE TITLE
Simulated-user provider does not pass vars/context to custom provider calls

### ISSUE THREAD

**Issue by ossamakhiar** [promptfoo/promptfoo#4649]
**Is your feature request related to a problem? Please describe.**
I'm trying to use the `promptfoo:simulated-user` provider to simulate multi-turn conversations while routing responses through my custom Python provider. However, `vars` defined in the test (like `workflow_id`, or instructions) are not passed into the provider’s `context`. Normally, these are available in `context["vars"]` during single-turn tests, but they are missing entirely in multi-turn simulated-user flows. This prevents dynamic routing or payload construction based on test-specific context

**Describe the solution you'd like**
I’d like test-level `vars` to be included in the `context["vars"]` parameter when `call_api()` is invoked on a custom provider, even during simulated-user runs. This would make context handling consistent between single-turn and multi-turn evaluations, and allow dynamic values like `workflow_id` to be accessible throughout the conversation.

**Describe alternatives you've considered**

**Additional context**
```yaml
providers:
  - id: file://provider.py
    config:
      base_url: base_url

defaultTest:
  provider:
    id: promptfoo:simulated-user
    config:
      maxTurns: 5

tests:
  - vars:
      workflow_id: 123-workflow
      session_id: 123-session
      instructions: |
        You are booking a one-way flight from New York to Seattle on May 20.
```
In this setup, `workflow_id` is not available inside the `context` argument of `call_api()` when using `simulated-user`
