### ISSUE TITLE
can we use repliacte's private models on promptfoo?

### ISSUE THREAD

**Issue by abrar-tericsoft** [promptfoo/promptfoo#508]

**Comment by typpo** [comment]
Yes, this is supported.  Remember to set `REPLICATE_API_KEY` for your account with the private model.

Your config would look something like this:
```yaml
providers:
  - id: replicate:path/to/you/model:version123456
    config:
      temperature: 0.01
      # ...
```
