### ISSUE TITLE
version 0.45.0 breaks python providers

### ISSUE THREAD

**Issue by mobidyc** [promptfoo/promptfoo#528]
Using the provider: `providers: ['python:call_llm.py']`

returns the error:
`[FAIL] Error: ModuleNotFoundError: No module named 'call_llm'`

downgrading to version 0.44.0 solves the issue in my case.

**Comment by typpo** [comment]
This might have something to do with relative paths or python paths, because the example at https://github.com/promptfoo/promptfoo/tree/main/examples/python-provider works ok for me still.

Can you re-run your eval with `LOG_LEVEL=debug` and let me know what the output is?  For example, `LOG_LEVEL=debug promptfoo eval`

**Comment by chiuchiu328** [comment]
I have the same issue and here is the log
![Screenshot 2024-03-07 at 4 02 57 PM](https://github.com/promptfoo/promptfoo/assets/9929375/2c7134b2-826c-4de1-ac95-36fbf57911b2)
and the error show in the prompt web
![Screenshot 2024-03-07 at 4 05 39 PM](https://github.com/promptfoo/promptfoo/assets/9929375/ae90549d-19bf-468b-9ab5-5e7282775c8f)
and the config file is 

```
description: 'promptfoo templete'

prompts:
  prompt/shelving_prompt.txt: shelving
  prompt/prompt_1.txt: prompt_1
  prompt/prompt_2.txt: prompt_2
  prompt/prompt_few_1.txt: prompt_few_1
  prompt/know_map_prompt.txt: understand

defaultTest:
  assert:
    - type: python
      value: file://evaluation/is_answer_type.py

providers:
  - id: 'python:provider/my_script.py'
    config:
      additionalOption: 123
    prompts: [understand]

tests: [test/short_info.yml]
```
