### ISSUE TITLE
`additionalOption` is not a dictionary in the `call_api` function from a python script

### ISSUE THREAD

**Issue by romaintoub** [promptfoo/promptfoo#529]
I've recently tested the config from a provider defined in a python script

I've followed the instructions in [the doc](https://promptfoo.dev/docs/providers/python/) but realized that the options variable is a string dictionary, for example if I define something like the following in a config file:
```
providers:
   - id: python:providers/eval_chain.py
     config:
         model_name: "xyz"
```
I'll get something like this for options:
```
"{"id":"python:providers/eval_chain.py","config":{"model_name":"xyz","basePath":"."}, "env":{}}"
```

The workaround that I use to solve this issue is to parse the options as a dict using `json.loads`, ie
```
def call_api(prompt, options, context):
    options_dict = json.loads(options)
    options.get("config").get("model_name", "default_model_name")
....
```
