### ISSUE TITLE
v0.45 breaks input data files

### ISSUE THREAD

**Issue by WilliamHua** [promptfoo/promptfoo#530]
v0.45 seems to break the ability to load input data

`promptfooconfig.yaml`

```
prompts:
  - file://prompt3.json
  - file://prompt7.json

providers:
  # - id: openai:chat:gpt-4-0613
  # - id: anthropic:completion:claude-3-opus-20240229
  - id: openai:chat:gpt-4-vision-preview

tests:
  - vars:
      data: file://data1.json
  - vars:
      data: file://data2.json
  - vars:
      data: file://data3.json
  - vars:
      data: file://data4.json
  - vars:
      data: file://data5.json
```

`npx promptfoo@v0.45 eval --no-cache` results in the model not seeing any of the input data
`npx promptfoo@v0.44 eval --no-cache` works as expected
