### ISSUE TITLE
Feature request: Load var from all *.txt files in a folder

### ISSUE THREAD

**Issue by hodanajan** [promptfoo/promptfoo#557]
First of all thank you very much for this tool, I've been looking for something like this and will be very useful for my workflow. There is one feature that I' missing (or perhaps it's possible to do already, but I don't know how). 

I'd like to be able to load vars from external files by providing a path with wildcards. 

Here is an example:
```
prompts:
  - "Identify language of the following text and extract all names of cities:\n{{text}}\n\nMake sure to anwer using valid JSON format."

providers:
  - openai:gpt-3.5-turbo
  - openai:gpt-4

tests:
#GENERAL tests - use for all texts
  - description: valid json
    vars:
      text: texts/*/*.txt
    assert:
      - type: is-json

#only for english texts
  - description: language check
    vars:
      text: texts/english/*.txt
    assert:
        - type: icontains-any
          value: ["english"]

#only for german texts
  - description: language check
    vars:
      text: texts/german/*.txt
    assert:
        - type: icontains-any
          value: ["german"]

#only for specific texts
  - description: correct city extracted?
    vars:
      text: file://texts/german/frankfurt.txt
    assert:
        - type: icontains-any
          value: ["frankfurt"]
```

In my use case I need to test against tens or hundreds of var values which can be categorized. Each category needs a different test. Some specific var values also need specific tests.

BTW I already sent this request on Discord, but thought here would be probably a better place for it. Thanks!
