### ISSUE TITLE
OpenRouter integration errors

### ISSUE THREAD

**Issue by dorperetz** [promptfoo/promptfoo#571]
Hey!

Seems like the openrouter provider isn't working.

Using this test file:

```
description: openrouter test
prompts:
  - Write a tweet about bananas
providers:
  - id: openai:chat:gpt-3.5-turbo
    config:
      apiBaseUrl: https://openrouter.ai/api
      apiKey: [real key]
tests:
  - vars:
    assert:
      - type: icontains
        value: banana
```

returns this error :

![image](https://github.com/promptfoo/promptfoo/assets/13338950/170c53e9-1c0e-48f9-9b6e-e75ecbec1d18)
