### ISSUE TITLE
[FAIL] Error: Unknown assertion type: contains-some

### ISSUE THREAD

**Issue by gp48maz1** [promptfoo/promptfoo#61]
The full error:

[FAIL] Error: Unknown assertion type: contains-some Error: Unknown assertion type: contains-some at runAssertion (/Users/me/.npm/_npx/1ddbeaccabfe00a4/node_modules/promptfoo/dist/src/assertions.js:256:11) at runAssertions (/Users/me/.npm/_npx/1ddbeaccabfe00a4/node_modules/promptfoo/dist/src/assertions.js:43:30) at Evaluator.runEval (/Users/me/.npm/_npx/1ddbeaccabfe00a4/node_modules/promptfoo/dist/src/evaluator.js:101:74) at async /Users/me/.npm/_npx/1ddbeaccabfe00a4/node_modules/promptfoo/dist/src/evaluator.js:277:25

I was just changing the initial test YAML

```
# This configuration runs each prompt through a series of example inputs and checks if they meet requirements.
#removed prompts.txt, 
prompts: [prompts-v1.txt]
providers: [openai:gpt-3.5-turbo-0613]
tests:
  - description: Test
    vars:
      var1: first variable's value
      var2: another value
      var3: some other value
    assert:
      - type: contains-some
        value:
          - "something "
          - "other "
          - "The other"
      - type: javascript
        value: 1 / (output.length + 1)  # prefer shorter outputs
```

... everything else is the same
