### ISSUE TITLE
Specify description for custom python providers, for display in web ui

### ISSUE THREAD

**Issue by alexclaydon** [promptfoo/promptfoo#655]
Hello,

At the moment, when using custom python script providers as follows:

```
providers:
  - id: 'python:../scripts/instructor_schema.py'
    config:
      llm_model: "gpt-4-0125-preview"
      evaluateOptions.maxConcurrency: 4
      evaluateOptions.repeat: 1
      evaluateOptions.delay: 500
      evaluateOptions.showProgressBar: true

  - id: 'python:../scripts/instructor_schema.py'
    config:
      llm_model: "gpt-3.5-turbo-0125"
      evaluateOptions.maxConcurrency: 4
      evaluateOptions.repeat: 1
      evaluateOptions.delay: 500
      evaluateOptions.showProgressBar: true
```

it doesn't appear to be possible to give each provider a useful descriptive name.  If, as above, running the same script with different `config`, it can be difficult to tell which column is for which provider.  Indeed, both columns are simple labelled `['{{ query }}']`.

Would it be possible to (i) give Python custom providers a custom name, and (ii) enable setting that custom name as column title in the web ui?

Many thanks for your attention!

**Comment by typpo** [comment]
Hey @alexclaydon,

I think what you're looking for is the `label` property:

```yaml
providers:
  - id: 'python:../scripts/instructor_schema.py'
    label: 'gpt-4-0125-preview via instructor_schema.py'
    config:
      llm_model: "gpt-4-0125-preview"
      evaluateOptions.maxConcurrency: 4
      evaluateOptions.repeat: 1
      evaluateOptions.delay: 500
      evaluateOptions.showProgressBar: true
  # ...
```

Let me know if that does the trick!
