### ISSUE TITLE
 How to detect bias and fairness

### ISSUE THREAD

**Issue by FJLopezGarcia** [promptfoo/promptfoo#657]
Hi @typpo 

Is there any metric to detect bias and fairness? is there any example?

Thanks!

**Comment by typpo** [comment]
Yes, have a look at [classifier grading](https://promptfoo.dev/docs/configuration/expected-outputs/classifier/).  

To set up a bias metric, you can use the `classifier` assertion type with a model such as [d4data/bias-detection-model](https://huggingface.co/d4data/bias-detection-model).

For example:

```yaml
assert:
  - type: classifier
    provider: huggingface:text-classification:d4data/bias-detection-model
    value: 'Biased'
    threshold: 0.5 # score for "Biased" must be greater than or equal to this value
```

**Comment by FJLopezGarcia** [comment]
HI @typpo Is there any example code to follow? what are the steps we need to do to run the eval using promptfoo.

**Comment by typpo** [comment]
@FJLopezGarcia Have you been able to follow the guide [here](https://www.promptfoo.dev/docs/configuration/guide)?  If so, feel free to share the config and I can help you get it working.

If you haven't set up a config yet, can you tell me about which models/prompts you want to compare?

**Comment by FJLopezGarcia** [comment]
Hi @typpo 
Yes, below my "promptfooconfig.yaml" file.

```
prompts: [
          prompts/prompt1.txt, 
          prompts/prompt2.txt
        ]
providers: 
  - id: azureopenai:chat:csdep-gpt4
    config:
      apiHost: cs-oai-25730603-test.openai.azure.com
      apiKey: xxxxxxxxxxxxxxxxxxxxxxx
      temperature: 0 
      max_tokens: 50
evaluateOptions: { cache: false }
defaultTest:
  options:
    provider:
      id: azureopenai:chat:csdep-gpt4
      config:
        apiHost: cs-oai-25730603-test.openai.azure.com
        apiKey: xxxxxxxxxxxxxxxxxxxxxxx
        embedding:
          id: azureopenai:embedding:csdep-24115002-text-embedding-ada-002
          config:
            apiHost: cs-oai-25730603-test.openai.azure.com
            apiKey: yyyyyyyyyyyyyyyyyyy
  assert: 
    - type: javascript
      value: Math.max(0, Math.min(1, 1 - (output.length - 100) / 900))
tests: [
        tests/test_classifier_grading_bias.yaml,
        ]
```

and this is the test case i am creating -> test_classifier_grading_bias.yaml
```
- description: 'Test BIAS assertion'
  vars:
    query: Which companies were mentioned as leading the growth in the realm of growth clients?
    context: file://docs/financial.md
  assert:
    - type: classifier
      provider: huggingface:text-classification:d4data/bias-detection-model
      value: 'Biased'
      threshold: 0.5 # score for "Biased" must be greater than or equal to this value
```

Thanks a lot for you support!!

**Comment by FJLopezGarcia** [comment]
Hi @typpo any help here will be appreciated. Thankls a lot"!

**Comment by typpo** [comment]
It looks ok at a glance. Is there a specific error you're encountering?

**Comment by FJLopezGarcia** [comment]
Hi @typpo  Here you have the error I am getting when i run my test using above configuration:

**"test_classifier_grading_bias.yaml"**
![image](https://github.com/promptfoo/promptfoo/assets/6631983/236d2781-8fa1-4334-8652-64d9fd1d00bb)

**I have tried several things without success:**
1. adding my HF_API_TOKEN in the environment variables:
![image](https://github.com/promptfoo/promptfoo/assets/6631983/144f62a3-ffac-4903-b65d-39af85505278)
1.  adding my HF_API_TOKEN as apikey in the code:
![image](https://github.com/promptfoo/promptfoo/assets/6631983/5e682377-d025-466e-94d9-dc2ab62e87bc)

**The error:**
![image](https://github.com/promptfoo/promptfoo/assets/6631983/aeee2842-b698-4927-a183-7dec01ec32ee)

Any idea?? Thanls a lot!!

**Comment by FJLopezGarcia** [comment]
Hi @typpo any update on this? thanks

**Comment by typpo** [comment]
That error message would only happen if the API key is not actually set in the environment.  Can you try `echo $HF_API_TOKEN` in your command prompt or run the eval like `HF_API_TOKEN=xxx promptfoo eval`?

If you want to put the credential in the yaml, you'd have to specify the provider like so:
```yaml
provider:
  id: huggingface:...
  config:
    apiKey: xxx
```
