### ISSUE TITLE
add header with provider information

### ISSUE THREAD

**Issue by pelikhan** [promptfoo/promptfoo#710]
We have a test scenario with multiple providers and a few tests. Would it be possible to add a header cell on the output column with the id/label of the provider?

**Comment by typpo** [comment]
Hi @pelikhan, I may not be understanding this ask correctly.  Currently the id/label should appear at the top of the table in the header.

![image](https://github.com/promptfoo/promptfoo/assets/310310/6c4e4151-8aba-480b-8eb2-07b9fc362ded)

**Comment by pelikhan** [comment]
Ah, I don't see it.
![image](https://github.com/promptfoo/promptfoo/assets/4175913/c00b1443-104e-4714-a626-77ed8114a283)

Could this be because I use a custom provider?

```yaml
description: summarize all files
prompts:
  - summarize
providers:
  - id: provider.mjs
    label: gpt-4
    config:
      model: gpt-4
tests:
  - vars:
      files: src/rag/markdown.md
    asserts:
      - type: llm-rubric
        value: is a summary
      - type: factuality
        value: Markdown is a text-based syntax to generate documents
      - type: icontains
        value: Markdown
```
