### ISSUE TITLE
Feature Request: Version Release LLM-Judged Metrics To Enable Pinning

### ISSUE THREAD

**Issue by thomascleberg** [promptfoo/promptfoo#712]
I want to ensure that I can use a specific version of a specific metric (using the current prompt and generation method, for example) and be guaranteed of continuing to use that same setting going forward, regardless of whether the default changes in this project.

Updated metric functionality would create a new version. Version could default to "latest" to use the latest version.

Desired state:
```yaml
  assert:
    - type: context-faithfulness
      version: 1.0
```
