### ISSUE TITLE
Error running database migrations: Cannot open database because the directory does not exist

### ISSUE THREAD

**Issue by pelikhan** [promptfoo/promptfoo#723]
I have been facing a puzzling error that was occurring only on the github actions runs. I wonder if anyone has faced before?

![image](https://github.com/promptfoo/promptfoo/assets/4175913/ea081ce8-c604-4ad5-95cc-dc04c581d219)

- workflow file:

```yaml
name: nightly test

on:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            OPENAI_API_TYPE: ${{ secrets.OPENAI_API_TYPE }}
            OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
            AZURE_OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
            AZURE_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            PROMPTFOO_CACHE_PATH: .genaiscript/cache/promptfoo
            PROMPTFOO_DISABLE_UPDATE: 1
        steps:
            - name: Set up promptfoo cache
              uses: actions/cache@v2
              with:
                  path: .genaiscript/cache/promptfoo
                  key: ${{ runner.os }}-promptfoo-v1
                  restore-keys: |
                      ${{ runner.os }}-promptfoo-
            - uses: actions/checkout@v3
              with:
                  submodules: "recursive"
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: "20"
                  cache: yarn
            - run: yarn install --frozen-lockfile
            - name: typecheck
              run: yarn typecheck
            - name: compile
              run: yarn compile
            - name: run test within scripts
              run: yarn test:scripts
```
