### ISSUE TITLE
Docs request: where does histogram come from?

### ISSUE THREAD

**Issue by jamesbraza** [promptfoo/promptfoo#738]
I have three possible scores: 0, 0.1, and 1 for a Python assertion, and two basic assertions.

```yaml
providers:
  - openai:chat:gpt-4-0613
  - openai:chat:gpt-4-turbo-2024-04-09
  - anthropic:messages:claude-3-sonnet-20240229
defaultTest:
  assert:
    - description: was answered
      type: not-icontains
      value: cannot answer
    - description: has sentences
      type: javascript
      value: output.length > 20
    - description: check value
      type: python
      value: file://assert.py
```

At the top of my `promptfoo view`, I see bins around 0.6 and 0.7, which isn't quite making sense to me:

![screenshot of histogram](https://github.com/promptfoo/promptfoo/assets/8990777/d79d8e29-b5ae-4452-a575-cfcd88219922)

The request is, can we add a little description such that this figure is easy to understand.
- I have three different model providers, is that where Prompt 1 (red), Prompt 2 (blue), and Prompt 3 (green) come from?
- Why does the histogram show scores of `0.6` and `0.7`? Is that like a sum of multiple assertions' scores?
