### ISSUE TITLE
Feature Request: Assertion Sets

### ISSUE THREAD

**Issue by thomascleberg** [promptfoo/promptfoo#757]
There are meaningful test cases in which at least one of as set of assertions needs to pass, but not all of them need to pass. 

it would be useful to be able to define an assertion that defines sub-assertions and the pass criteria for the assertion set.

Each of the assertions in the set could calculate and produce metrics like other assertions, but would be individually exempted from having a failing result cause a failure for the record.

Example sketch:
```yaml
assert:
    - type: context-faithfulness
      threshold: 0.9
      metric: Groundedness
    - type: assertion-set
      value: >= 1 pass
      assert: 
          - <assertion A>
          - <assertion B>
          - ...
```
