### ISSUE TITLE
Multiline vars replacement break indentation in config generation

### ISSUE THREAD

**Issue by yleflour** [promptfoo/promptfoo#759]
## Current situation

If the promptfile contains this:

```yaml
- role: user
  content: |
    The file content is:
    ```
    {{fileContent}}
    ```
```

And the configfile contains this:
```yaml
tests:
  - vars:
      fileContent: |
        // Sample comment
        export const hello = "word"
```

The resulting output is:
```yaml
- role: user
  content: |
    The file content is:
    ```
    // Sample comment
export const hello = "word"
\```
```

Which is invalid

## Expect result

A multiline var value should be indented as well:
```yaml
- role: user
  content: |
    The file content is:
    ```
    // Sample comment
    export const hello = "word"
    ```
```
