### ISSUE TITLE
not-equals is not working

### ISSUE THREAD

**Issue by ekrobj** [promptfoo/promptfoo#762]
# Expected Behavior

`not-equals` assertions should behave as the name suggests (negate an equals).

# Current Behavior

The `not-` prefix is getting ignored for `equals` assertions. Therefore it behaves like an `equals`.

# Failure Information (for bugs)
## False negative
```
description: 'Eval'
prompts:
  - prompts/prompt.json
providers:
  - id: openai:gpt-3.5-turbo
    config:
      temperature: 1
      max_tokens: 4096
      best_of: 1
tests:
  - assert:
    - type: not-equals
      value: saddfajdsa
```
![image](https://github.com/promptfoo/promptfoo/assets/167216434/d222160d-448e-49fc-9236-a824ceb25be2)
## False positive
```
description: 'Eval'
prompts:
  - prompts/prompt.json
providers:
  - id: openai:gpt-3.5-turbo
    config:
      temperature: 1
      max_tokens: 4096
      best_of: 1
tests:
  - assert:
    - type: not-equals
      value: Hello
```
![image](https://github.com/promptfoo/promptfoo/assets/167216434/86231e4f-02c7-459e-bb3b-808057f8ea9d)

## Bug in source
https://github.com/promptfoo/promptfoo/blob/ac542d1801a819fd8ad267188848814c1ecc6a10/src/assertions.ts#L276-L286

## Additional information
`not-contains` works as example:
```
description: 'Eval'
prompts:
  - prompts/prompt.json
providers:
  - id: openai:gpt-3.5-turbo
    config:
      temperature: 1
      max_tokens: 4096
      best_of: 1
tests:
  - assert:
    - type: not-contains
      value: saddfajdsa
```
![image](https://github.com/promptfoo/promptfoo/assets/167216434/d3c52e20-8fe1-400e-b9b9-b0631c0cc1fc)
