### ISSUE TITLE
How to test prompt with triple dashes inside without breaking into separate prompts?

### ISSUE THREAD

**Issue by SamComber** [promptfoo/promptfoo#789]
I have a prompt that post-RAG has retrieved docs separated by a triple dash, `---`, i.e the below. Command I'm running is `npx promptfoo@latest eval  --tests tests.csv --providers openai:gpt-3.5-turbo --output output.json`, and the `promptfooconfig.yaml` is:

 ```
env: {}
description: ''
providers:
  - id: openai:gpt-3.5-turbo-0613
    config:
      temperature: 0.5
      max_tokens: 1024
      top_p: 1
      frequency_penalty: 0
      presence_penalty: 0
prompts:
  - "This is my system prompt...\nThe current date is Friday, 17 May 2024.n--- Snippet from blog (url_name = url) ---\n--- End snippet ---\n--- Snippet from blog (url_name = url) ---\n--- End snippet ---"
tests: 
defaultTest: {}
evaluateOptions: {}

```

```
This is my system prompt...
The current date is Friday, 17 May 2024.

--- Snippet from blog (url_name = url) ---
<text>
--- End snippet ---
--- Snippet from blog (url_name = url) ---
<text>
--- End snippet ---
```

Currently, these are truncating into separate prompts...

<img width="794" alt="image" src="https://github.com/promptfoo/promptfoo/assets/9962584/a845ad31-0b58-4a51-ad3b-12fbf3c828a3">

Is there a way around this?
