### ISSUE TITLE
Web ui doesn't support object prompts config

### ISSUE THREAD

**Issue by kongmoumou** [promptfoo/promptfoo#803]
I want to test different prompt for different model, and the `promptfooconfig.yaml` content like below ⬇️

```yaml
prompts:
  prompt-1.yaml: prompt-1
  prompt-2.yaml: prompt-2
providers:
  - id: openai:gpt-4-turbo-preview
    prompts:
      - prompt-1
  - id: openai:gpt-4o
    prompts:
      - prompt-2
```

when using promptfoo cli, it works as expected. but it's not working while directly pasting yaml to web ui, error shows below ⬇️

![image](https://github.com/promptfoo/promptfoo/assets/35442047/52a1f45e-02f5-4078-8e6f-f889b3932abc)

**Comment by mldangelo** [comment]
@kongmoumou We deprecated the object syntax in favor of array syntax. There's a good example of the syntax here: prompt-1 You should be able to run:

```yaml
prompts:
  - id: prompt-1.yaml
    label: prompt-1
  - id: prompt-2.yaml
    label: prompt-2
providers:
  - id: openai:gpt-4-turbo-preview
    prompts:
      - prompt-1
  - id: openai:gpt-4o
    prompts:
      - prompt-2
```

I hope this helps.
