### ISSUE TITLE
Allow overriding provider config in prompt or test case

### ISSUE THREAD

**Issue by tomquist** [promptfoo/promptfoo#815]
Currently, all provider config must be done at the top-level. It's not possible to run the same provider with different configuration. It should be possible to override the provider config at the test-case or prompt level (or both).

**Comment by mldangelo** [comment]
Hi @tomquist,

Good news - this feature is now fully supported!

You can run the same provider with different configurations in two ways:

**1. Define the same provider multiple times with different labels:**
```yaml
providers:
  - id: openai:gpt-4
    label: low-temp
    config:
      temperature: 0.1
  - id: openai:gpt-4
    label: high-temp
    config:
      temperature: 1.5
```

**2. Override provider config at the test-case level:**
```yaml
providers:
  - openai:gpt-4

tests:
  - vars:
      question: "Test question"
    provider:
      id: openai:gpt-4
      config:
        temperature: 1.5
```

See the [Configuration Reference](https://www.promptfoo.dev/docs/configuration/reference#provideroptions) for complete details on ProviderOptions.

Since this issue is from May 2024 and the feature is now working, I'm closing it. If you have any follow-up questions, feel free to comment or re-open!

Thanks!
