### ISSUE TITLE
Not working using text prompt with Palm2 Google Vertex API

### ISSUE THREAD

**Issue by rmonteiro89** [promptfoo/promptfoo#826]
Hi, 

I tried to use this tool using the provider `vertex:text-bison@002` as the config file below:
```
# Learn more: https://promptfoo.dev/docs/configuration/guide
description: 'Testing'

prompts:
  - 'Convert this English to {{language}}: {{input}}'

providers:
  - id: vertex:text-bison@002
    config:
      generationConfig:
        temperature: 0.4
        maxOutputTokens: 1024
        topP: 0.95

tests:
  - vars:
      language: Portuguese
      input: Hello my old friend!
```

It returned the error:
```
"status":400,"code":400,"errors":[{"message":"Invalid instance: input has an instance that's missing a prompt field","domain":"global","reason":"badRequest"}]
```

Checking the source code, it looks like this tool only works for the Palm2 Chat API. 

Is it intentional, or could I open a PR to fix/add it?

Edit:
it looks like it is a simple change https://cloud.google.com/vertex-ai/generative-ai/docs/text/test-text-prompts.
