### ISSUE TITLE
Ensure percent complete accurately reflects test suite

### ISSUE THREAD

**Issue by chrismaltais** [promptfoo/promptfoo#858]
I have the following promptfoo config file:
```yaml
description: 'Segmenter'
prompts:
- " "
providers:
- id: 'python:src/segmenter/provider.py'
  label: 'Staging'
  config:
    env: 'staging'
    storage_folder: 'test/staging'
- id: 'python:src/segmenter/provider.py'
  label: 'Production'
  config:
    env: 'production'
    storage_folder: 'test/production'
tests: src/segmenter/tests.yaml
evaluateOptions:
  maxConcurrency: 2
  delay: 500
  showProgressBar: true
  cache: false
```

Where the `src/segmenter/tests.yaml` file looks like:
```yaml
- description: Apparel and Accessories
  vars:
    originalImage: "![image](https://example.com/some_image.png)"
  assert:
    - type: latency
      threshold: 2000
- description: Apparel and Accessories
  vars:
    originalImage: "![image](https://example.com/some_image.png)"
  assert:
    - type: latency
      threshold: 2000
- description: Apparel and Accessories
  vars:
    originalImage: "![image](https://example.com/some_image.png)"
  assert:
    - type: latency
      threshold: 2000
```

When I run these tests via the web ui, I'm expecting the results to go 0 -> 33% -> 66% -> 100% (i.e. updating based on the number of variables).

However, the web ui stays at 0% until all the tests are completed, then redirects me to the evals page:
https://github.com/promptfoo/promptfoo/assets/17098959/9457aac4-a284-4246-ba76-0dc7d9509cf5
