### ISSUE TITLE
Support for loading test cases from directory

### ISSUE THREAD

**Issue by KasperDjernaes** [promptfoo/promptfoo#86]
## Description

To facilitate easier management, discussion, and understanding of individual test cases, it would be beneficial to allow defining and loading tests (consisting of variables and assertions pairs) from a specified directory.

## Proposed Implementation

Consider a scenario where the test definitions could be mentioned in a configuration file in the following way:

promptfooconfig.yaml
```yaml
prompts: [prompts/prompt1.yaml]
providers: [openai:gpt-3.5-turbo]
tests: './tests/
```

Where the test directory would look like this:

```
tests
├── 1.yaml
├── 2.yaml
└── 3.yaml
```

Each yaml will then hold the defintion of the input vars and the assertions for one specific test case:

```yaml
vars:
  text: Some input text for the test
assert:
  - type: not-contains-any
    value:
      - "diagnose"
  - type: contains-all
    value:
      - "enigmatic creatures"
  - type: similar
    value: Some input text for the testing
    threshold: 0.95
```

## Potential Benefits:

**1. Granular Test Case Management:** This structure enables users to work with each test case as a separate unit, alleviating the necessity of maintaining all test cases within a single file.

**2. Facilitates Discussion:** A numerical test case system allows teams to easily refer and discuss specific test cases.

**3. Grouping Tests:** This structure would enable users to categorize their tests based on directory names (for example, tests/accuracy/ and tests/creativity/), enabling easier comparison of prompt performance across various performance categories, rather than on an aggregate measure across all tests.

Currently, while tests.csv is used, it does not allow defining multiple assertions for the same variable. This proposed change will be especially useful when the number of assertions for each test case is significantly large, making their management in separate files more efficient.

I'm open to contributing towards the implementation of this feature. Please let me know if any additional information is required.
