### ISSUE TITLE
python external assertion not working

### ISSUE THREAD

**Issue by apatil4** [promptfoo/promptfoo#869]
Hey team, I am using promptfoo to evaluate certain of our internal models LLMs. it seems like the python assertion using an external script always returns ```Python code execution failed: Python assertion must return a boolean, number, or {pass, score, reason} object```

below is my assert.py taken from the `examples` directory
```
def get_assert(output, context):
    print('Prompt:', context['prompt'])
    print('Vars', context['vars']['topic'])

    # You can return a bool...
    # return 'bananas' in output.lower()

    # A score (where 0 = Fail)...
    # return 0.5

    # Or an entire grading result...
    return {
        'pass': True,
        'score': 0.5,
        'reason': 'Contains banana',
    }
```

and below is the promptfoo config
```
# This configuration compares LLM output of 2 prompts x 2 GPT models across 3 test cases.
# Learn more: https://promptfoo.dev/docs/configuration/guide
description: 'My first eval'

prompts:
  - "Write a tweet about {{topic}}"

providers:
  - id: 'python:provider.py'
    config:
      additionalOption: llama
  - id: 'python:provider.py'
    config:
      additionalOption: phi

tests:
  - description: 'Tweet about bananas'
    vars:
      topic: bananas
    assert:
      - type: python
        value: file://assert.py
```

Attached a screenshot of the error I am getting
<img width="1493" alt="promptfoo_and_Activity_-_Hyperscience_-_Slack" src="https://github.com/promptfoo/promptfoo/assets/1051178/bb723ee9-810c-4f16-a331-a2b9a56ec9a4">
