### ISSUE TITLE
Specify a label with a prompt function

### ISSUE THREAD

**Issue by gibbster** [promptfoo/promptfoo#874]
Hello, I'm trying to specify labels so that I can use different prompts with different models (as described here: https://www.promptfoo.dev/docs/configuration/parameters#different-prompts-per-model) but also use prompt functions (https://www.promptfoo.dev/docs/configuration/parameters#prompt-functions). 

Is that possible? I tried the naive thing of specifying the javascript file as the prompt id and providing a label, but that led to the prompt being ignored and nothing being executed. To double check my setup, I then swapped the javascript file with a text file and that worked correctly.

**Comment by typpo** [comment]
Looks like the `label` property is not supported in two cases:

1. Native Javascript provider functions
2. Referencing a Javascript file

Both fixed in #875!

**Comment by typpo** [comment]
This change is released in 0.62.0

**Comment by gibbster** [comment]
Hm - I see that we can now add a label to a provider when that provider is specified with javascript, but can we provide a label to a prompt specified by js? I apologize if I misunderstood, but I was thinking that something like this would be supported: 

```
prompts:
  - id: prompts/prompts.js:v1
    label: simple
  - id: prompts/prompts.js:addAssumptions
    label: simple
  - id: prompts/prompts.js:addAssumptionsFixThreshold
    label: simple

providers:
  - id: bedrock:anthropic.claude-3-sonnet-20240229-v1:0
    config:
      region: 'us-east-1'
      temperature: 0.0
      max_tokens: 4096
    prompts:
      - simple
```
When I try that, it doesn't fail exactly, but it finds no test cases
