### ISSUE TITLE
[Web UI] Show assertion details when using assert-set

### ISSUE THREAD

**Issue by sjsinju** [promptfoo/promptfoo#919]
Thank you for adding #765 (assert-set) and #903 (__threshold for csv). 👍 

I thought below should be shown same behavior.

a.yaml
```
- vars:
      abc: "test"
- assert:
      type: assert-set
      threshold: 0.5
      assert:
        - type: python
          value: "file://a.py"
        - type: python
          value: "file://b.py
```

a.csv
| abc | __expected1 | __expected2 | __threshold |
| - | - | - | - |
| test | file://a.py | file://b.py | 0.5 |

But I got results on Web UI
1. for `a.yaml` : Just shown `Aggregate score 1 > 0.5 threshold` in detail view
![image](https://github.com/promptfoo/promptfoo/assets/17977017/3b9b176b-97d8-4ea4-8267-7efdc8cd8661)

2. for `a.csv` : `Aggregate score 1 > 0.5 threshold` in overview is same with `a.yaml`, but detail view shows pass/fail details for all of assertions

Is this the intended result?
I think 1 should also show assertions details in detail view same as 2. If no, could you explain this differences?

**Comment by mldangelo** [comment]
Hey @sjsinju! Thanks for the detailed bug report – and apologies for the long delay in getting back to you!

Great news: this has been fixed! 🎉

## What was happening

You correctly identified that YAML `assert-set` and CSV `__expected` columns were behaving differently. The root cause was how assertion results were structured:

| Format | Result Structure |
|--------|------------------|
| CSV `__expected` columns | Assertions flat → results directly in `componentResults` ✓ |
| YAML `assert-set` | Assertions nested → results buried in `componentResults[0].componentResults` ✗ |

The UI reads `componentResults` to display the Evaluation panel, so with `assert-set`, it only saw the aggregate result ("Aggregate score 1 > 0.5 threshold") and missed the sub-assertion details.

## The fix

In PR #3142, we refactored the assertion result handling to automatically **flatten nested results**. Now when you use `assert-set`:

```yaml
- assert:
    type: assert-set
    threshold: 0.5
    assert:
      - type: python
        value: "file://a.py"
      - type: python
        value: "file://b.py"
```

The detail view will show:
1. The aggregate `assert-set` result with threshold info
2. **Each individual sub-assertion** with its pass/fail status, score, and reason

This matches the behavior you expected from CSV! Closing this as resolved. Thanks again for the thorough report with screenshots – it really helped track this down!
