### ISSUE TITLE
Alternative to Nunjucks?

### ISSUE THREAD

**Issue by therealpaulgg** [promptfoo/promptfoo#92]
One issue I've encountered frequently with Nunjucks is that because it is designed to work with HTML templating, it by default really wants to add HTML-escaped characters to anything it templates.

For example:

```yaml
- role: system
  content: |
    You are a helpful assistant which suggests users healthy snacks to purchase

- role: user
  content: '{{ request }}'
```

For the 'request' variable, nunjucks will HTML escape any characters that are deemed sensitive. Just a couple of examples:
- '<' becomes '&lt'
- '>' becomes '&gt'
- '"' becomes '&quot'

Given the general sensitivity of LLMs, I'd like to ensure prompts in general are as close to natural language as possible. I have noticed greater quality outputs the more natural language is used.

We can use the 'safe' keyword in some circumstances but not all. For example trying to use 'safe' in the above example could result in a malformed YAML file.

Trying to think of perhaps a specific templating alternative for YAML..
