### ISSUE TITLE
ValidationException: Malformed input request when using Cohere embedding with Bedrock provider

### ISSUE THREAD

**Issue by RobinGroundfog** [promptfoo/promptfoo#921]
I have the following configuration:

```
defaultTest:
  options:
    provider:
      text:
        id: bedrock:anthropic.claude-3-haiku-20240307-v1:0
        config:
          region: eu-central-1
      embedding:
        id: bedrock:embeddings:cohere.embed-english-v3
        config:
          region: eu-central-1

...
tests:
    - type: answer-relevance
      threshold: 0.9
```

I get the following error when running `promptfoo eval`:
```
API call error: ValidationException: Malformed input request: #: required key [texts] not found#: required key [input_type] not found#: extraneous key [inputText] is not permitted, please reformat your input and try again.
```

This error disappears when I'm using another Bedrock vector model such as amazon.titan-embed-text-v1 so I assume the error doesn't come from my configuration
