### ISSUE TITLE
OpenAI Assistant - Single conversation/thread with multiple messages

### ISSUE THREAD

**Issue by tenhsor1** [promptfoo/promptfoo#950]
I'm trying to assert the result of an OpenAI Assistant as per the docs here: https://www.promptfoo.dev/docs/guides/evaluate-openai-assistants/ but can't find a way to prepend the new test messages to a previous thread/conversation, there's a way to do this?

ie:
```
prompts:
  - '{{message}}'

providers:
  - openai:assistant:...
tests:
    vars:
      message: ['Who founded Facebook?', 'When was he born?'] # the last message here is not added to the assistant thread
```

**Comment by typpo** [comment]
You'd have to build multiple messages into the prompt itself, for example by having a variable for previous chat messages.  See https://www.promptfoo.dev/docs/configuration/chat/

**Comment by tenhsor1** [comment]
@typpo I was able to use the prompt in that configuration for simulating a conversation, now I have a different problem: I want to have multiple different conversations to be part of a single test suite, there's a way to do this?
Something like this:
```
description: ''

prompts: [prompt.json]

providers:
 - openai:gpt-4o

tests:
  - description: "Conversation 1"
    - vars:
        question: Who founded Facebook?
    - vars:
        question: Where does he live?
    - vars:
        question: Which state is that in?
  - description: "Conversation 2"
    - vars:
      question: Who founded Twitter?
    - vars:
      question: "Is he into Bitcoin?"
 
```

Where ideally, each vars could have its own assertion as well.
