### ISSUE TITLE
Tests inside Scenarios not Filtered by --filter-pattern

### ISSUE THREAD

**Issue by aantn** [promptfoo/promptfoo#987]
config.yaml:
```
providers:
  - id: 'python:./holmes_runner.py'
    config:
      holmesFlags: "--verbose"

scenarios:
  - config:
    - vars:
        ... 

    tests:
      - description: SomeTest
        vars:
          ...
```

When I run the following, I would expected SomeTest to not run, but it does run:
```console
$ promptfoo eval -c config.yaml --filter-pattern nomatch
```

**Comment by aantn** [comment]
Cleaned up the example a little to remove irrelevant bits

**Comment by aantn** [comment]
To elaborate a little more on the motivation here, I have tests that should run on the same scenario data, but which can't run at the same time as the scenarios are not re-entrant. I would like to solve this by invoking promptfoo twice in a row, each time with a separate test. (I also considered having 2 promptfoo configs and re-using the scenario data as external var files - hence the other GitHub issue I opened recently.)

**Comment by mldangelo** [comment]
Fix in https://github.com/promptfoo/promptfoo/pull/996 Thank you @aantn!

**Comment by aantn** [comment]
Wonderful, thanks. Any ideas when the next release will be?

**Comment by maeltha** [comment]
Hi, was this feature implemented? I tried the same having in my code 
```
scenarios:
  - config:
    - vars:
        prompt: file://./prompt.txt
        format_instructions: file://./format_instructions.txt
    tests:
      - description: 'test'
        vars:
```

but when I execute `promptfoo eval --filter-pattern 'something'` the test is executed nonetheless..
using promtfoo 0.100.5
